<?xml version="1.0" encoding="Shift_JIS"?>
<?xml-stylesheet type="text/xsl" href="hoot.xsl"?>
<!DOCTYPE gamelist [
	<!ELEMENT gamelist (game|bind|childlists)*>
	<!ATTLIST gamelist date CDATA #IMPLIED>
	<!ELEMENT childlists (list)*>
	<!ELEMENT list (#PCDATA)>
	<!ELEMENT bind (exts,driver,options?)>
	<!ELEMENT exts (ext)*>
	<!ELEMENT ext (#PCDATA)>
	<!ELEMENT game (name,driver,driveralias?,options?,romlist?,titlelist?)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT driver (#PCDATA)>
	<!ATTLIST driver type CDATA #IMPLIED>
	<!ELEMENT driveralias (#PCDATA)>
	<!ATTLIST driveralias type CDATA #IMPLIED>
	<!ELEMENT options (option)*>
	<!ELEMENT option EMPTY>
	<!ATTLIST option name CDATA #REQUIRED
					 value CDATA #REQUIRED>
	<!ELEMENT romlist (rom)*>
	<!ATTLIST romlist archive CDATA #IMPLIED>
	<!ELEMENT rom (#PCDATA)>
	<!ATTLIST rom type CDATA #REQUIRED
				  offset CDATA #IMPLIED
				  crc32 CDATA #IMPLIED>
	<!ELEMENT titlelist (title)*>
	<!ELEMENT title (#PCDATA)>
	<!ATTLIST title code CDATA #REQUIRED
					type CDATA #IMPLIED>
]>
<gamelist date="2005/02/13">
	<bind>
		<exts>
			<ext>pce</ext>
			<ext>hes</ext>
		</exts>
		<driver type="hes">pcengine</driver>
		<options>
			<option name="adpcm" value="0x01"/>
		</options>
	</bind>
	<bind>
		<exts>
			<ext>kss</ext>
		</exts>
		<driver type="kss">msx</driver>
		<options>
			<option name="ay_mix" value="0x5a"/>
			<option name="sn_mix" value="0xf0"/>
			<option name="fmpac_mix" value="0x280"/>
			<option name="fmunit_mix" value="0x280"/>
			<option name="msxa_mix" value="0x160"/>
			<option name="scc_mix" value="0xa3"/>
		</options>
	</bind>
	<bind>
		<exts>
			<ext>mdx</ext>
		</exts>
		<driver type="mxdrv">x68k</driver>
		<options>
			<option name="opm_mix" value="0xc0"/>
			<option name="pcm_mix" value="0xf0"/>
		</options>
	</bind>
	<bind>
		<exts>
			<ext>nsf</ext>
		</exts>
		<driver type="nsf">nes</driver>
		<options>
			<!--
				デフォルトの音量バランスの調整は
				・RFモジュレータ撤去 + 5V化の旧ファミコン(2A03E) + TNS-HFC3で調整してます。
				FCはロットによってバランスが変わる(特にFDS)ので、各デバイスの音量は好みに合わせて調整してください。

				n163realmode, fdsrealmode, nesrealdacの設定数値は以下(NEZplug++のドキュメントより)

				n163realmode (default: 1)
				└Namco163の拡張音源の音質の設定です。実機に近い音を鳴らしたい場合、推奨設定は1です。
					0にすると、波形がきれいに出力されます。
					1にすると、実機に近い音質で出力されます。さらに、ch数が8の時は高音域ノイズも乗せます。
					2にすると、実機に近い音質で出力されます。ch数に関わらず、高音域ノイズは乗せません。
					3にすると、実機に近い音質で出力されます。ch数に関わらず、高音域ノイズは乗せます。
					上記に0x80を足すと古いmckでコンパイルされたデータ用に旧ルーチンを使用します。(hootオリジナル)
					ただし新型NSD.Libの使用が判別できた場合で0x80以上の指定がある場合、0x80分が引かれて新ルーチンが強制的に使用されます。

				fdsrealmode (default: 3)
				└FDSの拡張音源の音質の設定です。実機に近い音を鳴らしたい場合、推奨設定は3です。
					0にすると、波形がきれいに出力されます。
					1にすると、波形にローパスフィルタがかかります。
					2にすると、波形のひずみを再現します。2C33から直接音を取ったような感じです。
					3にすると、波形のひずみを再現し、ローパスフィルタもかけます。実機に近い感じです。

				nesrealdac (default: 1)
				└1にすると、ファミコン内蔵音源の出力がひずみます。
					0だと、ひずまずに素直な波形になります。

				※下のnezと設定が分かれているので間違えないようにしてください
			-->
			<option name="fds_mix" value="0xd0"/>
			<option name="fdsrealmode" value="0"/>
			<option name="nesrealdac" value="0"/>
		</options>
	</bind>
	<bind>
		<exts>
			<ext>nez</ext>
		</exts>
		<driver type="nez">nes</driver>
		<options>
			<option name="fds_mix" value="0xd0"/>
			<option name="fdsrealmode" value="0"/>
			<option name="nesrealdac" value="0"/>
		</options>
	</bind>
	<bind>
		<exts>
			<ext>gbs</ext>
			<ext>gbr</ext>
		</exts>
		<driver type="gbs">gb</driver>
	</bind>
	<bind>
		<exts>
			<ext>spc</ext>
		</exts>
		<driver type="spc">snes</driver>
	</bind>
	<bind>
		<exts>
			<ext>bgm</ext>
		</exts>
		<driver type="kinro5">msx</driver>
		<options>
			<option name="scc_mix" value="0x108"/>
			<option name="psg_mix" value="0xd4"/>
			<option name="opll_mix" value="0x250"/>
		</options>
	</bind>
	<bind>
		<exts>
			<ext>mpk</ext>
		</exts>
		<driver type="mpk">msx</driver>
		<options>
			<option name="scc_mix" value="0x108"/>
			<option name="psg_mix" value="0xd4"/>
			<option name="opll_mix" value="0x250"/>
		</options>
	</bind>
	<bind>
		<exts>
			<ext>mgs</ext>
		</exts>
		<driver type="mgsdrv">msx</driver>
		<options>
			<option name="scc_mix" value="0x108"/>
			<option name="psg_mix" value="0xd4"/>
			<option name="opll_mix" value="0x250"/>
		</options>
	</bind>
	<bind>
		<exts>
			<ext>pt3</ext>
		</exts>
		<driver type="pt3">msx</driver>
	</bind>

	<childlists>
		<!-- ================ 1 ================ -->
		<list>xml/13cm.xml</list>
		<list>xml/21st_century.xml</list>
		<!-- ================ A ================ -->
		<list>xml/abogado_powers.xml</list>
		<list>xml/abstrax.xml</list>
		<list>xml/acclaim.xml</list>
		<list>xml/accolade.xml</list>
		<list>xml/acer.xml</list>
		<list>xml/acid_plan.xml</list>
		<list>xml/active.xml</list>
		<list>xml/activision.xml</list>
		<list>xml/adk.xml</list>
		<list>xml/advanced_programming.xml</list>
		<list>xml/agumix.xml</list>
		<list>xml/ail.xml</list>
		<list>xml/aion.xml</list>
		<list>xml/alfasystem.xml</list>
		<list>xml/alicesoft.xml</list>
		<list>xml/allex.xml</list>
		<list>xml/allot.xml</list>
		<list>xml/amorphous.xml</list>
		<list>xml/ange.xml</list>
		<list>xml/anjin.xml</list>
		<list>xml/apogee.xml</list>
		<list>xml/apple_pie.xml</list>
		<list>xml/apricot.xml</list>
		<list>xml/arc_developments.xml</list>
		<list>xml/arsys.xml</list>
		<list>xml/artdink.xml</list>
		<list>xml/artec.xml</list>
		<list>xml/ascii.xml</list>
		<list>xml/ascon.xml</list>
		<list>xml/atari.xml</list>
		<list>xml/atlus.xml</list>
		<list>xml/attic.xml</list>
		<list>xml/audiogenic.xml</list>
		<list>xml/aypio.xml</list>
		<!-- ================ B ================ -->
		<list>xml/backspin.xml</list>
		<list>xml/bandai.xml</list>
		<list>xml/banpresto.xml</list>
		<list>xml/basement.xml</list>
		<list>xml/basho_house.xml</list>
		<list>xml/bethesda.xml</list>
		<list>xml/bio_100%.xml</list>
		<list>xml/birdy_soft.xml</list>
		<list>xml/bit2.xml</list>
		<list>xml/bitmap_brothers.xml</list>
		<list>xml/bit_brother_software.xml</list>
		<list>xml/black_package.xml</list>
		<list>xml/blizzard.xml</list>
		<list>xml/blucky.xml</list>
		<list>xml/blue_byte.xml</list>
		<list>xml/bnn.xml</list>
		<list>xml/bonbeebonbon.xml</list>
		<list>xml/bothtec.xml</list>
		<list>xml/bps.xml</list>
		<list>xml/braingray.xml</list>
		<list>xml/broderbund.xml</list>
		<list>xml/bullfrog.xml</list>
		<!-- ================ C ================ -->
		<list>xml/c's_ware.xml</list>
		<list>xml/c-class.xml</list>
		<list>xml/c-lab.xml</list>
		<list>xml/california_dreams.xml</list>
		<list>xml/capcom.xml</list>
		<list>xml/carrylab.xml</list>
		<list>xml/catspro.xml</list>
		<list>xml/cbc.xml</list>
		<list>xml/celebrity_software.xml</list>
		<list>xml/chaos.xml</list>
		<list>xml/chatnoir.xml</list>
		<list>xml/chime.xml</list>
		<list>xml/chunsoft.xml</list>
		<list>xml/cocktailsoft.xml</list>
		<list>xml/codemasters.xml</list>
		<list>xml/colgate.xml</list>
		<list>xml/colossus.xml</list>
		<list>xml/compac.xml</list>
		<list>xml/compile.xml</list>
		<list>xml/copysoft.xml</list>
		<list>xml/core_design.xml</list>
		<list>xml/cosmos_computer.xml</list>
		<list>xml/crossmedia.xml</list>
		<list>xml/crowd.xml</list>
		<list>xml/cuisse.xml</list>
		<list>xml/culotte.xml</list>
		<list>xml/custom.xml</list>
		<list>xml/cybelle.xml</list>
		<list>xml/cygnus_studios.xml</list>
		<!-- ================ D ================ -->
		<list>xml/dataeast.xml</list>
		<list>xml/datawest.xml</list>
		<list>xml/davidson_and_associates.xml</list>
		<list>xml/dbsoft.xml</list>
		<list>xml/delphine.xml</list>
		<list>xml/dempa.xml</list>
		<list>xml/dengekisoft.xml</list>
		<list>xml/dentons.xml</list>
		<list>xml/desire.xml</list>
		<list>xml/dez.xml</list>
		<list>xml/did.xml</list>
		<list>xml/digital_integration.xml</list>
		<list>xml/dinamic.xml</list>
		<list>xml/discovery.xml</list>
		<list>xml/disney.xml</list>
		<list>xml/dixie.xml</list>
		<list>xml/dma_design.xml</list>
		<list>xml/do.xml</list>
		<list>xml/doa.xml</list>
		<list>xml/domark.xml</list>
		<list>xml/dot_plan.xml</list>
		<list>xml/doujin.xml</list>
		<list>xml/dreamers_guild.xml</list>
		<list>xml/dreamforge.xml</list>
		<list>xml/dynamicproduction.xml</list>
		<!-- ================ E ================ -->
		<list>xml/eastcube.xml</list>
		<list>xml/eclipse.xml</list>
		<list>xml/eldritch.xml</list>
		<list>xml/electricsheep.xml</list>
		<list>xml/electronic_arts.xml</list>
		<list>xml/elf.xml</list>
		<list>xml/elite.xml</list>
		<list>xml/empire.xml</list>
		<list>xml/enix.xml</list>
		<list>xml/epic_megagames.xml</list>
		<list>xml/epic_sony.xml</list>
		<list>xml/epyx.xml</list>
		<list>xml/etc.xml</list>
		<list>xml/exact.xml</list>
		<list>xml/exst.xml</list>
		<!-- ================ F ================ -->
		<list>xml/f2system.xml</list>
		<list>xml/fairydust.xml</list>
		<list>xml/fairytale-hardcover.xml</list>
		<list>xml/fairytale-xshitei.xml</list>
		<list>xml/fairytale.xml</list>
		<list>xml/falcom.xml</list>
		<list>xml/family_soft.xml</list>
		<list>xml/firstlight.xml</list>
		<list>xml/flair.xml</list>
		<list>xml/flat.xml</list>
		<list>xml/flipflop.xml</list>
		<list>xml/fmc.xml</list>
		<list>xml/foresight.xml</list>
		<list>xml/forest.xml</list>
		<list>xml/foster.xml</list>
		<list>xml/fournine.xml</list>
		<list>xml/frontier.xml</list>
		<list>xml/fugasystem.xml</list>
		<!-- ================ G ================ -->
		<list>xml/gainax.xml</list>
		<list>xml/gam.xml</list>
		<list>xml/gamearts.xml</list>
		<list>xml/gamestar.xml</list>
		<list>xml/gametechnopolis.xml</list>
		<list>xml/gametek.xml</list>
		<list>xml/garuda.xml</list>
		<list>xml/giga.xml</list>
		<list>xml/gimmick_house.xml</list>
		<list>xml/glams.xml</list>
		<list>xml/glodia.xml</list>
		<list>xml/gloria.xml</list>
		<list>xml/goliath.xml</list>
		<list>xml/graftgold.xml</list>
		<list>xml/gray.xml</list>
		<list>xml/great.xml</list>
		<list>xml/gremlin.xml</list>
		<list>xml/grocer.xml</list>
		<list>xml/gust.xml</list>
		<!-- ================ H ================ -->
		<list>xml/hal_laboratory.xml</list>
		<list>xml/happy_time.xml</list>
		<list>xml/hard.xml</list>
		<list>xml/heartsoft.xml</list>
		<list>xml/hertz.xml</list>
		<list>xml/hervest.xml</list>
		<list>xml/himeyasoft.xml</list>
		<list>xml/hobby_japan.xml</list>
		<list>xml/hokusho.xml</list>
		<list>xml/holywood.xml</list>
		<list>xml/homedata.xml</list>
		<list>xml/hot-b.xml</list>
		<list>xml/hudsonsoft.xml</list>
		<list>xml/hulinks.xml</list>
		<list>xml/human.xml</list>
		<list>xml/hummingbirdsoft.xml</list>
		<!-- ================ I ================ -->
		<list>xml/ice.xml</list>
		<list>xml/idea_software.xml</list>
		<list>xml/ides.xml</list>
		<list>xml/illusion.xml</list>
		<list>xml/illusioncore.xml</list>
		<list>xml/illusionpro.xml</list>
		<list>xml/image_works.xml</list>
		<list>xml/imagineer.xml</list>
		<list>xml/imagitec.xml</list>
		<list>xml/impressions.xml</list>
		<list>xml/infocom.xml</list>
		<list>xml/infogrames.xml</list>
		<list>xml/inos.xml</list>
		<list>xml/inside.xml</list>
		<list>xml/interheart.xml</list>
		<list>xml/interplay.xml</list>
		<list>xml/irem.xml</list>
		<list>xml/isc.xml</list>
		<!-- ================ J ================ -->
		<list>xml/jaleco.xml</list>
		<list>xml/jam.xml</list>
		<list>xml/janis.xml</list>
		<list>xml/japan_clary_business.xml</list>
		<list>xml/japan_home_video.xml</list>
		<list>xml/jast.xml</list>
		<list>xml/jitenshasogyo.xml</list>
		<list>xml/juice.xml</list>
		<!-- ================ K ================ -->
		<list>xml/kaneko.xml</list>
		<list>xml/kao.xml</list>
		<list>xml/katty.xml</list>
		<list>xml/kid.xml</list>
		<list>xml/kinetica.xml</list>
		<list>xml/kingsoft.xml</list>
		<list>xml/kinpukurin.xml</list>
		<list>xml/knorr.xml</list>
		<list>xml/koei.xml</list>
		<list>xml/kogado.xml</list>
		<list>xml/konami.xml</list>
		<list>xml/krisalis.xml</list>
		<list>xml/ksk.xml</list>
		<list>xml/kss.xml</list>
		<list>xml/kuni-soft.xml</list>
		<!-- ================ L ================ -->
		<list>xml/lankhor.xml</list>
		<list>xml/leaf.xml</list>
		<list>xml/legend.xml</list>
		<list>xml/libido.xml</list>
		<list>xml/linel.xml</list>
		<list>xml/lip_star.xml</list>
		<list>xml/ljn.xml</list>
		<list>xml/log.xml</list>
		<list>xml/loriciel.xml</list>
		<list>xml/lovegun.xml</list>
		<list>xml/lucasarts.xml</list>
		<list>xml/lunar_soft.xml</list>
		<!-- ================ M ================ -->
		<list>xml/maesta7.xml</list>
		<list>xml/magicalzoo.xml</list>
		<list>xml/magical_company.xml</list>
		<list>xml/magnetic_scrolls.xml</list>
		<list>xml/matrix.xml</list>
		<list>xml/maxima.xml</list>
		<list>xml/max_design.xml</list>
		<list>xml/maybesoft.xml</list>
		<list>xml/mayfarsoft.xml</list>
		<list>xml/mbstruth.xml</list>
		<list>xml/mebio_software.xml</list>
		<list>xml/megami.xml</list>
		<list>xml/melody.xml</list>
		<list>xml/merit_studios.xml</list>
		<list>xml/miami_soft.xml</list>
		<list>xml/microcabin.xml</list>
		<list>xml/microids.xml</list>
		<list>xml/microleague.xml</list>
		<list>xml/micronet.xml</list>
		<list>xml/microplay.xml</list>
		<list>xml/microprose.xml</list>
		<list>xml/microsoft.xml</list>
		<list>xml/midway.xml</list>
		<list>xml/millenium.xml</list>
		<list>xml/mindcraft.xml</list>
		<list>xml/mindscape.xml</list>
		<list>xml/mink.xml</list>
		<list>xml/mischief.xml</list>
		<list>xml/misty.xml</list>
		<list>xml/mix.xml</list>
		<list>xml/mnm.xml</list>
		<list>xml/momonokihouse.xml</list>
		<list>xml/monolith.xml</list>
		<list>xml/movic.xml</list>
		<list>xml/muap.xml</list>
		<list>xml/mucom88.xml</list>
		<list>xml/mugen.xml</list>
		<list>xml/muppetbox.xml</list>
		<list>xml/mvp_software.xml</list>
		<!-- ================ N ================ -->
		<list>xml/namco.xml</list>
		<list>xml/natsume.xml</list>
		<list>xml/ncs.xml</list>
		<list>xml/nec.xml</list>
		<list>xml/nec_avenue.xml</list>
		<list>xml/nec_interchannel.xml</list>
		<list>xml/negative.xml</list>
		<list>xml/neo_software.xml</list>
		<list>xml/new.xml</list>
		<list>xml/new_world_computing.xml</list>
		<list>xml/nexton.xml</list>
		<list>xml/nexus.xml</list>
		<list>xml/nic.xml</list>
		<list>xml/nichibutsu.xml</list>
		<list>xml/nichicomren.xml</list>
		<list>xml/nidecomcarry.xml</list>
		<list>xml/nihoncreate.xml</list>
		<list>xml/nihondexter.xml</list>
		<list>xml/nihonplantech.xml</list>
		<list>xml/nikukyuu.xml</list>
		<list>xml/nintendo.xml</list>
		<list>xml/nmk.xml</list>
		<!-- ================ O ================ -->
		<list>xml/ocean.xml</list>
		<list>xml/onionsoftware.xml</list>
		<list>xml/orange_house.xml</list>
		<list>xml/origin.xml</list>
		<list>xml/outlaw.xml</list>
		<list>xml/outou.xml</list>
		<list>xml/oxford.xml</list>
		<!-- ================ P ================ -->
		<list>xml/pack-in-video.xml</list>
		<list>xml/palmtree_soft.xml</list>
		<list>xml/panasoft.xml</list>
		<list>xml/panther.xml</list>
		<list>xml/paragon.xml</list>
		<list>xml/parsley.xml</list>
		<list>xml/paxsoftnica.xml</list>
		<list>xml/pcmcomplete.xml</list>
		<list>xml/peachsoft.xml</list>
		<list>xml/pearlsoft.xml</list>
		<list>xml/pegasussoft.xml</list>
		<list>xml/pegasus_japan.xml</list>
		<list>xml/pendulo_studios.xml</list>
		<list>xml/peppermint_kids.xml</list>
		<list>xml/persian_soft.xml</list>
		<list>xml/petit.xml</list>
		<list>xml/pil.xml</list>
		<list>xml/piston_soft.xml</list>
		<list>xml/plum.xml</list>
		<list>xml/poisonbreath.xml</list>
		<list>xml/ponyca.xml</list>
		<list>xml/ponytail.xml</list>
		<list>xml/pow.xml</list>
		<list>xml/prestige.xml</list>
		<list>xml/probe.xml</list>
		<list>xml/psd.xml</list>
		<list>xml/psikyo.xml</list>
		<list>xml/psygnosis.xml</list>
		<list>xml/puchi.xml</list>
		<!-- ================ Q ================ -->
		<list>xml/quasarsoft.xml</list>
		<list>xml/queen_soft.xml</list>
		<!-- ================ R ================ -->
		<list>xml/r-rate.xml</list>
		<list>xml/r.xml</list>
		<list>xml/rage.xml</list>
		<list>xml/rainbird.xml</list>
		<list>xml/raizing.xml</list>
		<list>xml/randomhouse.xml</list>
		<list>xml/redzone.xml</list>
		<list>xml/red_rat.xml</list>
		<list>xml/reline.xml</list>
		<list>xml/revolution.xml</list>
		<list>xml/rforce.xml</list>
		<list>xml/rightstuff.xml</list>
		<list>xml/rihuri.xml</list>
		<list>xml/ringer_bell.xml</list>
		<list>xml/riruhisparty.xml</list>
		<list>xml/risc.xml</list>
		<list>xml/riverhillsoft.xml</list>
		<!-- ================ S ================ -->
		<list>xml/safari.xml</list>
		<list>xml/santa_fe.xml</list>
		<list>xml/scaptrust.xml</list>
		<list>xml/scoop.xml</list>
		<list>xml/sea_lion.xml</list>
		<list>xml/sega.xml</list>
		<list>xml/seibu.xml</list>
		<list>xml/sein.xml</list>
		<list>xml/sharp.xml</list>
		<list>xml/shinseisha.xml</list>
		<list>xml/sierra.xml</list>
		<list>xml/silence.xml</list>
		<list>xml/silicon_knights.xml</list>
		<list>xml/silkys.xml</list>
		<list>xml/simis.xml</list>
		<list>xml/simulmondo.xml</list>
		<list>xml/sir_tech.xml</list>
		<list>xml/snk.xml</list>
		<list>xml/softbank.xml</list>
		<list>xml/softec.xml</list>
		<list>xml/softpal.xml</list>
		<list>xml/softstar.xml</list>
		<list>xml/software_2000.xml</list>
		<list>xml/soft_plan.xml</list>
		<list>xml/soft_world.xml</list>
		<list>xml/sogna.xml</list>
		<list>xml/sony.xml</list>
		<list>xml/sorciere.xml</list>
		<list>xml/space_project.xml</list>
		<list>xml/spectrum_holobyte.xml</list>
		<list>xml/sps.xml</list>
		<list>xml/square.xml</list>
		<list>xml/ssg.xml</list>
		<list>xml/ssi.xml</list>
		<list>xml/starbyte.xml</list>
		<list>xml/starcraft.xml</list>
		<list>xml/sting.xml</list>
		<list>xml/storm.xml</list>
		<list>xml/striker.xml</list>
		<list>xml/studio_angel.xml</list>
		<list>xml/studio_b-room.xml</list>
		<list>xml/studio_genmaitya.xml</list>
		<list>xml/studio_milk.xml</list>
		<list>xml/studio_mobius.xml</list>
		<list>xml/studio_twinkle.xml</list>
		<list>xml/succubus.xml</list>
		<list>xml/sunflowers.xml</list>
		<list>xml/sunsoft.xml</list>
		<list>xml/sur_de_wave.xml</list>
		<list>xml/swat.xml</list>
		<list>xml/systemsoft.xml</list>
		<list>xml/system_sacom.xml</list>
		<!-- ================ T ================ -->
		<list>xml/t2.xml</list>
		<list>xml/tad.xml</list>
		<list>xml/taito.xml</list>
		<list>xml/takeru.xml</list>
		<list>xml/takicorporation.xml</list>
		<list>xml/tale_software.xml</list>
		<list>xml/tande.xml</list>
		<list>xml/tatsumi.xml</list>
		<list>xml/team_17.xml</list>
		<list>xml/tear_drop.xml</list>
		<list>xml/technogrard.xml</list>
		<list>xml/technopolissoft.xml</list>
		<list>xml/technos.xml</list>
		<list>xml/tecmo.xml</list>
		<list>xml/tecnosoft.xml</list>
		<list>xml/telenet.xml</list>
		<list>xml/tengupro.xml</list>
		<list>xml/tenshindo.xml</list>
		<list>xml/teque.xml</list>
		<list>xml/tetratech.xml</list>
		<list>xml/tgl.xml</list>
		<list>xml/thalion.xml</list>
		<list>xml/thinkingrabbit.xml</list>
		<list>xml/tiara.xml</list>
		<list>xml/tierheit.xml</list>
		<list>xml/tips.xml</list>
		<list>xml/toaplan.xml</list>
		<list>xml/toho.xml</list>
		<list>xml/tokumashoten.xml</list>
		<list>xml/tokyo_shoseki.xml</list>
		<list>xml/tomboy.xml</list>
		<list>xml/tonkinhouse.xml</list>
		<list>xml/topo_soft.xml</list>
		<list>xml/trush.xml</list>
		<list>xml/t_time.xml</list>
		<!-- ================ U ================ -->
		<list>xml/u-mesoft.xml</list>
		<list>xml/u-office.xml</list>
		<list>xml/ubisoft.xml</list>
		<list>xml/ucom.xml</list>
		<list>xml/umizuki_productions.xml</list>
		<list>xml/universal.xml</list>
		<list>xml/unknown.xml</list>
		<list>xml/upl.xml</list>
		<list>xml/us_gold.xml</list>
		<list>xml/u_office.xml</list>
		<!-- ================ V ================ -->
		<list>xml/victor.xml</list>
		<list>xml/video_system.xml</list>
		<list>xml/ving.xml</list>
		<list>xml/visco.xml</list>
		<list>xml/vivian.xml</list>
		<list>xml/vivid_image.xml</list>
		<!-- ================ W ================ -->
		<list>xml/warlock.xml</list>
		<list>xml/wavetrain.xml</list>
		<list>xml/wendymagazine.xml</list>
		<list>xml/westwood.xml</list>
		<list>xml/wildlife.xml</list>
		<list>xml/wing.xml</list>
		<list>xml/winkysoft.xml</list>
		<list>xml/wishbone.xml</list>
		<list>xml/wiz.xml</list>
		<list>xml/wolfteam.xml</list>
		<!-- ================ X ================ -->
		<list>xml/xtalsoft.xml</list>
		<list>xml/xyz.xml</list>
		<!-- ================ Y ================ -->
		<list>xml/youentai.xml</list>
		<list>xml/yunsung.xml</list>
		<!-- ================ Z ================ -->
		<list>xml/zeit.xml</list>
		<list>xml/zoom.xml</list>
		<list>xml/zyx.xml</list>
	</childlists>
<!-- ================ END ================ -->
</gamelist>
