<?xml version="1.0" encoding="Shift_JIS"?>
<?xml-stylesheet type="text/xsl" href="hoot.xsl"?>
<!DOCTYPE gamelist [
	<!ELEMENT gamelist (game|bind|childlists)*>
	<!ATTLIST gamelist date CDATA #IMPLIED>
	<!ELEMENT childlists (list)*>
	<!ELEMENT list (#PCDATA)>
	<!ELEMENT bind (exts,driver,options?)>
	<!ELEMENT exts (ext)*>
	<!ELEMENT ext (#PCDATA)>
	<!ELEMENT game (name,driver,driveralias?,options?,romlist?,titlelist?)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT driver (#PCDATA)>
	<!ATTLIST driver type CDATA #IMPLIED>
	<!ELEMENT driveralias (#PCDATA)>
	<!ATTLIST driveralias type CDATA #IMPLIED>
	<!ELEMENT options (option)*>
	<!ELEMENT option EMPTY>
	<!ATTLIST option name CDATA #REQUIRED
					 value CDATA #REQUIRED>
	<!ELEMENT romlist (rom)*>
	<!ATTLIST romlist archive CDATA #IMPLIED>
	<!ELEMENT rom (#PCDATA)>
	<!ATTLIST rom type CDATA #REQUIRED
				  offset CDATA #IMPLIED
				  crc32 CDATA #IMPLIED>
	<!ELEMENT titlelist (title|range)*>
	<!ELEMENT title (#PCDATA)>
	<!ATTLIST title code CDATA #REQUIRED
					type CDATA #IMPLIED>
	<!ELEMENT range (#PCDATA)>
	<!ATTLIST range min CDATA #REQUIRED
					max CDATA #REQUIRED
					extcode CDATA #IMPLIED>
]>
<gamelist date="2005/09/25">
	<!-- //ZyX -->
	<game>
		<name>[PC-9801] TRIGGER</name>
		<driver type="opn">pc98dos</driver>
		<driveralias type="NEC PC-9801">ZyX</driveralias>
		<options>
			<option name="clockmul" value="8"/>
		</options>
		<romlist archive="trigger1_98">
			<rom type="file" offset="-1">DOFMDC98.COM</rom>
			<rom type="file" offset="5">IDA.COM</rom>
			<rom type="file" offset="0x10">TRG01</rom>
			<rom type="file" offset="0x11">TRG02</rom>
			<rom type="file" offset="0x12">TRG03</rom>
			<rom type="file" offset="0x13">TRG04</rom>
			<rom type="file" offset="0x14">TRG05</rom>
			<rom type="file" offset="0x15">TRG06</rom>
			<rom type="file" offset="0x16">TRG07</rom>
			<rom type="file" offset="0x17">TRG08</rom>
			<rom type="file" offset="0x18">TRG09</rom>
			<rom type="file" offset="0x19">TRG10</rom>
			<rom type="file" offset="0x1a">TRG11</rom>
			<rom type="file" offset="0x1b">TRG12</rom>
			<rom type="file" offset="0x1c">TRG13</rom>
			<rom type="file" offset="0x1d">TRG16</rom>
			<rom type="file" offset="0x1e">TRG17</rom>
			<rom type="file" offset="0x1f">TRG17B</rom>
			<rom type="file" offset="0x20">TRG18</rom>
			<rom type="file" offset="0x21">TRG19</rom>
			<rom type="file" offset="0x22">TRG20</rom>
			<rom type="file" offset="0x23">TRG21</rom>
			<rom type="file" offset="0x24">TRG22</rom>
			<rom type="file" offset="0x25">TRG23</rom>
			<rom type="shell" offset="0">DOFMDC98</rom>
		</romlist>
		<titlelist>
			<title code="0x10">TRG01</title>
			<title code="0x11">TRG02</title>
			<title code="0x12">TRG03</title>
			<title code="0x13">TRG04</title>
			<title code="0x14">TRG05</title>
			<title code="0x15">TRG06</title>
			<title code="0x16">TRG07</title>
			<title code="0x17">TRG08</title>
			<title code="0x18">TRG09</title>
			<title code="0x19">TRG10</title>
			<title code="0x1a">TRG11</title>
			<title code="0x1b">TRG12</title>
			<title code="0x1c">TRG13</title>
			<title code="0x1d">TRG16</title>
			<title code="0x1e">TRG17</title>
			<title code="0x1f">TRG17B</title>
			<title code="0x20">TRG18</title>
			<title code="0x21">TRG19</title>
			<title code="0x22">TRG20</title>
			<title code="0x23">TRG21</title>
			<title code="0x24">TRG22</title>
			<title code="0x25">TRG23</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] TRIGGER2(OPN)</name>
		<driver type="opn">pc98dos</driver>
		<driveralias type="NEC PC-9801">ZyX</driveralias>
		<options>
			<option name="clockmul" value="8"/>
		</options>
		<romlist archive="trigger2_98">
			<rom type="file" offset="-1">DOFMDC98.COM</rom>
			<rom type="file" offset="5">IDA2.COM</rom>
			<rom type="file" offset="0x10">TRG01FM</rom>
			<rom type="file" offset="0x11">TRG02FM</rom>
			<rom type="file" offset="0x12">TRG03FM</rom>
			<rom type="file" offset="0x13">TRG04FM</rom>
			<rom type="file" offset="0x14">TRG05FM</rom>
			<rom type="file" offset="0x15">TRG06FM</rom>
			<rom type="file" offset="0x16">TRG07FM</rom>
			<rom type="file" offset="0x17">TRG09FM</rom>
			<rom type="file" offset="0x18">TRG10FM</rom>
			<rom type="file" offset="0x19">TRG11FM</rom>
			<rom type="file" offset="0x1a">TRG12FM</rom>
			<rom type="file" offset="0x1b">TRG13FM</rom>
			<rom type="file" offset="0x1c">TRG14FM</rom>
			<rom type="file" offset="0x1d">TRG15FM</rom>
			<rom type="file" offset="0x1e">TRG16FM</rom>
			<rom type="file" offset="0x1f">TRG17FM</rom>
			<rom type="file" offset="0x20">TRG21FM</rom>
			<rom type="file" offset="0x21">TRG22FM</rom>
			<rom type="file" offset="0x22">TRG23FM</rom>
			<rom type="file" offset="0x23">TRG24FM</rom>
			<rom type="file" offset="0x24">TRG25FM</rom>
			<rom type="shell" offset="0">DOFMDC98</rom>
		</romlist>
		<titlelist>
			<title code="0x10">TRG01FM</title>
			<title code="0x11">TRG02FM</title>
			<title code="0x12">TRG03FM</title>
			<title code="0x13">TRG04FM</title>
			<title code="0x14">TRG05FM</title>
			<title code="0x15">TRG06FM</title>
			<title code="0x16">TRG07FM</title>
			<title code="0x17">TRG09FM</title>
			<title code="0x18">TRG10FM</title>
			<title code="0x19">TRG11FM</title>
			<title code="0x1a">TRG12FM</title>
			<title code="0x1b">TRG13FM</title>
			<title code="0x1c">TRG14FM</title>
			<title code="0x1d">TRG15FM</title>
			<title code="0x1e">TRG16FM</title>
			<title code="0x1f">TRG17FM</title>
			<title code="0x20">TRG21FM</title>
			<title code="0x21">TRG22FM</title>
			<title code="0x22">TRG23FM</title>
			<title code="0x23">TRG24FM</title>
			<title code="0x24">TRG25FM</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] TWILIGHT HOTEL 〜トワイライトホテル〜(OPN)</name>
		<driver type="opn">pc98dos</driver>
		<driveralias type="NEC PC-9801">ZyX</driveralias>
		<options>
			<option name="clockmul" value="8"/>
		</options>
		<romlist archive="thotel_98">
			<rom type="file" offset="-1">DOFMDX98.COM</rom>
			<rom type="file" offset="-1">ZVA.EXE</rom>
			<rom type="conin" offset="5">ZVA.EXE</rom>
			<rom type="file" offset="0x10">TH01F.MSC</rom>
			<rom type="file" offset="0x11">TH02F.MSC</rom>
			<rom type="file" offset="0x12">TH03F.MSC</rom>
			<rom type="file" offset="0x13">TH04F.MSC</rom>
			<rom type="file" offset="0x14">TH05F.MSC</rom>
			<rom type="file" offset="0x15">TH06F.MSC</rom>
			<rom type="file" offset="0x16">TH07F.MSC</rom>
			<rom type="file" offset="0x17">TH08F.MSC</rom>
			<rom type="file" offset="0x18">TH09F.MSC</rom>
			<rom type="file" offset="0x19">TH10F.MSC</rom>
			<rom type="file" offset="0x1a">TH11F.MSC</rom>
			<rom type="file" offset="0x1b">TH12F.MSC</rom>
			<rom type="file" offset="0x1c">TH13F.MSC</rom>
			<rom type="file" offset="0x1d">TH14F.MSC</rom>
			<rom type="file" offset="0x1e">TH15F.MSC</rom>
			<rom type="file" offset="0x1f">TH16F.MSC</rom>
			<rom type="file" offset="0x20">TH17F.MSC</rom>
			<rom type="file" offset="0x21">TH18F.MSC</rom>
			<rom type="file" offset="0x22">TH19F.MSC</rom>
			<rom type="file" offset="0x23">TH20F.MSC</rom>
			<rom type="file" offset="0x24">TH21F.MSC</rom>
			<rom type="file" offset="0x25">TH22F.MSC</rom>
			<rom type="file" offset="0x26">TH23F.MSC</rom>
			<rom type="file" offset="0x27">TH24F.MSC</rom>
			<rom type="file" offset="0x28">TH25F.MSC</rom>
			<rom type="file" offset="0x29">TH26F.MSC</rom>
			<rom type="file" offset="0x2a">TH27F.MSC</rom>
			<rom type="file" offset="0x2b">TH28F.MSC</rom>
			<rom type="file" offset="0x2c">TH29F.MSC</rom>
			<rom type="file" offset="0x2d">SE01.MSC</rom>
			<rom type="file" offset="0x2e">SE02.MSC</rom>
			<rom type="file" offset="0x2f">SE03.MSC</rom>
			<rom type="file" offset="0x30">SE04.MSC</rom>
			<rom type="file" offset="0x31">SE05.MSC</rom>
			<rom type="file" offset="0x32">SE06.MSC</rom>
			<rom type="file" offset="0x33">SE07.MSC</rom>
			<rom type="file" offset="0x34">SE08.MSC</rom>
			<rom type="file" offset="0x35">SE09.MSC</rom>
			<rom type="file" offset="0x36">SE10.MSC</rom>
			<rom type="file" offset="0x37">SE11.MSC</rom>
			<rom type="file" offset="0x38">SE12.MSC</rom>
			<rom type="file" offset="0x39">SE14.MSC</rom>
			<rom type="file" offset="0x3a">SE15.MSC</rom>
			<rom type="file" offset="0x3b">SE16.MSC</rom>
			<rom type="file" offset="0x3c">SE17.MSC</rom>
			<rom type="file" offset="0x3d">SE18.MSC</rom>
			<rom type="file" offset="0x3e">SE19.MSC</rom>
			<rom type="file" offset="0x3f">SE20.MSC</rom>
			<rom type="shell" offset="0">DOFMDX98</rom>
		</romlist>
		<titlelist>
			<title code="0x10">TH01F.MSC</title>
			<title code="0x11">TH02F.MSC</title>
			<title code="0x12">TH03F.MSC</title>
			<title code="0x13">TH04F.MSC</title>
			<title code="0x14">TH05F.MSC</title>
			<title code="0x15">TH06F.MSC</title>
			<title code="0x16">TH07F.MSC</title>
			<title code="0x17">TH08F.MSC</title>
			<title code="0x18">TH09F.MSC</title>
			<title code="0x19">TH10F.MSC</title>
			<title code="0x1a">TH11F.MSC</title>
			<title code="0x1b">TH12F.MSC</title>
			<title code="0x1c">TH13F.MSC</title>
			<title code="0x1d">TH14F.MSC</title>
			<title code="0x1e">TH15F.MSC</title>
			<title code="0x1f">TH16F.MSC</title>
			<title code="0x20">TH17F.MSC</title>
			<title code="0x21">TH18F.MSC</title>
			<title code="0x22">TH19F.MSC</title>
			<title code="0x23">TH20F.MSC</title>
			<title code="0x24">TH21F.MSC</title>
			<title code="0x25">TH22F.MSC</title>
			<title code="0x26">TH23F.MSC</title>
			<title code="0x27">TH24F.MSC</title>
			<title code="0x28">TH25F.MSC</title>
			<title code="0x29">TH26F.MSC</title>
			<title code="0x2a">TH27F.MSC</title>
			<title code="0x2b">TH28F.MSC</title>
			<title code="0x2c">TH29F.MSC</title>
			<title code="0x2d">SE01.MSC</title>
			<title code="0x2e">SE02.MSC</title>
			<title code="0x2f">SE03.MSC</title>
			<title code="0x30">SE04.MSC</title>
			<title code="0x31">SE05.MSC</title>
			<title code="0x32">SE06.MSC</title>
			<title code="0x33">SE07.MSC</title>
			<title code="0x34">SE08.MSC</title>
			<title code="0x35">SE09.MSC</title>
			<title code="0x36">SE10.MSC</title>
			<title code="0x37">SE11.MSC</title>
			<title code="0x38">SE12.MSC</title>
			<title code="0x39">SE14.MSC</title>
			<title code="0x3a">SE15.MSC</title>
			<title code="0x3b">SE16.MSC</title>
			<title code="0x3c">SE17.MSC</title>
			<title code="0x3d">SE18.MSC</title>
			<title code="0x3e">SE19.MSC</title>
			<title code="0x3f">SE20.MSC</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] Hercequary</name>
		<driver type="opn">pc98vx</driver>
		<driveralias type="NEC PC-9801">ZyX</driveralias>
		<options>
			<option name="bootcs" value="0x0060"/>
			<option name="bootip" value="0x0000"/>
			<option name="funcvect" value="0x7f"/>
			<option name="adressing" value="0"/>
			<option name="dataaddr" value="0x10000"/>
			<option name="filesize" value="0x6000"/>
			<option name="datamax" value="0xff"/>
			<option name="clockmul" value="8"/>
		</options>
		<romlist archive="herceq_98">
			<rom type="code" offset="0x600">DOFMD_98.BIN</rom>
			<rom type="code" offset="0xfa0">ZYXMD</rom>
			<rom type="bgm" offset="0x01">CONT.MSC</rom>
			<rom type="bgm" offset="0x02">END.MSC</rom>
			<rom type="bgm" offset="0x03">MD1.MSC</rom>
			<rom type="bgm" offset="0x04">MD2.MSC</rom>
			<rom type="bgm" offset="0x05">MD3.MSC</rom>
			<rom type="bgm" offset="0x06">MD4.MSC</rom>
			<rom type="bgm" offset="0x07">MD5.MSC</rom>
			<rom type="bgm" offset="0x08">MD6.MSC</rom>
			<rom type="bgm" offset="0x09">MD7.MSC</rom>
			<rom type="bgm" offset="0x0a">MD8.MSC</rom>
			<rom type="bgm" offset="0x0b">MENU.MSC</rom>
			<rom type="bgm" offset="0x0c">OP1.MSC</rom>
			<rom type="bgm" offset="0x0d">OP2.MSC</rom>
			<rom type="bgm" offset="0x0e">OVER.MSC</rom>
			<rom type="bgm" offset="0x0f">VIS.MSC</rom>
			<rom type="bgm" offset="0x10">VS.MSC</rom>
		</romlist>
		<titlelist>
			<title code="0x01">CONT.MSC</title>
			<title code="0x02">END.MSC</title> 
			<title code="0x03">MD1.MSC</title> 
			<title code="0x04">MD2.MSC</title> 
			<title code="0x05">MD3.MSC</title> 
			<title code="0x06">MD4.MSC</title> 
			<title code="0x07">MD5.MSC</title> 
			<title code="0x08">MD6.MSC</title> 
			<title code="0x09">MD7.MSC</title> 
			<title code="0x0a">MD8.MSC</title> 
			<title code="0x0b">MENU.MSC</title>
			<title code="0x0c">OP1.MSC</title> 
			<title code="0x0d">OP2.MSC</title> 
			<title code="0x0e">OVER.MSC</title>
			<title code="0x0f">VIS.MSC</title> 
			<title code="0x10">VS.MSC</title>  
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] リング・アウト!!(OPN)</name>
		<driver type="opn">pc98dos</driver>
		<driveralias type="NEC PC-9801">ZyX</driveralias>
		<options>
			<option name="clockmul" value="8"/>
		</options>
		<romlist archive="ringout_98">
			<rom type="file" offset="-1">DOFMDX98.COM</rom>
			<rom type="file" offset="-1">ZVA21F.EXE</rom>
			<rom type="conin" offset="5">ZVA21F.EXE</rom>
			<rom type="file" offset="0x10">RIN01F.MSC</rom>
			<rom type="file" offset="0x11">RIN02F.MSC</rom>
			<rom type="file" offset="0x12">RIN03F.MSC</rom>
			<rom type="file" offset="0x13">RIN04F.MSC</rom>
			<rom type="file" offset="0x14">RIN05F.MSC</rom>
			<rom type="file" offset="0x15">RIN06F.MSC</rom>
			<rom type="file" offset="0x16">RIN07F.MSC</rom>
			<rom type="file" offset="0x17">RIN08F.MSC</rom>
			<rom type="file" offset="0x18">RIN09F.MSC</rom>
			<rom type="file" offset="0x19">RIN10F.MSC</rom>
			<rom type="file" offset="0x1a">RIN11F.MSC</rom>
			<rom type="file" offset="0x1b">SE01.MSC</rom>
			<rom type="file" offset="0x1c">SE02.MSC</rom>
			<rom type="file" offset="0x1d">SE03.MSC</rom>
			<rom type="file" offset="0x1e">SE04.MSC</rom>
			<rom type="file" offset="0x1f">SE05.MSC</rom>
			<rom type="shell" offset="0">DOFMDX98</rom>
		</romlist>
		<titlelist>
			<title code="0x10">RIN01F.MSC</title>
			<title code="0x11">RIN02F.MSC</title>
			<title code="0x12">RIN03F.MSC</title>
			<title code="0x13">RIN04F.MSC</title>
			<title code="0x14">RIN05F.MSC</title>
			<title code="0x15">RIN06F.MSC</title>
			<title code="0x16">RIN07F.MSC</title>
			<title code="0x17">RIN08F.MSC</title>
			<title code="0x18">RIN09F.MSC</title>
			<title code="0x19">RIN10F.MSC</title>
			<title code="0x1a">RIN11F.MSC</title>
			<title code="0x1b">SE01.MSC</title>
			<title code="0x1c">SE02.MSC</title>
			<title code="0x1d">SE03.MSC</title>
			<title code="0x1e">SE04.MSC</title>
			<title code="0x1f">SE05.MSC</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] 学園爆裂転校生!(OPN)</name>
		<driver type="opn">pc98vx</driver>
		<driveralias type="NEC PC-9801">ZyX</driveralias>
		<options>
			<option name="bootcs" value="0x0060"/>
			<option name="bootip" value="0x0000"/>
			<option name="funcvect" value="0x7f"/>
			<option name="adressing" value="0"/>
			<option name="dataaddr" value="0x10000"/>
			<option name="filesize" value="0x6000"/>
			<option name="datamax" value="0xff"/>
			<option name="clockmul" value="8"/>
		</options>
		<romlist archive="gbakuten_98">
			<rom type="code" offset="0x600">DOFMD_98.BIN</rom>
			<rom type="code" offset="0xfa0">ZYXMD</rom>
			<rom type="bgm" offset="0x01">BT01F.MSC</rom>
			<rom type="bgm" offset="0x02">BT02F.MSC</rom>
			<rom type="bgm" offset="0x03">BT03F.MSC</rom>
			<rom type="bgm" offset="0x04">BT04F.MSC</rom>
			<rom type="bgm" offset="0x05">BT05F.MSC</rom>
			<rom type="bgm" offset="0x06">BT06F.MSC</rom>
			<rom type="bgm" offset="0x07">BT07F.MSC</rom>
			<rom type="bgm" offset="0x08">BT08F.MSC</rom>
			<rom type="bgm" offset="0x09">BT09F.MSC</rom>
			<rom type="bgm" offset="0x0a">BT10F.MSC</rom>
			<rom type="bgm" offset="0x0b">BT11F.MSC</rom>
			<rom type="bgm" offset="0x0c">BT12F.MSC</rom>
			<rom type="bgm" offset="0x0d">BT13F.MSC</rom>
			<rom type="bgm" offset="0x0e">BT14F.MSC</rom>
			<rom type="bgm" offset="0x0f">BT15F.MSC</rom>
			<rom type="bgm" offset="0x10">SE01.MSC</rom>
			<rom type="bgm" offset="0x11">SE02.MSC</rom>
			<rom type="bgm" offset="0x12">SE03.MSC</rom>
			<rom type="bgm" offset="0x13">SE04.MSC</rom>
			<rom type="bgm" offset="0x14">SE05.MSC</rom>
			<rom type="bgm" offset="0x15">SE06.MSC</rom>
			<rom type="bgm" offset="0x16">SE07.MSC</rom>
			<rom type="bgm" offset="0x17">SE08.MSC</rom>
			<rom type="bgm" offset="0x18">SE09.MSC</rom>
			<rom type="bgm" offset="0x19">SE10.MSC</rom>
			<rom type="bgm" offset="0x1a">SE11.MSC</rom>
			<rom type="bgm" offset="0x1b">SE12.MSC</rom>
		</romlist>
		<titlelist>
			<title code="0x01">BT01F.MSC</title>
			<title code="0x02">BT02F.MSC</title>
			<title code="0x03">BT03F.MSC</title>
			<title code="0x04">BT04F.MSC</title>
			<title code="0x05">BT05F.MSC</title>
			<title code="0x06">BT06F.MSC</title>
			<title code="0x07">BT07F.MSC</title>
			<title code="0x08">BT08F.MSC</title>
			<title code="0x09">BT09F.MSC</title>
			<title code="0x0a">BT10F.MSC</title>
			<title code="0x0b">BT11F.MSC</title>
			<title code="0x0c">BT12F.MSC</title>
			<title code="0x0d">BT13F.MSC</title>
			<title code="0x0e">BT14F.MSC</title>
			<title code="0x0f">BT15F.MSC</title>
			<title code="0x10">SE01.MSC</title>
			<title code="0x11">SE02.MSC</title>
			<title code="0x12">SE03.MSC</title>
			<title code="0x13">SE04.MSC</title>
			<title code="0x14">SE05.MSC</title>
			<title code="0x15">SE06.MSC</title>
			<title code="0x16">SE07.MSC</title>
			<title code="0x17">SE08.MSC</title>
			<title code="0x18">SE09.MSC</title>
			<title code="0x19">SE10.MSC</title>
			<title code="0x1a">SE11.MSC</title>
			<title code="0x1b">SE12.MSC</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] 高見沢恭介 熱血!! 教育研修(OPN)</name>
		<driver type="opn">pc98vx</driver>
		<driveralias type="NEC PC-9801">ZyX</driveralias>
		<options>
			<option name="bootcs" value="0x0060"/>
			<option name="bootip" value="0x0000"/>
			<option name="funcvect" value="0x7f"/>
			<option name="adressing" value="0"/>
			<option name="dataaddr" value="0x10000"/>
			<option name="filesize" value="0x6000"/>
			<option name="datamax" value="0xff"/>
			<option name="clockmul" value="8"/>
		</options>
		<romlist archive="kyouiku_98">
			<rom type="code" offset="0x600">DOFMD_98.BIN</rom>
			<rom type="code" offset="0xfa0">ZYXMD</rom>
			<rom type="bgm" offset="0x01">TK01F.MSC</rom>
			<rom type="bgm" offset="0x02">TK02F.MSC</rom>
			<rom type="bgm" offset="0x03">TK03F.MSC</rom>
			<rom type="bgm" offset="0x04">TK04F.MSC</rom>
			<rom type="bgm" offset="0x05">TK05F.MSC</rom>
			<rom type="bgm" offset="0x06">TK06F.MSC</rom>
			<rom type="bgm" offset="0x07">TK07F.MSC</rom>
			<rom type="bgm" offset="0x08">TK08F.MSC</rom>
			<rom type="bgm" offset="0x09">TK09F.MSC</rom>
			<rom type="bgm" offset="0x0a">TK10F.MSC</rom>
			<rom type="bgm" offset="0x0b">TK11F.MSC</rom>
			<rom type="bgm" offset="0x0c">TK12F.MSC</rom>
			<rom type="bgm" offset="0x0d">TK13F.MSC</rom>
			<rom type="bgm" offset="0x0e">TK14F.MSC</rom>
			<rom type="bgm" offset="0x0f">TK15F.MSC</rom>
			<rom type="bgm" offset="0x10">TK16F.MSC</rom>
			<rom type="bgm" offset="0x11">TK17F.MSC</rom>
			<rom type="bgm" offset="0x12">TK18F.MSC</rom>
			<rom type="bgm" offset="0x13">TK19F.MSC</rom>
			<rom type="bgm" offset="0x14">TK20F.MSC</rom>
			<rom type="bgm" offset="0x15">TK21F.MSC</rom>
			<rom type="bgm" offset="0x16">TK22F.MSC</rom>
			<rom type="bgm" offset="0x17">TK23F.MSC</rom>
			<rom type="bgm" offset="0x18">TK24F.MSC</rom>
			<rom type="bgm" offset="0x19">SE01F.MSC</rom>
			<rom type="bgm" offset="0x1a">SE02.MSC</rom>
			<rom type="bgm" offset="0x1b">SE03.MSC</rom>
			<rom type="bgm" offset="0x1c">SE04.MSC</rom>
			<rom type="bgm" offset="0x1d">SE05.MSC</rom>
			<rom type="bgm" offset="0x1e">SE06.MSC</rom>
			<rom type="bgm" offset="0x1f">SE07.MSC</rom>
			<rom type="bgm" offset="0x20">SE08.MSC</rom>
			<rom type="bgm" offset="0x21">SE09.MSC</rom>
			<rom type="bgm" offset="0x22">SE10.MSC</rom>
			<rom type="bgm" offset="0x23">SE11.MSC</rom>
			<rom type="bgm" offset="0x24">SE12.MSC</rom>
			<rom type="bgm" offset="0x25">SE14.MSC</rom>
			<rom type="bgm" offset="0x26">SE15.MSC</rom>
			<rom type="bgm" offset="0x27">SE16.MSC</rom>
		</romlist>
		<titlelist>
			<title code="0x01">TK01F.MSC</title>
			<title code="0x02">TK02F.MSC</title>
			<title code="0x03">TK03F.MSC</title>
			<title code="0x04">TK04F.MSC</title>
			<title code="0x05">TK05F.MSC</title>
			<title code="0x06">TK06F.MSC</title>
			<title code="0x07">TK07F.MSC</title>
			<title code="0x08">TK08F.MSC</title>
			<title code="0x09">TK09F.MSC</title>
			<title code="0x0a">TK10F.MSC</title>
			<title code="0x0b">TK11F.MSC</title>
			<title code="0x0c">TK12F.MSC</title>
			<title code="0x0d">TK13F.MSC</title>
			<title code="0x0e">TK14F.MSC</title>
			<title code="0x0f">TK15F.MSC</title>
			<title code="0x10">TK16F.MSC</title>
			<title code="0x11">TK17F.MSC</title>
			<title code="0x12">TK18F.MSC</title>
			<title code="0x13">TK19F.MSC</title>
			<title code="0x14">TK20F.MSC</title>
			<title code="0x15">TK21F.MSC</title>
			<title code="0x16">TK22F.MSC</title>
			<title code="0x17">TK23F.MSC</title>
			<title code="0x18">TK24F.MSC</title>
			<title code="0x19">SE01F.MSC</title>
			<title code="0x1a">SE02.MSC</title>
			<title code="0x1b">SE03.MSC</title>
			<title code="0x1c">SE04.MSC</title>
			<title code="0x1d">SE05.MSC</title>
			<title code="0x1e">SE06.MSC</title>
			<title code="0x1f">SE07.MSC</title>
			<title code="0x20">SE08.MSC</title>
			<title code="0x21">SE09.MSC</title>
			<title code="0x22">SE10.MSC</title>
			<title code="0x23">SE11.MSC</title>
			<title code="0x24">SE12.MSC</title>
			<title code="0x25">SE14.MSC</title>
			<title code="0x26">SE15.MSC</title>
			<title code="0x27">SE16.MSC</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] 雷の戦士ライディ(OPN)</name>
		<driver type="opn">pc98vx</driver>
		<driveralias type="NEC PC-9801">ZyX</driveralias>
		<options>
			<option name="bootcs" value="0x0060"/>
			<option name="bootip" value="0x0000"/>
			<option name="funcvect" value="0x7f"/>
			<option name="adressing" value="0"/>
			<option name="dataaddr" value="0x10000"/>
			<option name="filesize" value="0x6000"/>
			<option name="datamax" value="0xff"/>
			<option name="clockmul" value="8"/>
		</options>
		<romlist archive="laidi1_98">
			<rom type="code" offset="0x600">DOFMD_98.BIN</rom>
			<rom type="code" offset="0xfa0">ZYXMD</rom>
			<rom type="bgm" offset="0x01">RD01F.MSC</rom>
			<rom type="bgm" offset="0x02">RD02F.MSC</rom>
			<rom type="bgm" offset="0x03">RD03F.MSC</rom>
			<rom type="bgm" offset="0x04">RD04F.MSC</rom>
			<rom type="bgm" offset="0x05">RD05F.MSC</rom>
			<rom type="bgm" offset="0x06">RD06F.MSC</rom>
			<rom type="bgm" offset="0x07">RD07F.MSC</rom>
			<rom type="bgm" offset="0x08">RD08F.MSC</rom>
			<rom type="bgm" offset="0x09">RD09F.MSC</rom>
			<rom type="bgm" offset="0x0a">RD10F.MSC</rom>
			<rom type="bgm" offset="0x0b">RD11F.MSC</rom>
			<rom type="bgm" offset="0x0c">RD12F.MSC</rom>
			<rom type="bgm" offset="0x0d">RD13F.MSC</rom>
			<rom type="bgm" offset="0x0e">RD14F.MSC</rom>
			<rom type="bgm" offset="0x0f">RD15F.MSC</rom>
			<rom type="bgm" offset="0x10">SE01.MSC</rom>
			<rom type="bgm" offset="0x11">SE02.MSC</rom>
			<rom type="bgm" offset="0x12">SE03.MSC</rom>
			<rom type="bgm" offset="0x13">SE04.MSC</rom>
			<rom type="bgm" offset="0x14">SE05.MSC</rom>
			<rom type="bgm" offset="0x15">SE06.MSC</rom>
			<rom type="bgm" offset="0x16">SE07.MSC</rom>
			<rom type="bgm" offset="0x17">SE08.MSC</rom>
			<rom type="bgm" offset="0x18">SE09.MSC</rom>
			<rom type="bgm" offset="0x19">SE10.MSC</rom>
			<rom type="bgm" offset="0x1a">SE11.MSC</rom>
			<rom type="bgm" offset="0x1b">SE12.MSC</rom>
			<rom type="bgm" offset="0x1c">SE13.MSC</rom>
			<rom type="bgm" offset="0x1d">SE14.MSC</rom>
			<rom type="bgm" offset="0x1e">SE15.MSC</rom>
			<rom type="bgm" offset="0x1f">SE16.MSC</rom>
			<rom type="bgm" offset="0x20">SE17.MSC</rom>
		</romlist>
		<titlelist>
			<title code="0x01">RD01F.MSC</title>
			<title code="0x02">RD02F.MSC</title>
			<title code="0x03">RD03F.MSC</title>
			<title code="0x04">RD04F.MSC</title>
			<title code="0x05">RD05F.MSC</title>
			<title code="0x06">RD06F.MSC</title>
			<title code="0x07">RD07F.MSC</title>
			<title code="0x08">RD08F.MSC</title>
			<title code="0x09">RD09F.MSC</title>
			<title code="0x0a">RD10F.MSC</title>
			<title code="0x0b">RD11F.MSC</title>
			<title code="0x0c">RD12F.MSC</title>
			<title code="0x0d">RD13F.MSC</title>
			<title code="0x0e">RD14F.MSC</title>
			<title code="0x0f">RD15F.MSC</title>
			<title code="0x10">SE01.MSC</title>
			<title code="0x11">SE02.MSC</title>
			<title code="0x12">SE03.MSC</title>
			<title code="0x13">SE04.MSC</title>
			<title code="0x14">SE05.MSC</title>
			<title code="0x15">SE06.MSC</title>
			<title code="0x16">SE07.MSC</title>
			<title code="0x17">SE08.MSC</title>
			<title code="0x18">SE09.MSC</title>
			<title code="0x19">SE10.MSC</title>
			<title code="0x1a">SE11.MSC</title>
			<title code="0x1b">SE12.MSC</title>
			<title code="0x1c">SE13.MSC</title>
			<title code="0x1d">SE14.MSC</title>
			<title code="0x1e">SE15.MSC</title>
			<title code="0x1f">SE16.MSC</title>
			<title code="0x20">SE17.MSC</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] 雷の戦士ライディ2(OPN)</name>
		<driver type="opn">pc98dos</driver>
		<driveralias type="NEC PC-9801">ZyX</driveralias>
		<options>
			<option name="clockmul" value="8"/>
		</options>
		<romlist archive="laidi2_98">
			<rom type="file" offset="-1">DOFMDX98.COM</rom>
			<rom type="file" offset="-1">ZVA98.EXE</rom>
			<rom type="conin" offset="5">ZVA98.EXE</rom>
			<rom type="file" offset="0x10">RD201F.MSC</rom>
			<rom type="file" offset="0x11">RD202F.MSC</rom>
			<rom type="file" offset="0x12">RD203F.MSC</rom>
			<rom type="file" offset="0x13">RD204F.MSC</rom>
			<rom type="file" offset="0x14">RD205F.MSC</rom>
			<rom type="file" offset="0x15">RD206F.MSC</rom>
			<rom type="file" offset="0x16">RD207F.MSC</rom>
			<rom type="file" offset="0x17">RD208F.MSC</rom>
			<rom type="file" offset="0x18">RD209F.MSC</rom>
			<rom type="file" offset="0x19">RD210F.MSC</rom>
			<rom type="file" offset="0x1a">RD211F.MSC</rom>
			<rom type="file" offset="0x1b">RD212F.MSC</rom>
			<rom type="file" offset="0x1c">RD213F.MSC</rom>
			<rom type="file" offset="0x1d">RD214F.MSC</rom>
			<rom type="file" offset="0x1e">RD215F.MSC</rom>
			<rom type="file" offset="0x1f">RD216F.MSC</rom>
			<rom type="file" offset="0x20">RD217F.MSC</rom>
			<rom type="file" offset="0x21">RD218F.MSC</rom>
			<rom type="file" offset="0x22">RD219F.MSC</rom>
			<rom type="file" offset="0x23">RD220F.MSC</rom>
			<rom type="file" offset="0x24">RD221F.MSC</rom>
			<rom type="file" offset="0x25">RD222F.MSC</rom>
			<rom type="file" offset="0x26">RD223F.MSC</rom>
			<rom type="file" offset="0x27">RD224F.MSC</rom>
			<rom type="file" offset="0x28">RD225F.MSC</rom>
			<rom type="file" offset="0x29">RD226F.MSC</rom>
			<rom type="file" offset="0x2a">RD227F.MSC</rom>
			<rom type="file" offset="0x2b">RD228F.MSC</rom>
			<rom type="file" offset="0x2c">RD229F.MSC</rom>
			<rom type="file" offset="0x2d">RD230F.MSC</rom>
			<rom type="file" offset="0x2e">RD231F.MSC</rom>
			<rom type="file" offset="0x2f">RD232F.MSC</rom>
			<rom type="file" offset="0x30">RD233F.MSC</rom>
			<rom type="file" offset="0x31">RD234F.MSC</rom>
			<rom type="file" offset="0x32">RD235F.MSC</rom>
			<rom type="file" offset="0x33">RD236F.MSC</rom>
			<rom type="file" offset="0x34">SE01.MSC</rom>
			<rom type="file" offset="0x25">SE02.MSC</rom>
			<rom type="file" offset="0x26">SE03.MSC</rom>
			<rom type="file" offset="0x27">SE04A.MSC</rom>
			<rom type="file" offset="0x28">SE04B.MSC</rom>
			<rom type="file" offset="0x29">SE05.MSC</rom>
			<rom type="file" offset="0x2a">SE06.MSC</rom>
			<rom type="file" offset="0x2b">SE07.MSC</rom>
			<rom type="file" offset="0x2c">SE09.MSC</rom>
			<rom type="file" offset="0x2d">SE10.MSC</rom>
			<rom type="file" offset="0x2e">SE11.MSC</rom>
			<rom type="file" offset="0x2f">SE12.MSC</rom>
			<rom type="file" offset="0x30">SE13.MSC</rom>
			<rom type="file" offset="0x31">SE14.MSC</rom>
			<rom type="file" offset="0x32">SE15.MSC</rom>
			<rom type="file" offset="0x33">SE16.MSC</rom>
			<rom type="file" offset="0x34">SE17.MSC</rom>
			<rom type="file" offset="0x35">SE18.MSC</rom>
			<rom type="file" offset="0x36">SE19.MSC</rom>
			<rom type="file" offset="0x37">SE20.MSC</rom>
			<rom type="file" offset="0x38">SE21.MSC</rom>
			<rom type="file" offset="0x39">SE22.MSC</rom>
			<rom type="shell" offset="0">DOFMDX98</rom>
		</romlist>
		<titlelist>
			<title code="0x10">RD201F.MSC</title>
			<title code="0x11">RD202F.MSC</title>
			<title code="0x12">RD203F.MSC</title>
			<title code="0x13">RD204F.MSC</title>
			<title code="0x14">RD205F.MSC</title>
			<title code="0x15">RD206F.MSC</title>
			<title code="0x16">RD207F.MSC</title>
			<title code="0x17">RD208F.MSC</title>
			<title code="0x18">RD209F.MSC</title>
			<title code="0x19">RD210F.MSC</title>
			<title code="0x1a">RD211F.MSC</title>
			<title code="0x1b">RD212F.MSC</title>
			<title code="0x1c">RD213F.MSC</title>
			<title code="0x1d">RD214F.MSC</title>
			<title code="0x1e">RD215F.MSC</title>
			<title code="0x1f">RD216F.MSC</title>
			<title code="0x20">RD217F.MSC</title>
			<title code="0x21">RD218F.MSC</title>
			<title code="0x22">RD219F.MSC</title>
			<title code="0x23">RD220F.MSC</title>
			<title code="0x24">RD221F.MSC</title>
			<title code="0x25">RD222F.MSC</title>
			<title code="0x26">RD223F.MSC</title>
			<title code="0x27">RD224F.MSC</title>
			<title code="0x28">RD225F.MSC</title>
			<title code="0x29">RD226F.MSC</title>
			<title code="0x2a">RD227F.MSC</title>
			<title code="0x2b">RD228F.MSC</title>
			<title code="0x2c">RD229F.MSC</title>
			<title code="0x2d">RD230F.MSC</title>
			<title code="0x2e">RD231F.MSC</title>
			<title code="0x2f">RD232F.MSC</title>
			<title code="0x30">RD233F.MSC</title>
			<title code="0x31">RD234F.MSC</title>
			<title code="0x32">RD235F.MSC</title>
			<title code="0x33">RD236F.MSC</title>