<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="hoot.xsl"?>
<!DOCTYPE gamelist [
	<!ELEMENT gamelist (game|bind|childlists)*>
	<!ATTLIST gamelist date CDATA #IMPLIED>
	<!ELEMENT childlists (list)*>
	<!ELEMENT list (#PCDATA)>
	<!ELEMENT bind (exts,driver,options?)>
	<!ELEMENT exts (ext)*>
	<!ELEMENT ext (#PCDATA)>
	<!ELEMENT game (name,driver,driveralias?,options?,romlist?,titlelist?)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT driver (#PCDATA)>
	<!ATTLIST driver type CDATA #IMPLIED>
	<!ELEMENT driveralias (#PCDATA)>
	<!ATTLIST driveralias type CDATA #IMPLIED>
	<!ELEMENT options (option)*>
	<!ELEMENT option EMPTY>
	<!ATTLIST option name CDATA #REQUIRED
					 value CDATA #REQUIRED>
	<!ELEMENT romlist (rom)*>
	<!ATTLIST romlist archive CDATA #IMPLIED>
	<!ELEMENT rom (#PCDATA)>
	<!ATTLIST rom type CDATA #REQUIRED
				  offset CDATA #IMPLIED
				  crc32 CDATA #IMPLIED>
	<!ELEMENT titlelist (title|range)*>
	<!ELEMENT title (#PCDATA)>
	<!ATTLIST title code CDATA #REQUIRED
					type CDATA #IMPLIED>
	<!ELEMENT range (#PCDATA)>
	<!ATTLIST range min CDATA #REQUIRED
					max CDATA #REQUIRED
					extcode CDATA #IMPLIED
					start CDATA #IMPLIED>

]>
<gamelist date="2005/09/25">
	<!-- //アボガドパワーズ -->
	<game>
		<name>[PC-9801] Kuro no Danshou: The Literary Fragment (黒の断章 THE LITERARY FRAGMENT) (YM2608)</name>
		<driver type="opna">pc98dos</driver>
		<driveralias type="PC-9801">Abogado Powers</driveralias>
		<options>
			<option name="clockmul" value="8"/>
			<option name="wstimer" value="8"/>
		</options>
		<romlist archive="kurodan_98">
			<rom type="file" offset="-1">CMD.COM</rom>
			<rom type="file" offset="-1">CMDP.COM</rom>
			<rom type="file" offset="0x10">BGM_00.KM</rom>
			<rom type="file" offset="0x11">BGM_01.KM</rom>
			<rom type="file" offset="0x12">BGM_02.KM</rom>
			<rom type="file" offset="0x13">BGM_03.KM</rom>
			<rom type="file" offset="0x14">BGM_04.KM</rom>
			<rom type="file" offset="0x15">BGM_05.KM</rom>
			<rom type="file" offset="0x16">BGM_06.KM</rom>
			<rom type="file" offset="0x17">BGM_07.KM</rom>
			<rom type="file" offset="0x18">BGM_08.KM</rom>
			<rom type="file" offset="0x19">BGM_09.KM</rom>
			<rom type="file" offset="0x1A">BGM_10.KM</rom>
			<rom type="file" offset="0x1B">BGM_11.KM</rom>
			<rom type="file" offset="0x1C">BGM_12.KM</rom>
			<rom type="file" offset="0x1D">BGM_13.KM</rom>
			<rom type="file" offset="0x1E">BGM_14.KM</rom>
			<rom type="file" offset="0x1F">BGM_15.KM</rom>
			<rom type="file" offset="0x20">BGM_16.KM</rom>
			<rom type="file" offset="0x21">BGM_17.KM</rom>
			<rom type="shell" offset="0">CMD /K</rom>
			<rom type="shell" offset="0">CMDP.COM</rom>
		</romlist>
		<titlelist>
			<title code="0x21">[Stop]</title>
			<title code="0x10">BGM_00.KM</title>
			<title code="0x11">BGM_01.KM</title>
			<title code="0x12">BGM_02.KM</title>
			<title code="0x13">BGM_03.KM</title>
			<title code="0x14">BGM_04.KM</title>
			<title code="0x15">BGM_05.KM</title>
			<title code="0x16">BGM_06.KM</title>
			<title code="0x17">BGM_07.KM</title>
			<title code="0x18">BGM_08.KM</title>
			<title code="0x19">BGM_09.KM</title>
			<title code="0x1A">BGM_10.KM</title>
			<title code="0x1B">BGM_11.KM</title>
			<title code="0x1C">BGM_12.KM</title>
			<title code="0x1D">BGM_13.KM</title>
			<title code="0x1E">BGM_14.KM</title>
			<title code="0x1F">BGM_15.KM</title>
			<title code="0x20">BGM_16.KM</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] Kuro no Danshou: The Literary Fragment (黒の断章 THE LITERARY FRAGMENT) (YM2203)</name>
		<driver type="opn">pc98dos</driver>
		<driveralias type="PC-9801">Abogado Powers</driveralias>
		<options>
			<option name="clockmul" value="8"/>
			<option name="wstimer" value="8"/>
		</options>
		<romlist archive="kurodan_98">
			<rom type="file" offset="-1">CMD.COM</rom>
			<rom type="file" offset="-1">CMDP.COM</rom>
			<rom type="file" offset="0x10">BGM_00.KM</rom>
			<rom type="file" offset="0x11">BGM_01.KM</rom>
			<rom type="file" offset="0x12">BGM_02.KM</rom>
			<rom type="file" offset="0x13">BGM_03.KM</rom>
			<rom type="file" offset="0x14">BGM_04.KM</rom>
			<rom type="file" offset="0x15">BGM_05.KM</rom>
			<rom type="file" offset="0x16">BGM_06.KM</rom>
			<rom type="file" offset="0x17">BGM_07.KM</rom>
			<rom type="file" offset="0x18">BGM_08.KM</rom>
			<rom type="file" offset="0x19">BGM_09.KM</rom>
			<rom type="file" offset="0x1A">BGM_10.KM</rom>
			<rom type="file" offset="0x1B">BGM_11.KM</rom>
			<rom type="file" offset="0x1C">BGM_12.KM</rom>
			<rom type="file" offset="0x1D">BGM_13.KM</rom>
			<rom type="file" offset="0x1E">BGM_14.KM</rom>
			<rom type="file" offset="0x1F">BGM_15.KM</rom>
			<rom type="file" offset="0x20">BGM_16.KM</rom>
			<rom type="file" offset="0x21">BGM_17.KM</rom>
			<rom type="shell" offset="0">CMD /K</rom>
			<rom type="shell" offset="0">CMDP.COM</rom>
		</romlist>
		<titlelist>
			<title code="0x21">[Stop]</title>
			<title code="0x10">BGM_00.KM</title>
			<title code="0x11">BGM_01.KM</title>
			<title code="0x12">BGM_02.KM</title>
			<title code="0x13">BGM_03.KM</title>
			<title code="0x14">BGM_04.KM</title>
			<title code="0x15">BGM_05.KM</title>
			<title code="0x16">BGM_06.KM</title>
			<title code="0x17">BGM_07.KM</title>
			<title code="0x18">BGM_08.KM</title>
			<title code="0x19">BGM_09.KM</title>
			<title code="0x1A">BGM_10.KM</title>
			<title code="0x1B">BGM_11.KM</title>
			<title code="0x1C">BGM_12.KM</title>
			<title code="0x1D">BGM_13.KM</title>
			<title code="0x1E">BGM_14.KM</title>
			<title code="0x1F">BGM_15.KM</title>
			<title code="0x20">BGM_16.KM</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] Es no Houteishiki (Esの方程式) (YM2608)</name>
		<driver type="opna">pc98dos</driver>
		<driveralias type="PC-9801">Abogado Powers</driveralias>
		<options>
			<option name="clockmul" value="8"/>
			<option name="wstimer" value="8"/>
		</options>
		<romlist archive="eshoutei_98">
			<rom type="file" offset="-1">CMD.COM</rom>
			<rom type="file" offset="-1">CMDP.COM</rom>
			<rom type="file" offset="0x10">BGM_00.KM</rom>
			<rom type="file" offset="0x11">BGM_02.KM</rom>
			<rom type="file" offset="0x12">BGM_04.KM</rom>
			<rom type="file" offset="0x13">BGM_06.KM</rom>
			<rom type="file" offset="0x14">BGM_08.KM</rom>
			<rom type="file" offset="0x15">BGM_10.KM</rom>
			<rom type="file" offset="0x16">BGM_12.KM</rom>
			<rom type="file" offset="0x17">BGM_14.KM</rom>
			<rom type="file" offset="0x18">BGM_16.KM</rom>
			<rom type="file" offset="0x19">BGM_18.KM</rom>
			<rom type="file" offset="0x1A">BGM_20.KM</rom>
			<rom type="file" offset="0x1B">BGM_22.KM</rom>
			<rom type="file" offset="0x1C">BGM_24.KM</rom>
			<rom type="file" offset="0x1D">BGM_26.KM</rom>
			<rom type="file" offset="0x1E">BGM_28.KM</rom>
			<rom type="file" offset="0x1F">BGM_30.KM</rom>
			<rom type="file" offset="0x20">BGM_32.KM</rom>
			<rom type="file" offset="0x21">BGM_34.KM</rom>
			<rom type="file" offset="0x22">BGM_36.KM</rom>
			<rom type="shell" offset="0">CMD /K</rom>
			<rom type="shell" offset="0">CMDP.COM</rom>
		</romlist>
		<titlelist>
			<title code="0x22">[Stop]</title>
			<title code="0x10">Look Up at the Sky</title>
			<title code="0x11">Retrace One's Memory</title>
			<title code="0x12">Leave......</title>
			<title code="0x13">Soft Wind</title>
			<title code="0x14">Answer</title>
			<title code="0x15">Why</title>
			<title code="0x16">Sense Danger</title>
			<title code="0x17">Next Development</title>
			<title code="0x18">Calmness</title>
			<title code="0x19">Brutal Murder</title>
			<title code="0x1A">Kenta's Theme</title>
			<title code="0x1B">What's Up?</title>
			<title code="0x1C">Fear of Death</title>
			<title code="0x1D">Deep In Sorrow</title>
			<title code="0x1E">Occurrence</title>
			<title code="0x1F">The Origin of Next Tragedy</title>
			<title code="0x20">Stage Clear</title>
			<title code="0x21">Miss</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] Es no Houteishiki (Esの方程式) (YM2203)</name>
		<driver type="opn">pc98dos</driver>
		<driveralias type="PC-9801">Abogado Powers</driveralias>
		<options>
			<option name="clockmul" value="8"/>
			<option name="wstimer" value="8"/>
			<option name="ssg_mix" value="-18"/>
		</options>
		<romlist archive="eshoutei_98">
			<rom type="file" offset="-1">CMD.COM</rom>
			<rom type="file" offset="-1">CMDP.COM</rom>
			<rom type="file" offset="0x10">BGM_00.KM</rom>
			<rom type="file" offset="0x11">BGM_02.KM</rom>
			<rom type="file" offset="0x12">BGM_04.KM</rom>
			<rom type="file" offset="0x13">BGM_06.KM</rom>
			<rom type="file" offset="0x14">BGM_08.KM</rom>
			<rom type="file" offset="0x15">BGM_10.KM</rom>
			<rom type="file" offset="0x16">BGM_12.KM</rom>
			<rom type="file" offset="0x17">BGM_14.KM</rom>
			<rom type="file" offset="0x18">BGM_16.KM</rom>
			<rom type="file" offset="0x19">BGM_18.KM</rom>
			<rom type="file" offset="0x1A">BGM_20.KM</rom>
			<rom type="file" offset="0x1B">BGM_22.KM</rom>
			<rom type="file" offset="0x1C">BGM_24.KM</rom>
			<rom type="file" offset="0x1D">BGM_26.KM</rom>
			<rom type="file" offset="0x1E">BGM_28.KM</rom>
			<rom type="file" offset="0x1F">BGM_30.KM</rom>
			<rom type="file" offset="0x20">BGM_32.KM</rom>
			<rom type="file" offset="0x21">BGM_34.KM</rom>
			<rom type="file" offset="0x22">BGM_36.KM</rom>
			<rom type="shell" offset="0">CMD /K</rom>
			<rom type="shell" offset="0">CMDP.COM</rom>
		</romlist>
		<titlelist>
			<title code="0x22">[Stop]</title>
			<title code="0x10">Look Up at the Sky</title>
			<title code="0x11">Retrace One's Memory</title>
			<title code="0x12">Leave......</title>
			<title code="0x13">Soft Wind</title>
			<title code="0x14">Answer</title>
			<title code="0x15">Why</title>
			<title code="0x16">Sense Danger</title>
			<title code="0x17">Next Development</title>
			<title code="0x18">Calmness</title>
			<title code="0x19">Brutal Murder</title>
			<title code="0x1A">Kenta's Theme</title>
			<title code="0x1B">What's Up?</title>
			<title code="0x1C">Fear of Death</title>
			<title code="0x1D">Deep In Sorrow</title>
			<title code="0x1E">Occurrence</title>
			<title code="0x1F">The Origin of Next Tragedy</title>
			<title code="0x20">Stage Clear</title>
			<title code="0x21">Miss</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] Tsumo Baka Nisshi (つもバカ日誌) (YM2203)</name>
		<driver type="opn">pc98dos</driver>
		<driveralias type="PC-9801">Abogado Powers</driveralias>
		<options>
			<option name="clockmul" value="8"/>
			<option name="wstimer" value="8"/>
			<option name="ssg_mix" value="-18"/>
		</options>
		<romlist archive="tumobaka_98">
			<rom type="file" offset="-1">CMD.COM</rom>
			<rom type="file" offset="-1">CMDP.COM</rom>
			<rom type="file" offset="0x10">BA01.KM</rom>
			<rom type="file" offset="0x11">BA02.KM</rom>
			<rom type="file" offset="0x12">BA03.KM</rom>
			<rom type="file" offset="0x13">BA04.KM</rom>
			<rom type="file" offset="0x14">BA05.KM</rom>
			<rom type="file" offset="0x15">BA06.KM</rom>
			<rom type="file" offset="0x16">BA07.KM</rom>
			<rom type="file" offset="0x17">BA08.KM</rom>
			<rom type="file" offset="0x18">BA09.KM</rom>
			<rom type="file" offset="0x19">BA10.KM</rom>
			<rom type="file" offset="0x1a">BA11.KM</rom>
			<rom type="file" offset="0x1b">BA12.KM</rom>
			<rom type="file" offset="0x1c">BA13.KM</rom>
			<rom type="file" offset="0x1d">BA14.KM</rom>
			<rom type="file" offset="0x1e">BA15.KM</rom>
			<rom type="file" offset="0x1f">BA16.KM</rom>
			<rom type="file" offset="0x20">BA17.KM</rom>
			<rom type="shell" offset="0">CMD /K</rom>
			<rom type="shell" offset="0">CMDP.COM</rom>
		</romlist>
		<titlelist>
			<title code="0x10">雀荘八連荘のテーマ</title>
			<title code="0x11">グースネックのテーマ</title>
			<title code="0x12">景楼閣のテーマ</title>
			<title code="0x13">カジノで流れる曲</title>
			<title code="0x14">エスクワイアのテーマ</title>
			<title code="0x15">パチスロボーナスゲーム</title>
			<title code="0x16">移動時の曲</title>
			<title code="0x17">ぬぎぬぎBGM</title>
			<title code="0x18">ガンクラブチェックのBGM</title>
			<title code="0x19">オープニングの曲</title>
			<title code="0x1A">アイテムショップのBGM</title>
			<title code="0x1B">エンディングその1</title>
			<title code="0x1C">スタッフロール</title>
			<title code="0x1D">キャラクター紹介</title>
			<title code="0x1E">エンディングその2</title>
			<title code="0x1F">半チャン終了時のBGM</title>
			<title code="0x20">パチスロレギュラー時</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] Tsumo Baka Nisshi (つもバカ日誌) (YM2608)</name>
		<driver type="opna">pc98dos</driver>
		<driveralias type="PC-9801">Abogado Powers</driveralias>
		<options>
			<option name="clockmul" value="8"/>
			<option name="wstimer" value="8"/>
		</options>
		<romlist archive="tumobaka_98">
			<rom type="file" offset="-1">CMD.COM</rom>
			<rom type="file" offset="-1">CMDP.COM</rom>
			<rom type="file" offset="0x10">BA01.KM</rom>
			<rom type="file" offset="0x11">BA02.KM</rom>
			<rom type="file" offset="0x12">BA03.KM</rom>
			<rom type="file" offset="0x13">BA04.KM</rom>
			<rom type="file" offset="0x14">BA05.KM</rom>
			<rom type="file" offset="0x15">BA06.KM</rom>
			<rom type="file" offset="0x16">BA07.KM</rom>
			<rom type="file" offset="0x17">BA08.KM</rom>
			<rom type="file" offset="0x18">BA09.KM</rom>
			<rom type="file" offset="0x19">BA10.KM</rom>
			<rom type="file" offset="0x1a">BA11.KM</rom>
			<rom type="file" offset="0x1b">BA12.KM</rom>
			<rom type="file" offset="0x1c">BA13.KM</rom>
			<rom type="file" offset="0x1d">BA14.KM</rom>
			<rom type="file" offset="0x1e">BA15.KM</rom>
			<rom type="file" offset="0x1f">BA16.KM</rom>
			<rom type="file" offset="0x20">BA17.KM</rom>
			<rom type="shell" offset="0">CMD /K</rom>
			<rom type="shell" offset="0">CMDP.COM</rom>
		</romlist>
		<titlelist>
			<title code="0x10">雀荘八連荘のテーマ</title>
			<title code="0x11">グースネックのテーマ</title>
			<title code="0x12">景楼閣のテーマ</title>
			<title code="0x13">カジノで流れる曲</title>
			<title code="0x14">エスクワイアのテーマ</title>
			<title code="0x15">パチスロボーナスゲーム</title>
			<title code="0x16">移動時の曲</title>
			<title code="0x17">ぬぎぬぎBGM</title>
			<title code="0x18">ガンクラブチェックのBGM</title>
			<title code="0x19">オープニングの曲</title>
			<title code="0x1A">アイテムショップのBGM</title>
			<title code="0x1B">エンディングその1</title>
			<title code="0x1C">スタッフロール</title>
			<title code="0x1D">キャラクター紹介</title>
			<title code="0x1E">エンディングその2</title>
			<title code="0x1F">半チャン終了時のBGM</title>
			<title code="0x20">パチスロレギュラー時</title>
		</titlelist>
	</game>
	<game>
		<name>[PC/AT] Kuro no Danshou: The Literary Fragment (黒の断章 THE LITERARY FRAGMENT)</name>
		<driver type="soundblaster16">pcatdos</driver>
		<driveralias type="PC/AT">Abogado Powers</driveralias>
		<options>
			<option name="clockmul" value="0x20"/>
		</options>
		<romlist archive="kurodan_at">
			<rom type="file" offset="-1">TIMER.COM</rom>
			<rom type="file" offset="-1">CMD.COM</rom>
			<rom type="file" offset="-1">CMDP.COM</rom>
			<rom type="file" offset="0x10">BGM_00.KM</rom>
			<rom type="file" offset="0x11">BGM_01.KM</rom>
			<rom type="file" offset="0x12">BGM_02.KM</rom>
			<rom type="file" offset="0x13">BGM_03.KM</rom>
			<rom type="file" offset="0x14">BGM_04.KM</rom>
			<rom type="file" offset="0x15">BGM_05.KM</rom>
			<rom type="file" offset="0x16">BGM_06.KM</rom>
			<rom type="file" offset="0x17">BGM_07.KM</rom>
			<rom type="file" offset="0x18">BGM_08.KM</rom>
			<rom type="file" offset="0x19">BGM_09.KM</rom>
			<rom type="file" offset="0x1A">BGM_10.KM</rom>
			<rom type="file" offset="0x1B">BGM_11.KM</rom>
			<rom type="file" offset="0x1C">BGM_12.KM</rom>
			<rom type="file" offset="0x1D">BGM_13.KM</rom>
			<rom type="file" offset="0x1E">BGM_14.KM</rom>
			<rom type="file" offset="0x1F">BGM_15.KM</rom>
			<rom type="file" offset="0x20">BGM_16.KM</rom>
			<rom type="file" offset="0x21">BGM_17.KM</rom>
			<rom type="shell" offset="0">TIMER</rom>
			<rom type="shell" offset="0">CMD /K</rom>
			<rom type="shell" offset="0">CMDP.COM</rom>
		</romlist>
		<titlelist>
			<title code="0x21">Stop the Music</title>
			<title code="0x10">BGM_00.KM</title>
			<title code="0x11">BGM_01.KM</title>
			<title code="0x12">BGM_02.KM</title>
			<title code="0x13">BGM_03.KM</title>
			<title code="0x14">BGM_04.KM</title>
			<title code="0x15">BGM_05.KM</title>
			<title code="0x16">BGM_06.KM</title>
			<title code="0x17">BGM_07.KM</title>
			<title code="0x18">BGM_08.KM</title>
			<title code="0x19">BGM_09.KM</title>
			<title code="0x1A">BGM_10.KM</title>
			<title code="0x1B">BGM_11.KM</title>
			<title code="0x1C">BGM_12.KM</title>
			<title code="0x1D">BGM_13.KM</title>
			<title code="0x1E">BGM_14.KM</title>
			<title code="0x1F">BGM_15.KM</title>
			<title code="0x20">BGM_16.KM</title>
		</titlelist>
	</game>
	<game>
		<name>[PC/AT] Es no Houteishiki (Esの方程式)</name>
		<driver type="soundblaster16">pcatdos</driver>
		<driveralias type="PC/AT">Abogado Powers</driveralias>
		<options>
			<option name="clockmul" value="0x20"/>
		</options>
		<romlist archive="eshoutei_at">
			<rom type="file" offset="-1">TIMER.COM</rom>
			<rom type="file" offset="-1">CMD.COM</rom>
			<rom type="file" offset="-1">CMDP.COM</rom>
			<rom type="file" offset="0x10">BGM_01.KM</rom>
			<rom type="file" offset="0x11">BGM_03.KM</rom>
			<rom type="file" offset="0x12">BGM_05.KM</rom>
			<rom type="file" offset="0x13">BGM_07.KM</rom>
			<rom type="file" offset="0x14">BGM_09.KM</rom>
			<rom type="file" offset="0x15">BGM_11.KM</rom>
			<rom type="file" offset="0x16">BGM_13.KM</rom>
			<rom type="file" offset="0x17">BGM_15.KM</rom>
			<rom type="file" offset="0x18">BGM_17.KM</rom>
			<rom type="file" offset="0x19">BGM_19.KM</rom>
			<rom type="file" offset="0x1A">BGM_21.KM</rom>
			<rom type="file" offset="0x1B">BGM_23.KM</rom>
			<rom type="file" offset="0x1C">BGM_25.KM</rom>
			<rom type="file" offset="0x1D">BGM_27.KM</rom>
			<rom type="file" offset="0x1E">BGM_29.KM</rom>
			<rom type="file" offset="0x1F">BGM_31.KM</rom>
			<rom type="file" offset="0x20">BGM_33.KM</rom>
			<rom type="file" offset="0x21">BGM_35.KM</rom>
			<rom type="file" offset="0x22">BGM_37.KM</rom>
			<rom type="shell" offset="0">TIMER</rom>
			<rom type="shell" offset="0">CMD /K</rom>
			<rom type="shell" offset="0">CMDP.COM</rom>
		</romlist>
		<titlelist>
			<title code="0x22">[Stop]</title>
			<title code="0x10">Look Up at the Sky</title>
			<title code="0x11">Retrace One's Memory</title>
			<title code="0x12">Leave......</title>
			<title code="0x13">Soft Wind</title>
			<title code="0x14">Answer</title>
			<title code="0x15">Why</title>
			<title code="0x16">Sense Danger</title>
			<title code="0x17">Next Development</title>
			<title code="0x18">Calmness</title>
			<title code="0x19">Brutal Murder</title>
			<title code="0x1A">Kenta's Theme</title>
			<title code="0x1B">What's Up?</title>
			<title code="0x1C">Fear of Death</title>
			<title code="0x1D">Deep in Sorrow</title>
			<title code="0x1E">Occurrence</title>
			<title code="0x1F">The Origin of Next Tragedy</title>
			<title code="0x20">Stage Clear</title>
			<title code="0x21">Miss</title>
		</titlelist>
	</game>
</gamelist>
