<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="hoot.xsl"?>
<!DOCTYPE gamelist [
	<!ELEMENT gamelist (game|bind|childlists)*>
	<!ATTLIST gamelist date CDATA #IMPLIED>
	<!ELEMENT childlists (list)*>
	<!ELEMENT list (#PCDATA)>
	<!ELEMENT bind (exts,driver,options?)>
	<!ELEMENT exts (ext)*>
	<!ELEMENT ext (#PCDATA)>
	<!ELEMENT game (name,driver,driveralias?,options?,romlist?,titlelist?)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT driver (#PCDATA)>
	<!ATTLIST driver type CDATA #IMPLIED>
	<!ELEMENT driveralias (#PCDATA)>
	<!ATTLIST driveralias type CDATA #IMPLIED>
	<!ELEMENT options (option)*>
	<!ELEMENT option EMPTY>
	<!ATTLIST option name CDATA #REQUIRED
					 value CDATA #REQUIRED>
	<!ELEMENT romlist (rom)*>
	<!ATTLIST romlist archive CDATA #IMPLIED>
	<!ELEMENT rom (#PCDATA)>
	<!ATTLIST rom type CDATA #REQUIRED
				  offset CDATA #IMPLIED
				  crc32 CDATA #IMPLIED>
	<!ELEMENT titlelist (title|range)*>
	<!ELEMENT title (#PCDATA)>
	<!ATTLIST title code CDATA #REQUIRED
					type CDATA #IMPLIED>
	<!ELEMENT range (#PCDATA)>
	<!ATTLIST range min CDATA #REQUIRED
					max CDATA #REQUIRED
					extcode CDATA #IMPLIED
					start CDATA #IMPLIED>
]>
<gamelist date="2005/09/25">
	<!-- //ACID PLAN -->
	<game>
		<name>[PC-9801] Charm (シャルム) (YM2203)</name>
		<driver type="opn">pc98dos</driver>
		<driveralias type="PC-9801">Acid Plan</driveralias>
		<options>
			<option name="clockmul" value="8"/>
			<option name="ssg_mix" value="-18"/>
		</options>
		<romlist archive="charm_98">
			<rom type="file" offset="-1">MDRV.COM</rom>
			<rom type="file" offset="-1">MDRV_98.COM</rom>
			<rom type="file" offset="-1">GUN_KUAN.TDT</rom>
			<rom type="file" offset="-1">MS01.KMD</rom>
			<rom type="file" offset="-1">MS02.KMD</rom>
			<rom type="file" offset="-1">MS03.KMD</rom>
			<rom type="file" offset="-1">MS04.KMD</rom>
			<rom type="file" offset="-1">MS05.KMD</rom>
			<rom type="file" offset="-1">MS06.KMD</rom>
			<rom type="file" offset="-1">MS07.KMD</rom>
			<rom type="file" offset="-1">MS08.KMD</rom>
			<rom type="file" offset="-1">MS09.KMD</rom>
			<rom type="file" offset="-1">MS10.KMD</rom>
			<rom type="file" offset="-1">MS11.KMD</rom>
			<rom type="file" offset="-1">MS12.KMD</rom>
			<rom type="file" offset="-1">MS13.KMD</rom>
			<rom type="conin" offset="0x10">MS01.KMD</rom>
			<rom type="conin" offset="0x11">MS02.KMD</rom>
			<rom type="conin" offset="0x12">MS03.KMD</rom>
			<rom type="conin" offset="0x13">MS04.KMD</rom>
			<rom type="conin" offset="0x14">MS05.KMD</rom>
			<rom type="conin" offset="0x15">MS06.KMD</rom>
			<rom type="conin" offset="0x16">MS07.KMD</rom>
			<rom type="conin" offset="0x17">MS08.KMD</rom>
			<rom type="conin" offset="0x18">MS09.KMD</rom>
			<rom type="conin" offset="0x19">MS10.KMD</rom>
			<rom type="conin" offset="0x1a">MS11.KMD</rom>
			<rom type="conin" offset="0x1b">MS12.KMD</rom>
			<rom type="conin" offset="0x1c">MS13.KMD</rom>
			<rom type="shell" offset="0">MDRV</rom>
			<rom type="shell" offset="0">MDRV -tGUN_KUAN.TDT</rom>
			<rom type="shell" offset="0">MDRV_98</rom>
		</romlist>
		<titlelist>
			<title code="0x10">MS01.KMD</title>
			<title code="0x11">MS02.KMD</title>
			<title code="0x12">MS03.KMD</title>
			<title code="0x13">MS04.KMD</title>
			<title code="0x14">MS05.KMD</title>
			<title code="0x15">MS06.KMD</title>
			<title code="0x16">MS07.KMD</title>
			<title code="0x17">MS08.KMD</title>
			<title code="0x18">MS09.KMD</title>
			<title code="0x19">MS10.KMD</title>
			<title code="0x1a">MS11.KMD</title>
			<title code="0x1b">MS12.KMD</title>
			<title code="0x1c">MS13.KMD</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] Charm 2 ~Niji-iro no Kaze~ (シャルム2 ~虹色の風~) (YM2203)</name>
		<driver type="opn">pc98dos</driver>
		<driveralias type="PC-9801">Acid Plan</driveralias>
		<options>
			<option name="clockmul" value="8"/>
			<option name="ssg_mix" value="-18"/>
		</options>
		<romlist archive="charm2_98">
			<rom type="file" offset="-1">MDRV.COM</rom>
			<rom type="file" offset="-1">MDRV_98.COM</rom>
			<rom type="file" offset="-1">GUN_KUAN.TDT</rom>
			<rom type="file" offset="-1">DRUMS.DRM</rom>
			<rom type="file" offset="-1">C001.KMD</rom>
			<rom type="file" offset="-1">C002.KMD</rom>
			<rom type="file" offset="-1">C003.KMD</rom>
			<rom type="file" offset="-1">C004.KMD</rom>
			<rom type="file" offset="-1">C005.KMD</rom>
			<rom type="file" offset="-1">C006.KMD</rom>
			<rom type="file" offset="-1">C007.KMD</rom>
			<rom type="file" offset="-1">C008.KMD</rom>
			<rom type="file" offset="-1">C009.KMD</rom>
			<rom type="file" offset="-1">C010.KMD</rom>
			<rom type="file" offset="-1">C011.KMD</rom>
			<rom type="file" offset="-1">C012.KMD</rom>
			<rom type="file" offset="-1">C013.KMD</rom>
			<rom type="file" offset="-1">C014.KMD</rom>
			<rom type="file" offset="-1">OPENING.KMD</rom>
			<rom type="conin" offset="0x10">C001.KMD</rom>
			<rom type="conin" offset="0x11">C002.KMD</rom>
			<rom type="conin" offset="0x12">C003.KMD</rom>
			<rom type="conin" offset="0x13">C004.KMD</rom>
			<rom type="conin" offset="0x14">C005.KMD</rom>
			<rom type="conin" offset="0x15">C006.KMD</rom>
			<rom type="conin" offset="0x16">C007.KMD</rom>
			<rom type="conin" offset="0x17">C008.KMD</rom>
			<rom type="conin" offset="0x18">C009.KMD</rom>
			<rom type="conin" offset="0x19">C010.KMD</rom>
			<rom type="conin" offset="0x1a">C011.KMD</rom>
			<rom type="conin" offset="0x1b">C012.KMD</rom>
			<rom type="conin" offset="0x1c">C013.KMD</rom>
			<rom type="conin" offset="0x1d">C014.KMD</rom>
			<rom type="conin" offset="0x1e">OPENING.KMD</rom>
			<rom type="shell" offset="0">MDRV</rom>
			<rom type="shell" offset="0">MDRV -tGUN_KUAN.TDT</rom>
			<rom type="shell" offset="0">MDRV -dDRUMS.DRM</rom>
			<rom type="shell" offset="0">MDRV_98</rom>
		</romlist>
		<titlelist>
			<title code="0x1e">虹色の風</title>
			<title code="0x10">英里子</title>
			<title code="0x11">想い</title>
			<title code="0x12">ともしび</title>
			<title code="0x13">そよやぜ</title>
			<title code="0x14">紅鶯翼</title>
			<title code="0x15">鏡映し</title>
			<title code="0x16">心の陰り</title>
			<title code="0x17">WALK</title>
			<title code="0x18">V.S.</title>
			<title code="0x19">Skip</title>
			<title code="0x1a">フレンド</title>
			<title code="0x1b">Pikky</title>
			<title code="0x1c">雀の歌</title>
			<title code="0x1d">西風の中で</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] Charm 2 ~Niji-iro no Kaze~ (シャルム2 ~虹色の風~) (GS)</name>
		<driver type="beep">pc98dos</driver>
		<driveralias type="PC-9801">Acid Plan</driveralias>
		<options>
			<option name="clockmul" value="8"/>
			<option name="midiout" value="1"/>
			<option name="midiout_type" value="4"/>
		</options>
		<romlist archive="charm2_98">
			<rom type="file" offset="-1">MDDRV.COM</rom>
			<rom type="file" offset="-1">MDDRV_98.COM</rom>
			<rom type="file" offset="-1">C001.KMM</rom>
			<rom type="file" offset="-1">C002.KMM</rom>
			<rom type="file" offset="-1">C003.KMM</rom>
			<rom type="file" offset="-1">C004.KMM</rom>
			<rom type="file" offset="-1">C005.KMM</rom>
			<rom type="file" offset="-1">C006.KMM</rom>
			<rom type="file" offset="-1">C007.KMM</rom>
			<rom type="file" offset="-1">C008.KMM</rom>
			<rom type="file" offset="-1">C009.KMM</rom>
			<rom type="file" offset="-1">C010.KMM</rom>
			<rom type="file" offset="-1">C011.KMM</rom>
			<rom type="file" offset="-1">C012.KMM</rom>
			<rom type="file" offset="-1">C013.KMM</rom>
			<rom type="file" offset="-1">C014.KMM</rom>
			<rom type="file" offset="-1">OPENING.KMM</rom>
			<rom type="conin" offset="0x10">C001.KMM</rom>
			<rom type="conin" offset="0x11">C002.KMM</rom>
			<rom type="conin" offset="0x12">C003.KMM</rom>
			<rom type="conin" offset="0x13">C004.KMM</rom>
			<rom type="conin" offset="0x14">C005.KMM</rom>
			<rom type="conin" offset="0x15">C006.KMM</rom>
			<rom type="conin" offset="0x16">C007.KMM</rom>
			<rom type="conin" offset="0x17">C008.KMM</rom>
			<rom type="conin" offset="0x18">C009.KMM</rom>
			<rom type="conin" offset="0x19">C010.KMM</rom>
			<rom type="conin" offset="0x1a">C011.KMM</rom>
			<rom type="conin" offset="0x1b">C012.KMM</rom>
			<rom type="conin" offset="0x1c">C013.KMM</rom>
			<rom type="conin" offset="0x1d">C014.KMM</rom>
			<rom type="conin" offset="0x1e">OPENING.KMM</rom>
			<rom type="shell" offset="0">MDDRV</rom>
			<rom type="shell" offset="0">MDDRV_98</rom>
		</romlist>
		<titlelist>
			<title code="0x1e">虹色の風</title>
			<title code="0x10">英里子</title>
			<title code="0x11">想い</title>
			<title code="0x12">ともしび</title>
			<title code="0x13">そよやぜ</title>
			<title code="0x14">紅鶯翼</title>
			<title code="0x15">鏡映し</title>
			<title code="0x16">心の陰り</title>
			<title code="0x17">WALK</title>
			<title code="0x18">V.S.</title>
			<title code="0x19">Skip</title>
			<title code="0x1a">フレンド</title>
			<title code="0x1b">Pikky</title>
			<title code="0x1c">雀の歌</title>
			<title code="0x1d">西風の中で</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] Charm 2 ~Niji-iro no Kaze~ (シャルム2 ~虹色の風~) (Vermouth, Gravis Ultrasound simulation)</name>
		<driver type="beep">pc98dos</driver>
		<driveralias type="PC-9801">Acid Plan</driveralias>
		<options>
			<option name="clockmul" value="8"/>
			<option name="midiout" value="1"/>
			<option name="midiout_type" value="6"/>
			<option name="midiout_mix" value="0x80"/>
		</options>
		<romlist archive="charm2_98">
			<rom type="file" offset="-1">MDDRV.COM</rom>
			<rom type="file" offset="-1">MDDRV_98.COM</rom>
			<rom type="file" offset="-1">C001.KMM</rom>
			<rom type="file" offset="-1">C002.KMM</rom>
			<rom type="file" offset="-1">C003.KMM</rom>
			<rom type="file" offset="-1">C004.KMM</rom>
			<rom type="file" offset="-1">C005.KMM</rom>
			<rom type="file" offset="-1">C006.KMM</rom>
			<rom type="file" offset="-1">C007.KMM</rom>
			<rom type="file" offset="-1">C008.KMM</rom>
			<rom type="file" offset="-1">C009.KMM</rom>
			<rom type="file" offset="-1">C010.KMM</rom>
			<rom type="file" offset="-1">C011.KMM</rom>
			<rom type="file" offset="-1">C012.KMM</rom>
			<rom type="file" offset="-1">C013.KMM</rom>
			<rom type="file" offset="-1">C014.KMM</rom>
			<rom type="file" offset="-1">OPENING.KMM</rom>
			<rom type="conin" offset="0x10">C001.KMM</rom>
			<rom type="conin" offset="0x11">C002.KMM</rom>
			<rom type="conin" offset="0x12">C003.KMM</rom>
			<rom type="conin" offset="0x13">C004.KMM</rom>
			<rom type="conin" offset="0x14">C005.KMM</rom>
			<rom type="conin" offset="0x15">C006.KMM</rom>
			<rom type="conin" offset="0x16">C007.KMM</rom>
			<rom type="conin" offset="0x17">C008.KMM</rom>
			<rom type="conin" offset="0x18">C009.KMM</rom>
			<rom type="conin" offset="0x19">C010.KMM</rom>
			<rom type="conin" offset="0x1a">C011.KMM</rom>
			<rom type="conin" offset="0x1b">C012.KMM</rom>
			<rom type="conin" offset="0x1c">C013.KMM</rom>
			<rom type="conin" offset="0x1d">C014.KMM</rom>
			<rom type="conin" offset="0x1e">OPENING.KMM</rom>
			<rom type="shell" offset="0">MDDRV</rom>
			<rom type="shell" offset="0">MDDRV_98</rom>
		</romlist>
		<titlelist>
			<title code="0x1e">虹色の風</title>
			<title code="0x10">英里子</title>
			<title code="0x11">想い</title>
			<title code="0x12">ともしび</title>
			<title code="0x13">そよやぜ</title>
			<title code="0x14">紅鶯翼</title>
			<title code="0x15">鏡映し</title>
			<title code="0x16">心の陰り</title>
			<title code="0x17">WALK</title>
			<title code="0x18">V.S.</title>
			<title code="0x19">Skip</title>
			<title code="0x1a">フレンド</title>
			<title code="0x1b">Pikky</title>
			<title code="0x1c">雀の歌</title>
			<title code="0x1d">西風の中で</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] Chrome Paradise ~Ginpaku-iro no Rakuen~ (銀白色の楽園 ~クロムパラダイス~) (YM2203)</name>
		<driver type="opn">pc98dos</driver>
		<driveralias type="PC-9801">Acid Plan</driveralias>
		<options>
			<option name="clockmul" value="8"/>
		</options>
		<romlist archive="cp_98">
			<rom type="file" offset="-1">NAX.com</rom>
			<rom type="file" offset="-1">NLP_HOOT.COM</rom>
			<rom type="file" offset="-1">TONES.DTA</rom>
			<rom type="file" offset="0x10">M_1.O</rom>
			<rom type="file" offset="0x11">M_2.O</rom>
			<rom type="file" offset="0x12">M_3.O</rom>
			<rom type="file" offset="0x13">M_4.O</rom>
			<rom type="file" offset="0x14">M_5.O</rom>
			<rom type="file" offset="0x15">M_6.O</rom>
			<rom type="file" offset="0x16">M_7.O</rom>
			<rom type="file" offset="0x17">M_8.O</rom>
			<rom type="file" offset="0x18">M_9.O</rom>
			<rom type="file" offset="0x19">M_10.O</rom>
			<rom type="shell" offset="0">NAX</rom>
			<rom type="shell" offset="0">NLP_HOOT</rom>
		</romlist>
		<titlelist>
			<title code="0x10">M_1.O</title>
			<title code="0x11">M_2.O</title>
			<title code="0x12">M_3.O</title>
			<title code="0x13">M_4.O</title>
			<title code="0x14">M_5.O</title>
			<title code="0x15">M_6.O</title>
			<title code="0x16">M_7.O</title>
			<title code="0x17">M_8.O</title>
			<title code="0x18">M_9.O</title>
			<title code="0x19">M_10.O</title>
		</titlelist>
	</game>
</gamelist>