<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="hoot.xsl"?>
<!DOCTYPE gamelist [
	<!ELEMENT gamelist (game|bind|childlists)*>
	<!ATTLIST gamelist date CDATA #IMPLIED>
	<!ELEMENT childlists (list)*>
	<!ELEMENT list (#PCDATA)>
	<!ELEMENT bind (exts,driver,options?)>
	<!ELEMENT exts (ext)*>
	<!ELEMENT ext (#PCDATA)>
	<!ELEMENT game (name,driver,driveralias?,options?,romlist?,titlelist?)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT driver (#PCDATA)>
	<!ATTLIST driver type CDATA #IMPLIED>
	<!ELEMENT driveralias (#PCDATA)>
	<!ATTLIST driveralias type CDATA #IMPLIED>
	<!ELEMENT options (option)*>
	<!ELEMENT option EMPTY>
	<!ATTLIST option name CDATA #REQUIRED
					 value CDATA #REQUIRED>
	<!ELEMENT romlist (rom)*>
	<!ATTLIST romlist archive CDATA #IMPLIED>
	<!ELEMENT rom (#PCDATA)>
	<!ATTLIST rom type CDATA #REQUIRED
				  offset CDATA #IMPLIED
				  crc32 CDATA #IMPLIED>
	<!ELEMENT titlelist (title|range)*>
	<!ELEMENT title (#PCDATA)>
	<!ATTLIST title code CDATA #REQUIRED
					type CDATA #IMPLIED>
	<!ELEMENT range (#PCDATA)>
	<!ATTLIST range min CDATA #REQUIRED
					max CDATA #REQUIRED
					extcode CDATA #IMPLIED
					start CDATA #IMPLIED>
]>
<gamelist date="2005/09/25">
	<!-- //Active -->
	<game>
		<name>[PC-9801] Angel Halo (エンジェル・ハイロウ) (YM2203)</name>
		<driver type="opn">pc98dos</driver>
		<driveralias type="PC-9801">Active</driveralias>
		<options>
			<option name="clockmul" value="8"/>
		</options>
		<romlist archive="anglhalo_98">
			<rom type="file" offset="-1">ahalo_98.com</rom>
			<rom type="file" offset="-1">MAIN98.EXE</rom>
			<rom type="conin" offset="5">MAIN98.EXE</rom>
			<rom type="file" offset="11">AN_01.AMD</rom>
			<rom type="file" offset="12">AN_02.AMD</rom>
			<rom type="file" offset="13">AN_03.AMD</rom>
			<rom type="file" offset="14">AN_04.AMD</rom>
			<rom type="file" offset="15">AN_05.AMD</rom>
			<rom type="file" offset="16">AN_06.AMD</rom>
			<rom type="file" offset="17">AN_07.AMD</rom>
			<rom type="file" offset="18">AN_08.AMD</rom>
			<rom type="file" offset="19">AN_09.AMD</rom>
			<rom type="file" offset="20">AN_10.AMD</rom>
			<rom type="file" offset="21">AN_11.AMD</rom>
			<rom type="file" offset="22">AN_12.AMD</rom>
			<rom type="file" offset="23">AN_13.AMD</rom>
			<rom type="file" offset="24">AN_14.AMD</rom>
			<rom type="file" offset="25">AN_15.AMD</rom>
			<rom type="file" offset="26">AN_16.AMD</rom>
			<rom type="file" offset="27">AN_17.AMD</rom>
			<rom type="file" offset="28">AN_18.AMD</rom>
			<rom type="file" offset="29">AN_19.AMD</rom>
			<rom type="shell" offset="0">ahalo_98</rom>
		</romlist>
		<titlelist>
			<title code="11">Angel Halo Op Main</title>
			<title code="12">Angel Halo Op Take 2</title>
			<title code="13">Active Members</title>
			<title code="14">Angel Halo Main 1</title>
			<title code="15">Angel Halo Main 2</title>
			<title code="16">Angel Halo Main 3</title>
			<title code="17">恐怖感</title>
			<title code="18">緊迫</title>
			<title code="19">高揚</title>
			<title code="20">Normal</title>
			<title code="21">abNormal</title>
			<title code="22">束の間の休息</title>
			<title code="23">シュハ、キマセリ electone</title>
			<title code="24">シュハ、キマセリ ending ver.</title>
			<title code="25">1999年のクリスマス</title>
			<title code="26">ジングルベル アレンジメント</title>
			<title code="27">Angel Halo Ending 1</title>
			<title code="28">Angel Halo Ending 2</title>
			<title code="29">Angel Halo Ending 3</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] Angel Halo (エンジェル・ハイロウ) (YM2608)</name>
		<driver type="opna">pc98dos</driver>
		<driveralias type="PC-9801">Active</driveralias>
		<options>
			<option name="clockmul" value="8"/>
		</options>
		<romlist archive="anglhalo_98">
			<rom type="file" offset="-1">ahalo_98.com</rom>
			<rom type="file" offset="-1">MAIN98.EXE</rom>
			<rom type="conin" offset="5">MAIN98.EXE</rom>
			<rom type="file" offset="11">AN_01.AME</rom>
			<rom type="file" offset="12">AN_02.AME</rom>
			<rom type="file" offset="13">AN_03.AME</rom>
			<rom type="file" offset="14">AN_04.AME</rom>
			<rom type="file" offset="15">AN_05.AME</rom>
			<rom type="file" offset="16">AN_06.AME</rom>
			<rom type="file" offset="17">AN_07.AME</rom>
			<rom type="file" offset="18">AN_08.AME</rom>
			<rom type="file" offset="19">AN_09.AME</rom>
			<rom type="file" offset="20">AN_10.AME</rom>
			<rom type="file" offset="21">AN_11.AME</rom>
			<rom type="file" offset="22">AN_12.AME</rom>
			<rom type="file" offset="23">AN_13.AME</rom>
			<rom type="file" offset="24">AN_14.AME</rom>
			<rom type="file" offset="25">AN_15.AME</rom>
			<rom type="file" offset="26">AN_16.AME</rom>
			<rom type="file" offset="27">AN_17.AME</rom>
			<rom type="file" offset="28">AN_18.AME</rom>
			<rom type="file" offset="29">AN_19.AME</rom>
			<rom type="shell" offset="0">ahalo_98</rom>
		</romlist>
		<titlelist>
			<title code="11">Angel Halo Op Main</title>
			<title code="12">Angel Halo Op Take2</title>
			<title code="13">Active Members</title>
			<title code="14">Angel Halo Main1</title>
			<title code="15">Angel Halo Main2</title>
			<title code="16">Angel Halo Main3</title>
			<title code="17">恐怖感</title>
			<title code="18">緊迫</title>
			<title code="19">高揚</title>
			<title code="20">Normal</title>
			<title code="21">abNormal</title>
			<title code="22">束の間の休息</title>
			<title code="23">シュハ、キマセリ electone</title>
			<title code="24">シュハ、キマセリ ending ver.</title>
			<title code="25">1999年のクリスマス</title>
			<title code="26">ジングルベル アレンジメント</title>
			<title code="27">Angel Halo Ending1</title>
			<title code="28">Angel Halo Ending2</title>
			<title code="29">Angel Halo Ending3</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] if (イフ) (YM2203)</name>
		<driver type="opn">pc98dos</driver>
		<driveralias type="PC-9801">Active</driveralias>
		<options>
			<option name="clockmul" value="8"/>
		</options>
		<romlist archive="if_98">
			<rom type="file" offset="-1">if_98.com</rom>
			<rom type="file" offset="-1">MAIN.EXE</rom>
			<rom type="conin" offset="5">MAIN.EXE</rom>
			<rom type="file" offset="0x0b">EFC01.AMD</rom>
			<rom type="file" offset="0x0c">EFC03.AMD</rom>
			<rom type="file" offset="0x0d">EFC06.AMD</rom>
			<rom type="file" offset="0x0e">EFC09.AMD</rom>
			<rom type="file" offset="0x0f">END1.AMD</rom>
			<rom type="file" offset="0x10">END3.AMD</rom>
			<rom type="file" offset="0x11">END4.AMD</rom>
			<rom type="file" offset="0x12">ENDX.AMD</rom>
			<rom type="file" offset="0x13">FAN.AMD</rom>
			<rom type="file" offset="0x14">H1.AMD</rom>
			<rom type="file" offset="0x15">H3.AMD</rom>
			<rom type="file" offset="0x16">H4.AMD</rom>
			<rom type="file" offset="0x17">HX.AMD</rom>
			<rom type="file" offset="0x18">MAIN1_2.AMD</rom>
			<rom type="file" offset="0x19">MAIN3_2.AMD</rom>
			<rom type="file" offset="0x1a">MAIN4_2.AMD</rom>
			<rom type="file" offset="0x1b">MAINX_2.AMD</rom>
			<rom type="file" offset="0x1c">MENU.AMD</rom>
			<rom type="file" offset="0x1d">OPEN.AMD</rom>
			<rom type="shell" offset="0">if_98</rom>
		</romlist>
		<titlelist>
			<title code="0x1c">MENU.AMD</title>
			<title code="0x1d">OPEN.AMD</title>
			<title code="0x18">和也君の憂鬱な日 メインテーマ1</title>
			<title code="0x16">和也君の憂鬱な日 メインテーマ2</title>
			<title code="0x0f">和也君の憂鬱な日 エンディングテーマ</title>
			<title code="0x1b">TriAngel メインテーマ1</title>
			<title code="0x17">TriAngel メインテーマ2</title>
			<title code="0x11">TriAngel エンディングテーマ</title>
			<title code="0x19">桔梗の花 メインテーマ1</title>
			<title code="0x15">桔梗の花 メインテーマ2</title>
			<title code="0x10">桔梗の花 エンディングテーマ</title>
			<title code="0x1a">マディ救出大作戦 メインテーマ1</title>
			<title code="0x14">マディ救出大作戦 メインテーマ2</title>
			<title code="0x12">マディ救出大作戦 エンディングテーマ</title>
			<title code="0x0b">EFC01.AMD</title>
			<title code="0x0c">EFC03.AMD</title>
			<title code="0x0d">EFC06.AMD</title>
			<title code="0x0e">EFC09.AMD</title>
			<title code="0x13">FAN.AMD</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] if 2 (イフ2) (YM2203)</name>
		<driver type="opn">pc98dos</driver>
		<driveralias type="PC-9801">Active</driveralias>
		<options>
			<option name="clockmul" value="8"/>
		</options>
		<romlist archive="if2_98">
			<rom type="file" offset="-1">if2_98.com</rom>
			<rom type="file" offset="-1">MAIN.EXE</rom>
			<rom type="conin" offset="5">MAIN.EXE</rom>
			<rom type="file" offset="0x0b">BGM11.AMD</rom>
			<rom type="file" offset="0x0c">BGM9.AMD</rom>
			<rom type="file" offset="0x0d">EIF2_H.AMD</rom>
			<rom type="file" offset="0x0e">EIF2END1.AMD</rom>
			<rom type="file" offset="0x0f">EIF2END2.AMD</rom>
			<rom type="file" offset="0x10">EIF2HIRU.AMD</rom>
			<rom type="file" offset="0x11">EIF2MORN.AMD</rom>
			<rom type="file" offset="0x12">FBGM1.AMD</rom>
			<rom type="file" offset="0x13">FBGM2.AMD</rom>
			<rom type="file" offset="0x14">FBGM3.AMD</rom>
			<rom type="file" offset="0x15">FBGM4.AMD</rom>
			<rom type="file" offset="0x16">FBGM5.AMD</rom>
			<rom type="file" offset="0x17">FBGM6.AMD</rom>
			<rom type="file" offset="0x18">GBGM12.AMD</rom>
			<rom type="file" offset="0x19">GBGM13.AMD</rom>
			<rom type="file" offset="0x1a">GBGM14.AMD</rom>
			<rom type="file" offset="0x1b">GBGM15.AMD</rom>
			<rom type="file" offset="0x1c">GBGM16.AMD</rom>
			<rom type="file" offset="0x1d">GBGM17.AMD</rom>
			<rom type="file" offset="0x1e">GBGM8.AMD</rom>
			<rom type="file" offset="0x1f">GEFC01.AMD</rom>
			<rom type="shell" offset="0">if2_98</rom>
		</romlist>
		<titlelist>
			<title code="0x0c">BGM9.AMD</title>
			<title code="0x0b">BGM11.AMD</title>
			<title code="0x11">やっぱり薔薇が好き 朝のテーマ</title>
			<title code="0x10">やっぱり薔薇が好き 昼のテーマ</title>
			<title code="0x0d">やっぱり薔薇が好き Hシーン</title>
			<title code="0x0e">やっぱり薔薇が好き エンディング(ハッピー)</title>
			<title code="0x0f">やっぱり薔薇が好き エンディング(バッド)</title>
			<title code="0x12">プリティ・ウーマン メインテーマ</title>
			<title code="0x13">プリティ・ウーマン 成島嬢のテーマ</title>
			<title code="0x14">プリティ・ウーマン 平林嬢のテーマ</title>
			<title code="0x15">プリティ・ウーマン 木戸嬢のテーマ</title>
			<title code="0x16">プリティ・ウーマン 坂本嬢のテーマ</title>
			<title code="0x17">プリティ・ウーマン Hシーンのテーマ</title>
			<title code="0x18">決戦は学校で メインテーマ1</title>
			<title code="0x1e">決戦は学校で メインテーマ2</title>
			<title code="0x19">決戦は学校で 屋上のテーマ2</title>
			<title code="0x1a">決戦は学校で Hシーン</title>
			<title code="0x1f">決戦は学校で 効果音1「ベル」</title>
			<title code="0x1b">決戦は学校で ハッピーエンド</title>
			<title code="0x1c">決戦は学校で バッドエンド1</title>
			<title code="0x1d">決戦は学校で バッドエンド2</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] if 2 (イフ2) (YM2608)</name>
		<driver type="opna">pc98dos</driver>
		<driveralias type="PC-9801">Active</driveralias>
		<options>
			<option name="clockmul" value="8"/>
		</options>
		<romlist archive="if2_98">
			<rom type="file" offset="-1">if2_98.com</rom>
			<rom type="file" offset="-1">MAIN.EXE</rom>
			<rom type="conin" offset="5">MAIN.EXE</rom>
			<rom type="file" offset="0x0b">BGM11.AME</rom>
			<rom type="file" offset="0x0c">BGM9.AME</rom>
			<rom type="file" offset="0x0d">EIF2_H.AME</rom>
			<rom type="file" offset="0x0e">EIF2END1.AME</rom>
			<rom type="file" offset="0x0f">EIF2END2.AME</rom>
			<rom type="file" offset="0x10">EIF2HIRU.AME</rom>
			<rom type="file" offset="0x11">EIF2MORN.AME</rom>
			<rom type="file" offset="0x12">FBGM1.AME</rom>
			<rom type="file" offset="0x13">FBGM2.AME</rom>
			<rom type="file" offset="0x14">FBGM3.AME</rom>
			<rom type="file" offset="0x15">FBGM4.AME</rom>
			<rom type="file" offset="0x16">FBGM5.AME</rom>
			<rom type="file" offset="0x17">FBGM6.AME</rom>
			<rom type="file" offset="0x18">GBGM12.AME</rom>
			<rom type="file" offset="0x19">GBGM13.AME</rom>
			<rom type="file" offset="0x1a">GBGM14.AME</rom>
			<rom type="file" offset="0x1b">GBGM15.AME</rom>
			<rom type="file" offset="0x1c">GBGM16.AME</rom>
			<rom type="file" offset="0x1d">GBGM17.AME</rom>
			<rom type="file" offset="0x1e">GBGM8.AME</rom>
			<rom type="file" offset="0x1f">GEFC01.AME</rom>
			<rom type="shell" offset="0">if2_98</rom>
		</romlist>
		<titlelist>
			<title code="0x0c">BGM9.AME</title>
			<title code="0x0b">BGM11.AME</title>
			<title code="0x11">やっぱり薔薇が好き 朝のテーマ</title>
			<title code="0x10">やっぱり薔薇が好き 昼のテーマ</title>
			<title code="0x0d">やっぱり薔薇が好き Hシーン</title>
			<title code="0x0e">やっぱり薔薇が好き エンディング(ハッピー)</title>
			<title code="0x0f">やっぱり薔薇が好き エンディング(バッド)</title>
			<title code="0x12">プリティ・ウーマン メインテーマ</title>
			<title code="0x13">プリティ・ウーマン 成島嬢のテーマ</title>
			<title code="0x14">プリティ・ウーマン 平林嬢のテーマ</title>
			<title code="0x15">プリティ・ウーマン 木戸嬢のテーマ</title>
			<title code="0x16">プリティ・ウーマン 坂本嬢のテーマ</title>
			<title code="0x17">プリティ・ウーマン Hシーンのテーマ</title>
			<title code="0x18">決戦は学校で メインテーマ1</title>
			<title code="0x1e">決戦は学校で メインテーマ2</title>
			<title code="0x19">決戦は学校で 屋上のテーマ2</title>
			<title code="0x1a">決戦は学校で Hシーン</title>
			<title code="0x1f">決戦は学校で 効果音1「ベル」</title>
			<title code="0x1b">決戦は学校で ハッピーエンド</title>
			<title code="0x1c">決戦は学校で バッドエンド1</title>
			<title code="0x1d">決戦は学校で バッドエンド2</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] if 3 (イフ3) (YM2203)</name>
		<driver type="opn">pc98dos</driver>
		<driveralias type="PC-9801">Active</driveralias>
		<options>
			<option name="clockmul" value="8"/>
		</options>
		<romlist archive="if3_98">
			<rom type="file" offset="-1">if3_98.com</rom>
			<rom type="file" offset="-1">MAIN.EXE</rom>
			<rom type="conin" offset="5">MAIN.EXE</rom>
			<rom type="file" offset="0x0b">_01.AMD</rom>
			<rom type="file" offset="0x0d">_02.AMD</rom>
			<rom type="file" offset="0x0f">H03.AMD</rom>
			<rom type="file" offset="0x10">H04.AMD</rom>
			<rom type="file" offset="0x11">H05.AMD</rom>
			<rom type="file" offset="0x12">H06.AMD</rom>
			<rom type="file" offset="0x13">H07.AMD</rom>
			<rom type="file" offset="0x14">H08.AMD</rom>
			<rom type="file" offset="0x15">H09.AMD</rom>
			<rom type="file" offset="0x16">H10.AMD</rom>
			<rom type="file" offset="0x17">I11.AMD</rom>
			<rom type="file" offset="0x18">I12.AMD</rom>
			<rom type="file" offset="0x19">I13.AMD</rom>
			<rom type="file" offset="0x1a">I14.AMD</rom>
			<rom type="file" offset="0x1b">I15.AMD</rom>
			<rom type="file" offset="0x1c">I16.AMD</rom>
			<rom type="file" offset="0x1d">I17.AMD</rom>
			<rom type="file" offset="0x1e">J18.AMD</rom>
			<rom type="file" offset="0x1f">J19.AMD</rom>
			<rom type="file" offset="0x20">J20.AMD</rom>
			<rom type="file" offset="0x21">J21.AMD</rom>
			<rom type="file" offset="0x22">J22.AMD</rom>
			<rom type="shell" offset="0">if3_98</rom>
		</romlist>
		<titlelist>
			<title code="0x0d">_02.AMD</title>
			<title code="0x0b">_01.AMD</title>
			<title code="0x0f">自殺志願 ビルの屋上のテーマ</title>
			<title code="0x10">自殺志願 女神様のテーマ</title>
			<title code="0x11">自殺志願 街頭のテーマ</title>
			<title code="0x12">自殺志願 ホテルのテーマ</title>
			<title code="0x13">自殺志願 シャワーを浴びるテーマ</title>
			<title code="0x14">自殺志願 Hテーマ、純愛編</title>
			<title code="0x15">自殺志願 Hテーマ、ものごっつうH編</title>
			<title code="0x16">自殺志願 Hテーマ、SM編</title>
			<title code="0x17">魔法少女のように 夜のテーマ</title>
			<title code="0x19">魔法少女のように 病院と、街のテーマ</title>
<!--
			<title code="0x18">魔法少女のように 変身シーンのテーマ</title>
-->
			<title code="0x1a">魔法少女のように 変身シーンのテーマ</title>
			<title code="0x1b">魔法少女のように Hシーンのテーマ</title>
			<title code="0x1c">魔法少女のように 少しふざけた音楽</title>
			<title code="0x1d">魔法少女のように さわやかな音楽</title>
			<title code="0x1e">EDAY&amp;MAGY メインテーマ</title>
			<title code="0x1f">EDAY&amp;MAGY アップテンポテーマ</title>
			<title code="0x20">EDAY&amp;MAGY スローテンポテーマ</title>
<!--
			<title code="0x21">EDAY&amp;MAGY Hのテーマ</title>
-->
			<title code="0x22">EDAY&amp;MAGY Hのテーマ</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] Sweet Angel (スウィートエンジェル) (YM2203)</name>
		<driver type="opn">pc98dos</driver>
		<driveralias type="PC-9801">Active</driveralias>
		<options>
			<option name="clockmul" value="8"/>
		</options>
		<romlist archive="sange_98">
			<rom type="file" offset="-1">sange_98.com</rom>
			<rom type="file" offset="-1">MAIN.EXE</rom>
			<rom type="conin" offset="5">MAIN.EXE</rom>
			<rom type="file" offset="0x0b">B1.AMD</rom>
			<rom type="file" offset="0x0c">B2.AMD</rom>
			<rom type="file" offset="0x0d">B4.AMD</rom>
			<rom type="file" offset="0x0e">B44.AMD</rom>
			<rom type="file" offset="0x0f">BGM1.AMD</rom>
			<rom type="file" offset="0x10">BGM3.AMD</rom>
			<rom type="file" offset="0x11">BGM4.AMD</rom>
			<rom type="file" offset="0x12">BGM5.AMD</rom>
			<rom type="file" offset="0x13">BGM6.AMD</rom>
			<rom type="file" offset="0x14">BGM8.AMD</rom>
			<rom type="file" offset="0x15">BGM10.AMD</rom>
			<rom type="file" offset="0x16">BGM11.AMD</rom>
			<rom type="file" offset="0x17">BUU.AMD</rom>
			<rom type="file" offset="0x18">KO1.AMD</rom>
			<rom type="file" offset="0x19">KO2.AMD</rom>
			<rom type="file" offset="0x1a">KO3.AMD</rom>
			<rom type="file" offset="0x1b">KO4.AMD</rom>
			<rom type="file" offset="0x1c">KO5.AMD</rom>
			<rom type="file" offset="0x1d">KO6.AMD</rom>
			<rom type="file" offset="0x1e">KO7.AMD</rom>
			<rom type="file" offset="0x1f">KO8.AMD</rom>
			<rom type="file" offset="0x20">KO9.AMD</rom>
			<rom type="file" offset="0x21">KO10.AMD</rom>
			<rom type="file" offset="0x22">KO11.AMD</rom>
			<rom type="file" offset="0x23">KO12.AMD</rom>
			<rom type="file" offset="0x24">KO13.AMD</rom>
			<rom type="file" offset="0x25">KO14.AMD</rom>
			<rom type="file" offset="0x26">KO15.AMD</rom>
			<rom type="file" offset="0x27">M1.AMD</rom>
			<rom type="file" offset="0x28">M2.AMD</rom>
			<rom type="file" offset="0x29">M31.AMD</rom>
			<rom type="shell" offset="0">sange_98</rom>
		</romlist>
		<titlelist>
			<title code="0x0b">B1.AMD</title>
			<title code="0x0c">B2.AMD</title>
			<title code="0x0d">B4.AMD</title>
			<title code="0x0e">B44.AMD</title>
			<title code="0x0f">BGM1.AMD</title>
			<title code="0x10">BGM3.AMD</title>
			<title code="0x11">BGM4.AMD</title>
			<title code="0x12">BGM5.AMD</title>
			<title code="0x13">BGM6.AMD</title>
			<title code="0x14">BGM8.AMD</title>
			<title code="0x15">BGM10.AMD</title>
			<title code="0x16">BGM11.AMD</title>
			<title code="0x17">BUU.AMD</title>
			<title code="0x27">M1.AMD</title>
			<title code="0x28">M2.AMD</title>
			<title code="0x29">M31.AMD</title>
			<title code="0x18">KO1.AMD</title>
			<title code="0x19">KO2.AMD</title>
			<title code="0x1a">KO3.AMD</title>
			<title code="0x1b">KO4.AMD</title>
			<title code="0x1c">KO5.AMD</title>
			<title code="0x1d">KO6.AMD</title>
			<title code="0x1e">KO7.AMD</title>
			<title code="0x1f">KO8.AMD</title>
			<title code="0x20">KO9.AMD</title>
			<title code="0x21">KO10.AMD</title>
			<title code="0x22">KO11.AMD</title>
			<title code="0x23">KO12.AMD</title>
			<title code="0x24">KO13.AMD</title>
			<title code="0x25">KO14.AMD</title>
			<title code="0x26">KO15.AMD</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] Kusuriyubi no Kyoukasho (くすり指の教科書) (YM2203)</name>
		<driver type="opn">pc98dos</driver>
		<driveralias type="PC-9801">Active</driveralias>
		<options>
			<option name="clockmul" value="8"/>
			<option name="ssg_mix" value="8"/>
		</options>
		<romlist archive="kusuriyb_98">
			<rom type="file" offset="-1">kusur_98.com</rom>
			<rom type="file" offset="-1">MAIN.EXE</rom>
			<rom type="conin" offset="5">MAIN.EXE</rom>
			<rom type="file" offset="11">MUSIC00.AMD</rom>
			<rom type="file" offset="12">MUSIC01.AMD</rom>
			<rom type="file" offset="13">MUSIC02.AMD</rom>
			<rom type="file" offset="14">MUSIC03.AMD</rom>
			<rom type="file" offset="15">MUSIC04.AMD</rom>
			<rom type="file" offset="16">MUSIC05.AMD</rom>
			<rom type="file" offset="17">MUSIC06.AMD</rom>
			<rom type="file" offset="18">MUSIC07.AMD</rom>
			<rom type="file" offset="19">MUSIC08.AMD</rom>
			<rom type="file" offset="20">MUSIC09.AMD</rom>
			<rom type="file" offset="21">MUSIC10.AMD</rom>
			<rom type="file" offset="22">MUSIC11.AMD</rom>
			<rom type="file" offset="23">MUSIC12.AMD</rom>
			<rom type="file" offset="24">MUSIC13.AMD</rom>
			<rom type="file" offset="25">MUSIC14.AMD</rom>
			<rom type="file" offset="26">MUSIC15.AMD</rom>
			<rom type="file" offset="27">START.AMD</rom>
			<rom type="shell" offset="0">kusur_98</rom>
		</romlist>
		<titlelist>
			<title code="11">くすり指の教科書オルゴールバージョン</title>
			<title code="12">くすり指の教科書(TV-Edit)</title>
			<title code="13">お散歩のテーマ</title>
			<title code="14">ともみのテーマ "今日もいい天気!"</title>
			<title code="15">有美～ありみ～のテーマ</title>
			<title code="16">ほんの少しの勇気を君に</title>
			<title code="17">淋しくなんかないもんね!</title>
			<title code="18">部屋のテーマ</title>
			<title code="19">お散歩テーマ2</title>
			<title code="20">お遊びのテーマ</title>
			<title code="21">学校のテーマ</title>
			<title code="22">海辺の告白</title>
			<title code="23">りんどうの咲く丘で</title>
			<title code="24">遠い約束</title>
			<title code="25">怖い曲</title>
			<title code="26">想い出のオルゴール</title>
			<title code="27">START.AMD</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] Kusuriyubi no Kyoukasho (くすり指の教科書) (YM2608)</name>
		<driver type="opna">pc98dos</driver>
		<driveralias type="PC-9801">Active</driveralias>
		<options>
			<option name="clockmul" value="8"/>
		</options>
		<romlist archive="kusuriyb_98">
			<rom type="file" offset="-1">kusur_98.com</rom>
			<rom type="file" offset="-1">MAIN.EXE</rom>
			<rom type="conin" offset="5">MAIN.EXE</rom>
			<rom type="file" offset="11">MUSIC00.AME</rom>
			<rom type="file" offset="12">MUSIC01.AME</rom>
			<rom type="file" offset="13">MUSIC02.AME</rom>
			<rom type="file" offset="14">MUSIC03.AME</rom>
			<rom type="file" offset="15">MUSIC04.AME</rom>
			<rom type="file" offset="16">MUSIC05.AME</rom>
			<rom type="file" offset="17">MUSIC06.AME</rom>
			<rom type="file" offset="18">MUSIC07.AME</rom>
			<rom type="file" offset="19">MUSIC08.AME</rom>
			<rom type="file" offset="20">MUSIC09.AME</rom>
			<rom type="file" offset="21">MUSIC10.AME</rom>
			<rom type="file" offset="22">MUSIC11.AME</rom>
			<rom type="file" offset="23">MUSIC12.AME</rom>
			<rom type="file" offset="24">MUSIC13.AME</rom>
			<rom type="file" offset="25">MUSIC14.AME</rom>
			<rom type="file" offset="26">MUSIC15.AME</rom>
			<rom type="file" offset="27">START.AME</rom>
			<rom type="shell" offset="0">kusur_98</rom>
		</romlist>
		<titlelist>
			<title code="11">くすり指の教科書オルゴールバージョン</title>
			<title code="12">くすり指の教科書(TV-Edit)</title>
			<title code="13">お散歩のテーマ</title>
			<title code="14">ともみのテーマ "今日もいい天気!"</title>
			<title code="15">有美～ありみ～のテーマ</title>
			<title code="16">ほんの少しの勇気を君に</title>
			<title code="17">淋しくなんかないもんね!</title>
			<title code="18">部屋のテーマ</title>
			<title code="19">お散歩テーマ2</title>
			<title code="20">お遊びのテーマ</title>
			<title code="21">学校のテーマ</title>
			<title code="22">海辺の告白</title>
			<title code="23">りんどうの咲く丘で</title>
			<title code="24">遠い約束</title>
			<title code="25">怖い曲</title>
			<title code="26">想い出のオルゴール</title>
			<title code="27">START.AMD</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] Misato-chan no Yume Nikki (みさとちゃんの夢日記) (YM2203)</name>
		<driver type="opn">pc98dos</driver>
		<driveralias type="PC-9801">Active</driveralias>
		<options>
			<option name="clockmul" value="8"/>
			<option name="ssg_mix" value="8"/>
		</options>
		<romlist archive="misat_98">
			<rom type="file" offset="-1">misat_98.com</rom>
			<rom type="file" offset="-1">MAIN98.EXE</rom>
			<rom type="conin" offset="5">MAIN98.EXE</rom>
			<rom type="file" offset="0x0b">IDOL1_A.AMD</rom>
			<rom type="file" offset="0x0c">IDOL2_A.AMD</rom>
			<rom type="file" offset="0x0d">IDOL3_A.AMD</rom>
			<rom type="file" offset="0x0e">IDOL4_A.AMD</rom>
			<rom type="file" offset="0x0f">IDOL5_A.AMD</rom>
			<rom type="file" offset="0x10">IDOL6_A.AMD</rom>
			<rom type="file" offset="0x11">MAD1_A.AMD</rom>
			<rom type="file" offset="0x12">MAD2_A.AMD</rom>
			<rom type="file" offset="0x13">MAD3_A.AMD</rom>
			<rom type="file" offset="0x14">MAD4_A.AMD</rom>
			<rom type="file" offset="0x15">MAD5_A.AMD</rom>
			<rom type="file" offset="0x16">MAD6_A.AMD</rom>
			<rom type="file" offset="0x17">MAID1_A.AMD</rom>
			<rom type="file" offset="0x18">MAID2_A.AMD</rom>
			<rom type="file" offset="0x19">MAID3_A.AMD</rom>
			<rom type="file" offset="0x1a">MAID4_A.AMD</rom>
			<rom type="file" offset="0x1b">MAID5_A.AMD</rom>
			<rom type="file" offset="0x1c">MAID6_A.AMD</rom>
			<rom type="shell" offset="0">misat_98</rom>
		</romlist>
		<titlelist>
			<title code="0x10">IDOL6_A.AMD</title>
			<title code="0x0e">IDOL4_A.AMD</title>
			<title code="0x0d">IDOL3_A.AMD</title>
			<title code="0x0b">IDOL1_A.AMD</title>
			<title code="0x18">MAID2_A.AMD</title>
			<title code="0x1a">MAID4_A.AMD</title>
			<title code="0x1c">MAID6_A.AMD</title>
			<title code="0x0c">IDOL2_A.AMD</title>
			<title code="0x0f">IDOL5_A.AMD</title>
<!--
			<title code="0x11">MAD1_A.AMD</title>
			<title code="0x12">MAD2_A.AMD</title>
			<title code="0x13">MAD3_A.AMD</title>
			<title code="0x14">MAD4_A.AMD</title>
			<title code="0x15">MAD5_A.AMD</title>
			<title code="0x16">MAD6_A.AMD</title>
			<title code="0x17">MAID1_A.AMD</title>
			<title code="0x19">MAID3_A.AMD</title>
			<title code="0x1b">MAID5_A.AMD</title>
-->
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] Misato-chan no Yume Nikki (みさとちゃんの夢日記) (YM2608)</name>
		<driver type="opna">pc98dos</driver>
		<driveralias type="PC-9801">Active</driveralias>
		<options>
			<option name="clockmul" value="8"/>
		</options>
		<romlist archive="misat_98">
			<rom type="file" offset="-1">misat_98.com</rom>
			<rom type="file" offset="-1">MAIN98.EXE</rom>
			<rom type="conin" offset="5">MAIN98.EXE</rom>
			<rom type="file" offset="0x0b">IDOL1_A.AME</rom>
			<rom type="file" offset="0x0c">IDOL2_A.AME</rom>
			<rom type="file" offset="0x0d">IDOL3_A.AME</rom>
			<rom type="file" offset="0x0e">IDOL4_A.AME</rom>
			<rom type="file" offset="0x0f">IDOL5_A.AME</rom>
			<rom type="file" offset="0x10">IDOL6_A.AME</rom>
			<rom type="file" offset="0x11">MAD1_A.AME</rom>
			<rom type="file" offset="0x12">MAD2_A.AME</rom>
			<rom type="file" offset="0x13">MAD3_A.AME</rom>
			<rom type="file" offset="0x14">MAD4_A.AME</rom>
			<rom type="file" offset="0x15">MAD5_A.AME</rom>
			<rom type="file" offset="0x16">MAD6_A.AME</rom>
			<rom type="file" offset="0x17">MAID1_A.AME</rom>
			<rom type="file" offset="0x18">MAID2_A.AME</rom>
			<rom type="file" offset="0x19">MAID3_A.AME</rom>
			<rom type="file" offset="0x1a">MAID4_A.AME</rom>
			<rom type="file" offset="0x1b">MAID5_A.AME</rom>
			<rom type="file" offset="0x1c">MAID6_A.AME</rom>
			<rom type="shell" offset="0">misat_98</rom>
		</romlist>
		<titlelist>
			<title code="0x10">IDOL6_A.AME</title>
			<title code="0x0e">IDOL4_A.AME</title>
			<title code="0x0d">IDOL3_A.AME</title>
			<title code="0x0b">IDOL1_A.AME</title>
			<title code="0x18">MAID2_A.AME</title>
			<title code="0x1a">MAID4_A.AME</title>
			<title code="0x1c">MAID6_A.AME</title>
			<title code="0x0c">IDOL2_A.AME</title>
			<title code="0x0f">IDOL5_A.AME</title>
<!--
			<title code="0x11">MAD1_A.AME</title>
			<title code="0x12">MAD2_A.AME</title>
			<title code="0x13">MAD3_A.AME</title>
			<title code="0x14">MAD4_A.AME</title>
			<title code="0x15">MAD5_A.AME</title>
			<title code="0x16">MAD6_A.AME</title>
			<title code="0x17">MAID1_A.AME</title>
			<title code="0x19">MAID3_A.AME</title>
			<title code="0x1b">MAID5_A.AME</title>
-->
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] Gun Blaze (ガンブレイズ) (YM2203)</name>
		<driver type="opn">pc98dos</driver>
		<driveralias type="PC-9801">Active</driveralias>
		<options>
			<option name="clockmul" value="8"/>
			<option name="ssg_mix" value="-18"/>
		</options>
		<romlist archive="gunbl_98">
			<rom type="file" offset="-1">gunbl_98.com</rom>
			<rom type="file" offset="-1">MAIN.EXE</rom>
			<rom type="conin" offset="5">MAIN.EXE</rom>
			<rom type="file" offset="0x0b">GB00.AMD</rom>
			<rom type="file" offset="0x0c">GB01.AMD</rom>
			<rom type="file" offset="0x0d">GB02.AMD</rom>
			<rom type="file" offset="0x0e">GB03.AMD</rom>
			<rom type="file" offset="0x0f">GB04.AMD</rom>
			<rom type="file" offset="0x10">GB05.AMD</rom>
			<rom type="file" offset="0x11">GB06.AMD</rom>
			<rom type="file" offset="0x12">GB07.AMD</rom>
			<rom type="file" offset="0x13">GB08.AMD</rom>
			<rom type="file" offset="0x14">GB09.AMD</rom>
			<rom type="file" offset="0x15">GB10.AMD</rom>
			<rom type="file" offset="0x16">GB11.AMD</rom>
			<rom type="file" offset="0x17">GB12.AMD</rom>
			<rom type="file" offset="0x18">GB13.AMD</rom>
			<rom type="file" offset="0x19">GB14.AMD</rom>
			<rom type="file" offset="0x1a">GB15.AMD</rom>
			<rom type="file" offset="0x1b">GB16.AMD</rom>
			<rom type="file" offset="0x1c">GB17.AMD</rom>
			<rom type="file" offset="0x1d">GB18.AMD</rom>
			<rom type="file" offset="0x1e">GB19.AMD</rom>
			<rom type="file" offset="0x1f">GB20.AMD</rom>
			<rom type="file" offset="0x20">GB21.AMD</rom>
			<rom type="file" offset="0x21">GB22.AMD</rom>
			<rom type="file" offset="0x22">GB23.AMD</rom>
			<rom type="file" offset="0x23">GB24.AMD</rom>
			<rom type="file" offset="0x24">GB25.AMD</rom>
			<rom type="file" offset="0x25">GB26.AMD</rom>
			<rom type="file" offset="0x26">GB27.AMD</rom>
			<rom type="file" offset="0x27">GB28.AMD</rom>
			<rom type="file" offset="0x28">GB29.AMD</rom>
			<rom type="file" offset="0x29">GB30.AMD</rom>
			<rom type="file" offset="0x2a">GB31.AMD</rom>
			<rom type="file" offset="0x2b">GB32.AMD</rom>
			<rom type="file" offset="0x2c">GB33.AMD</rom>
			<rom type="file" offset="0x2d">START.AMD</rom>
			<rom type="shell" offset="0">gunbl_98</rom>
		</romlist>
		<titlelist>
			<title code="0x0b">オープニング</title>
<!--
			<title code="0x0c">オープニング</title>
-->
			<title code="0x0d">レッドツエッペリン・飛行音</title>
<!--
			<title code="0x26">レッドツエッペリン・飛行音</title>
-->
			<title code="0x0e">林の飛行挺・飛行音</title>
			<title code="0x0f">『店』のテーマ</title>
			<title code="0x10">緊迫</title>
<!--
			<title code="0x18">緊迫</title>
-->
			<title code="0x11">躍動</title>
<!--
			<title code="0x1b">躍動</title>
-->
			<title code="0x12">マークの部屋のテーマ</title>
			<title code="0x13">Hシーンテーマ1</title>
			<title code="0x14">感動</title>
			<title code="0x15">元気・パトリシアのテーマ</title>
			<title code="0x16">ファンファーレ</title>