<?xml version="1.0" encoding="Shift_JIS"?>
<?xml-stylesheet type="text/xsl" href="hoot.xsl"?>
<!DOCTYPE gamelist [
	<!ELEMENT gamelist (game|bind|childlists)*>
	<!ATTLIST gamelist date CDATA #IMPLIED>
	<!ELEMENT childlists (list)*>
	<!ELEMENT list (#PCDATA)>
	<!ELEMENT bind (exts,driver,options?)>
	<!ELEMENT exts (ext)*>
	<!ELEMENT ext (#PCDATA)>
	<!ELEMENT game (name,driver,driveralias?,options?,romlist?,titlelist?)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT driver (#PCDATA)>
	<!ATTLIST driver type CDATA #IMPLIED>
	<!ELEMENT driveralias (#PCDATA)>
	<!ATTLIST driveralias type CDATA #IMPLIED>
	<!ELEMENT options (option)*>
	<!ELEMENT option EMPTY>
	<!ATTLIST option name CDATA #REQUIRED
					 value CDATA #REQUIRED>
	<!ELEMENT romlist (rom)*>
	<!ATTLIST romlist archive CDATA #IMPLIED>
	<!ELEMENT rom (#PCDATA)>
	<!ATTLIST rom type CDATA #REQUIRED
				  offset CDATA #IMPLIED
				  crc32 CDATA #IMPLIED>
	<!ELEMENT titlelist (title|range)*>
	<!ELEMENT title (#PCDATA)>
	<!ATTLIST title code CDATA #REQUIRED
					type CDATA #IMPLIED>
	<!ELEMENT range (#PCDATA)>
	<!ATTLIST range min CDATA #REQUIRED
					max CDATA #REQUIRED
					extcode CDATA #IMPLIED>
]>
<gamelist date="2005/09/25">
	<!-- //Gloria -->
	<game>
		<name>[PC-9801] Reverse (リバース) (YM2203)</name>
		<driver type="opn">pc98dos</driver>
		<driveralias type="PC-9801">Gloria</driveralias>
		<options>
			<option name="clockmul" value="8"/>
		</options>
		<romlist archive="reverse_98">
			<rom type="file" offset="-1">UFMD.COM</rom>
			<rom type="file" offset="-1">UFMD_98.COM</rom>
			<rom type="file" offset="0x10">REV01.USG</rom>
			<rom type="file" offset="0x11">REV02.USG</rom>
			<rom type="file" offset="0x12">REV03.USG</rom>
			<rom type="file" offset="0x13">REV04.USG</rom>
			<rom type="file" offset="0x14">REV05.USG</rom>
			<rom type="file" offset="0x15">REV06.USG</rom>
			<rom type="file" offset="0x16">REV07.USG</rom>
			<rom type="file" offset="0x17">REV08.USG</rom>
			<rom type="file" offset="0x18">REV09.USG</rom>
			<rom type="file" offset="0x19">REV10.USG</rom>
			<rom type="file" offset="0x1a">REV11.USG</rom>
			<rom type="file" offset="0x1b">REV12.USG</rom>
			<rom type="file" offset="0x1c">REV13.USG</rom>
			<rom type="file" offset="0x1d">REV14.USG</rom>
			<rom type="file" offset="0x1e">REV15.USG</rom>
			<rom type="file" offset="0x1f">REV16.USG</rom>
			<rom type="file" offset="0x20">REV17.USG</rom>
			<rom type="file" offset="0x21">REV18.USG</rom>
			<rom type="file" offset="0x22">REV19.USG</rom>
			<rom type="shell" offset="0">UFMD</rom>
			<rom type="shell" offset="0">UFMD_98</rom>
		</romlist>
		<titlelist>
			<title code="0x10">REV01.USG</title>
			<title code="0x11">REV02.USG</title>
			<title code="0x12">REV03.USG</title>
			<title code="0x13">REV04.USG</title>
			<title code="0x14">REV05.USG</title>
			<title code="0x15">REV06.USG</title>
			<title code="0x16">REV07.USG</title>
			<title code="0x17">REV08.USG</title>
			<title code="0x18">REV09.USG</title>
			<title code="0x19">REV10.USG</title>
			<title code="0x1a">REV11.USG</title>
			<title code="0x1b">REV12.USG</title>
			<title code="0x1c">REV13.USG</title>
			<title code="0x1d">REV14.USG</title>
			<title code="0x1e">REV15.USG</title>
			<title code="0x1f">REV16.USG</title>
			<title code="0x20">REV17.USG</title>
			<title code="0x21">REV18.USG</title>
			<title code="0x22">REV19.USG</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] Moratorium (モラトリアム) (YM2203)</name>
		<driver type="opn">pc98dos</driver>
		<driveralias type="PC-9801">Gloria</driveralias>
		<options>
			<option name="clockmul" value="8"/>
		</options>
		<romlist archive="mrt_98">
			<rom type="file" offset="-1">UFMD.COM</rom>
			<rom type="file" offset="-1">UFMD_98.COM</rom>
			<rom type="file" offset="0x10">MRT01.USG</rom>
			<rom type="file" offset="0x11">MRT02.USG</rom>
			<rom type="file" offset="0x12">MRT03.USG</rom>
			<rom type="file" offset="0x13">MRT04.USG</rom>
			<rom type="file" offset="0x14">MRT05.USG</rom>
			<rom type="file" offset="0x15">MRT06.USG</rom>
			<rom type="file" offset="0x16">MRT07.USG</rom>
			<rom type="file" offset="0x17">MRT08.USG</rom>
			<rom type="file" offset="0x18">MRT09.USG</rom>
			<rom type="file" offset="0x19">MRT10.USG</rom>
			<rom type="file" offset="0x1a">MRT11.USG</rom>
			<rom type="file" offset="0x1b">MRT12.USG</rom>
			<rom type="file" offset="0x1c">MRT13.USG</rom>
			<rom type="shell" offset="0">UFMD</rom>
			<rom type="shell" offset="0">UFMD_98</rom>
		</romlist>
		<titlelist>
			<title code="0x10">MRT01.USG</title>
			<title code="0x11">MRT02.USG</title>
			<title code="0x12">MRT03.USG</title>
			<title code="0x13">MRT04.USG</title>
			<title code="0x14">MRT05.USG</title>
			<title code="0x15">MRT06.USG</title>
			<title code="0x16">MRT07.USG</title>
			<title code="0x17">MRT08.USG</title>
			<title code="0x18">MRT09.USG</title>
			<title code="0x19">MRT10.USG</title>
			<title code="0x1a">MRT11.USG</title>
			<title code="0x1b">MRT12.USG</title>
			<title code="0x1c">MRT13.USG</title>
		</titlelist>
	</game>
</gamelist>