<?xml version="1.0" encoding="Shift_JIS"?>
<?xml-stylesheet type="text/xsl" href="hoot.xsl"?>
<!DOCTYPE gamelist [
	<!ELEMENT gamelist (game|bind|childlists)*>
	<!ATTLIST gamelist date CDATA #IMPLIED>
	<!ELEMENT childlists (list)*>
	<!ELEMENT list (#PCDATA)>
	<!ELEMENT bind (exts,driver,options?)>
	<!ELEMENT exts (ext)*>
	<!ELEMENT ext (#PCDATA)>
	<!ELEMENT game (name,driver,driveralias?,options?,romlist?,titlelist?)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT driver (#PCDATA)>
	<!ATTLIST driver type CDATA #IMPLIED>
	<!ELEMENT driveralias (#PCDATA)>
	<!ATTLIST driveralias type CDATA #IMPLIED>
	<!ELEMENT options (option)*>
	<!ELEMENT option EMPTY>
	<!ATTLIST option name CDATA #REQUIRED
					 value CDATA #REQUIRED>
	<!ELEMENT romlist (rom)*>
	<!ATTLIST romlist archive CDATA #IMPLIED>
	<!ELEMENT rom (#PCDATA)>
	<!ATTLIST rom type CDATA #REQUIRED
				  offset CDATA #IMPLIED
				  crc32 CDATA #IMPLIED>
	<!ELEMENT titlelist (title|range)*>
	<!ELEMENT title (#PCDATA)>
	<!ATTLIST title code CDATA #REQUIRED
					type CDATA #IMPLIED>
	<!ELEMENT range (#PCDATA)>
	<!ATTLIST range min CDATA #REQUIRED
					max CDATA #REQUIRED
					extcode CDATA #IMPLIED>
]>
<gamelist date="2005/09/25">
	<!-- //JHV -->
	<game>
		<name>[PC-9801] Atlantia (アトランティア) (YM2203)</name>
		<driver type="opn">pc98dos</driver>
		<driveralias type="PC-9801">Japan Home Video</driveralias>
		<options>
			<option name="funcvect" value="0x7e"/>
			<option name="clockmul" value="8"/>
		</options>
		<romlist archive="atlant_98">
			<rom type="file" offset="-1">PMD_98.COM</rom>
			<rom type="file" offset="-1">PMD.COM</rom>
			<rom type="file" offset="0x10">ATRA_01.M</rom>
			<rom type="file" offset="0x11">ATRA_03.M</rom>
			<rom type="file" offset="0x12">ATRA_04.M</rom>
			<rom type="file" offset="0x13">ATRA_05.M</rom>
			<rom type="file" offset="0x14">ATRA_06.M</rom>
			<rom type="file" offset="0x15">ATRA_07.M</rom>
			<rom type="file" offset="0x16">ATRA_08.M</rom>
			<rom type="file" offset="0x17">ATRA_09.M</rom>
			<rom type="file" offset="0x18">ATRA_10.M</rom>
			<rom type="file" offset="0x19">ATRA_11.M</rom>
			<rom type="file" offset="0x1a">ATRA_12.M</rom>
			<rom type="file" offset="0x1b">ATRA_13.M</rom>
			<rom type="file" offset="0x1c">ATRA_14.M</rom>
			<rom type="file" offset="0x1d">ATRA_15.M</rom>
			<rom type="shell" offset="0">pmd</rom>
			<rom type="shell" offset="0">pmd_98</rom>
		</romlist>
		<titlelist>
			<title code="0x10">ATRA_01.M</title>
			<title code="0x11">ATRA_03.M</title>
			<title code="0x12">ATRA_04.M</title>
			<title code="0x13">ATRA_05.M</title>
			<title code="0x14">ATRA_06.M</title>
			<title code="0x15">ATRA_07.M</title>
			<title code="0x16">ATRA_08.M</title>
			<title code="0x17">ATRA_09.M</title>
			<title code="0x18">ATRA_10.M</title>
			<title code="0x19">ATRA_11.M</title>
			<title code="0x1a">ATRA_12.M</title>
			<title code="0x1b">ATRA_13.M</title>
			<title code="0x1c">ATRA_14.M</title>
			<title code="0x1d">ATRA_15.M</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] Atlantia (アトランティア) (YM2608)</name>
		<driver type="opna">pc98dos</driver>
		<driveralias type="PC-9801">Japan Home Video</driveralias>
		<options>
			<option name="funcvect" value="0x7e"/>
			<option name="clockmul" value="8"/>
		</options>
		<romlist archive="atlant_98">
			<rom type="file" offset="-1">PMD_98.COM</rom>
			<rom type="file" offset="-1">PMDB2.COM</rom>
			<rom type="file" offset="0x10">ATRA_01.M</rom>
			<rom type="file" offset="0x11">ATRA_03.M</rom>
			<rom type="file" offset="0x12">ATRA_04.M</rom>
			<rom type="file" offset="0x13">ATRA_05.M</rom>
			<rom type="file" offset="0x14">ATRA_06.M</rom>
			<rom type="file" offset="0x15">ATRA_07.M</rom>
			<rom type="file" offset="0x16">ATRA_08.M</rom>
			<rom type="file" offset="0x17">ATRA_09.M</rom>
			<rom type="file" offset="0x18">ATRA_10.M</rom>
			<rom type="file" offset="0x19">ATRA_11.M</rom>
			<rom type="file" offset="0x1a">ATRA_12.M</rom>
			<rom type="file" offset="0x1b">ATRA_13.M</rom>
			<rom type="file" offset="0x1c">ATRA_14.M</rom>
			<rom type="file" offset="0x1d">ATRA_15.M</rom>
			<rom type="shell" offset="0">pmdb2</rom>
			<rom type="shell" offset="0">pmd_98</rom>
		</romlist>
		<titlelist>
			<title code="0x10">ATRA_01.M</title>
			<title code="0x11">ATRA_03.M</title>
			<title code="0x12">ATRA_04.M</title>
			<title code="0x13">ATRA_05.M</title>
			<title code="0x14">ATRA_06.M</title>
			<title code="0x15">ATRA_07.M</title>
			<title code="0x16">ATRA_08.M</title>
			<title code="0x17">ATRA_09.M</title>
			<title code="0x18">ATRA_10.M</title>
			<title code="0x19">ATRA_11.M</title>
			<title code="0x1a">ATRA_12.M</title>
			<title code="0x1b">ATRA_13.M</title>
			<title code="0x1c">ATRA_14.M</title>
			<title code="0x1d">ATRA_15.M</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] Desert Dragoon: Sabaku no Ryuukihei (デザートドラグーン ～砂漠の竜騎兵～) (YM2203)</name>
		<driver type="opn">pc98dos</driver>
		<driveralias type="PC-9801">Japan Home Video</driveralias>
		<options>
			<option name="clockmul" value="8"/>
		</options>
		<romlist archive="desertd_98">
			<rom type="file" offset="-1">FP.COM</rom>
			<rom type="file" offset="-1">FP_98.COM</rom>
			<rom type="file" offset="-1">DDM_01.MMD</rom>
			<rom type="file" offset="-1">DDM_02.MMD</rom>
			<rom type="file" offset="-1">DDM_03.MMD</rom>
			<rom type="file" offset="-1">DDM_04.MMD</rom>
			<rom type="file" offset="-1">DDM_05.MMD</rom>
			<rom type="file" offset="-1">DDM_06.MMD</rom>
			<rom type="file" offset="-1">DDM_07.MMD</rom>
			<rom type="file" offset="-1">DDM_08.MMD</rom>
			<rom type="file" offset="-1">DDM_09.MMD</rom>
			<rom type="file" offset="-1">DDM_10.MMD</rom>
			<rom type="file" offset="-1">DDM_11.MMD</rom>
			<rom type="file" offset="-1">DDM_12.MMD</rom>
			<rom type="file" offset="-1">DDM_13.MMD</rom>
			<rom type="file" offset="-1">DDM_14.MMD</rom>
			<rom type="file" offset="-1">DDM_15.MMD</rom>
			<rom type="file" offset="-1">DDM_16.MMD</rom>
			<rom type="conin" offset="0x10">DDM_01.MMD</rom>
			<rom type="conin" offset="0x11">DDM_02.MMD</rom>
			<rom type="conin" offset="0x12">DDM_03.MMD</rom>
			<rom type="conin" offset="0x13">DDM_04.MMD</rom>
			<rom type="conin" offset="0x14">DDM_05.MMD</rom>
			<rom type="conin" offset="0x15">DDM_06.MMD</rom>
			<rom type="conin" offset="0x16">DDM_07.MMD</rom>
			<rom type="conin" offset="0x17">DDM_08.MMD</rom>
			<rom type="conin" offset="0x18">DDM_09.MMD</rom>
			<rom type="conin" offset="0x19">DDM_10.MMD</rom>
			<rom type="conin" offset="0x1a">DDM_11.MMD</rom>
			<rom type="conin" offset="0x1b">DDM_12.MMD</rom>
			<rom type="conin" offset="0x1c">DDM_13.MMD</rom>
			<rom type="conin" offset="0x1d">DDM_14.MMD</rom>
			<rom type="conin" offset="0x1e">DDM_15.MMD</rom>
			<rom type="conin" offset="0x1f">DDM_16.MMD</rom>
			<rom type="shell" offset="0">FP</rom>
			<rom type="shell" offset="0">FP_98</rom>
		</romlist>
		<titlelist>
			<title code="0x10">プロローグ ～ 伝説の竜騎兵</title>
			<title code="0x11">遙かなる慟哭</title>
			<title code="0x12">Warning Mission</title>
			<title code="0x13">ビジュアル シーン</title>
			<title code="0x14">激突!!</title>
			<title code="0x15">Lock On</title>
			<title code="0x16">Desert Dragoon</title>
			<title code="0x17">中央の驚異</title>
			<title code="0x18">Gate Tower</title>
			<title code="0x19">戦士の牙</title>
			<title code="0x1a">Mission Complete</title>
			<title code="0x1b">敗北</title>
			<title code="0x1c">砂塵の果てに</title>
			<title code="0x1d">惑星 ネイロビ</title>
			<title code="0x1e">Level Up!!</title>
			<title code="0x1f">Just A Moment</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] Sotsugyou: Graduation (卒業 －グラデュエーション－) (YM2203)</name>
		<driver type="opn">pc98dos</driver>
		<driveralias type="PC-9801">Japan Home Video</driveralias>
		<options>
			<option name="clockmul" value="8"/>
		</options>
		<romlist archive="sotugyo_98">
			<rom type="file" offset="-1">MUSIC.COM</rom>
			<rom type="file" offset="-1">MUSIC68.COM</rom>
			<rom type="file" offset="0x10">AKI.MLO</rom>
			<rom type="file" offset="0x11">ARI_KI.MLO</rom>
			<rom type="file" offset="0x12">BELL.MLO</rom>
			<rom type="file" offset="0x13">DON.MLO</rom>
			<rom type="file" offset="0x14">FANFAR.MLO</rom>
			<rom type="file" offset="0x15">FUYU.MLO</rom>
			<rom type="file" offset="0x16">GEKI.MLO</rom>
			<rom type="file" offset="0x17">HARU2.MLO</rom>
			<rom type="file" offset="0x18">HARU3.MLO</rom>
			<rom type="file" offset="0x19">HEIJYOU.MLO</rom>
			<rom type="file" offset="0x1a">HYOUSHOU.MLO</rom>
			<rom type="file" offset="0x1b">IROKE.MLO</rom>
			<rom type="file" offset="0x1c">KANASIMI.MLO</rom>
			<rom type="file" offset="0x1d">KOUKA_2.MLO</rom>
			<rom type="file" offset="0x1e">MITO.MLO</rom>
			<rom type="file" offset="0x1f">MOMO.MLO</rom>
			<rom type="file" offset="0x20">NATU1.MLO</rom>
			<rom type="file" offset="0x21">NATU2.MLO</rom>
			<rom type="file" offset="0x22">OCHI_5.MLO</rom>
			<rom type="file" offset="0x23">OCHI_6.MLO</rom>
			<rom type="file" offset="0x24">OPENI1.MLO</rom>
			<rom type="file" offset="0x25">OZ.MLO</rom>
			<rom type="file" offset="0x26">PON.MLO</rom>
			<rom type="file" offset="0x27">SE_2.MLO</rom>
			<rom type="file" offset="0x28">SE_3.MLO</rom>
			<rom type="file" offset="0x29">SE_4.MLO</rom>
			<rom type="file" offset="0x2a">SIRAYUKI.MLO</rom>
			<rom type="file" offset="0x2b">START.MLO</rom>
			<rom type="file" offset="0x2c">UNDOU.MLO</rom>
			<rom type="file" offset="0x2d">UNDOU2.MLO</rom>
			<rom type="shell" offset="0">MUSIC</rom>
			<rom type="shell" offset="0">MUSIC68</rom>
		</romlist>
		<titlelist>
			<title code="0x12">ベル</title>
			<title code="0x2b">スタート</title>
			<title code="0x19">平常</title>
			<title code="0x17">春2</title>
			<title code="0x18">春3</title>
			<title code="0x20">夏1</title>
			<title code="0x21">夏2</title>
			<title code="0x10">秋</title>
			<title code="0x15">冬</title>
			<title code="0x1c">悲しみ</title>
			<title code="0x1b">色気</title>
			<title code="0x2c">運動会1</title>
			<title code="0x2d">運動会2</title>
			<title code="0x16">劇</title>
			<title code="0x1f">桃太郎</title>
			<title code="0x25">オズの魔法使い</title>
			<title code="0x11">アリとキリギリス</title>
			<title code="0x2a">白雪姫</title>
			<title code="0x1e">水戸黄門</title>
			<title code="0x1a">表彰</title>
			<title code="0x1d">校歌</title>
			<title code="0x13">よーいドン！</title>
			<title code="0x14">ファンファーレ</title>
			<title code="0x22">オチ5</title>
			<title code="0x23">オチ6</title>
			<title code="0x26">ポン</title>
			<title code="0x24">OPENI1.MLO</title>
			<title code="0x27">SE_2.MLO</title>
			<title code="0x28">SE_3.MLO</title>
			<title code="0x29">SE_4.MLO</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] Sotsugyou 2: Neo Generation (卒業II -ネオ・ジェネレーション-) (YM2203)</name>
		<driver type="opn">pc98dos</driver>
		<driveralias type="PC-9801">Japan Home Video</driveralias>
		<options>
			<option name="clockmul" value="8"/>
		</options>
		<romlist archive="sotugyo2_98">
			<rom type="file" offset="-1">MUSIC.COM</rom>
			<rom type="file" offset="-1">MUSIC70.COM</rom>
			<rom type="file" offset="0x10">SO201.MDB</rom>
			<rom type="file" offset="0x11">SO202.MDB</rom>
			<rom type="file" offset="0x12">SO203.MDB</rom>
			<rom type="file" offset="0x13">SO204.MDB</rom>
			<rom type="file" offset="0x14">SO205.MDB</rom>
			<rom type="file" offset="0x15">SO206.MDB</rom>
			<rom type="file" offset="0x16">SO207.MDB</rom>
			<rom type="file" offset="0x17">SO208.MDB</rom>
			<rom type="file" offset="0x18">SO209.MDB</rom>
			<rom type="file" offset="0x19">SO210.MDB</rom>
			<rom type="file" offset="0x1a">SO211.MDB</rom>
			<rom type="file" offset="0x1b">SO212.MDB</rom>
			<rom type="file" offset="0x1c">SO213.MDB</rom>
			<rom type="file" offset="0x1d">SO214.MDB</rom>
			<rom type="file" offset="0x1e">SO215.MDB</rom>
			<rom type="file" offset="0x1f">SO216.MDB</rom>
			<rom type="file" offset="0x20">SO217.MDB</rom>
			<rom type="file" offset="0x21">SO218.MDB</rom>
			<rom type="file" offset="0x22">SO219.MDB</rom>
			<rom type="file" offset="0x23">SO220.MDB</rom>
			<rom type="file" offset="0x24">SO221.MDB</rom>
			<rom type="file" offset="0x25">SO222.MDB</rom>
			<rom type="file" offset="0x26">SO223.MDB</rom>
			<rom type="file" offset="0x27">SO224.MDB</rom>
			<rom type="file" offset="0x28">SO225.MDB</rom>
			<rom type="file" offset="0x29">SO226.MDB</rom>
			<rom type="file" offset="0x2a">SO227.MDB</rom>
			<rom type="file" offset="0x2b">SO228.MDB</rom>
			<rom type="file" offset="0x2c">SO229.MDB</rom>
			<rom type="file" offset="0x2d">SO230.MDB</rom>
			<rom type="file" offset="0x2e">SO231.MDB</rom>
			<rom type="file" offset="0x2f">SO232.MDB</rom>
			<rom type="file" offset="0x30">SO233.MDB</rom>
			<rom type="file" offset="0x31">SO234.MDB</rom>
			<rom type="file" offset="0x32">SO236.MDB</rom>
			<rom type="file" offset="0x33">SO237.MDB</rom>
			<rom type="file" offset="0x34">SO238.MDB</rom>
			<rom type="file" offset="0x35">SO239.MDB</rom>
			<rom type="file" offset="0x36">SO241.MDB</rom>
			<rom type="file" offset="0x37">SO242.MDB</rom>
			<rom type="file" offset="0x38">SO243.MDB</rom>
			<rom type="file" offset="0x39">SO244.MDB</rom>
			<rom type="shell" offset="0">MUSIC</rom>
			<rom type="shell" offset="0">MUSIC70</rom>
		</romlist>
		<titlelist>
			<title code="0x10">卒業攻略法</title>
			<title code="0x11">授業前のひととき</title>
			<title code="0x12">出会いの春</title>
			<title code="0x13">思い出の夏</title>
			<title code="0x14">哀愁の秋</title>
			<title code="0x15">別れの冬</title>
			<title code="0x16">出会いの春2</title>
			<title code="0x17">思い出の夏2</title>
			<title code="0x18">哀愁の秋2</title>
			<title code="0x19">別れの冬2</title>
			<title code="0x1a">夏期講習</title>
			<title code="0x1b">臨海教室</title>
			<title code="0x1c">職員室</title>
			<title code="0x1d">石橋美佐子のテーマ</title>
			<title code="0x1e">犬塚さおりのテーマ</title>
			<title code="0x1f">シンディ桜井のテーマ</title>
			<title code="0x20">谷由利佳のテーマ</title>
			<title code="0x21">安田舞奈のテーマ</title>
			<title code="0x22">運動会開始</title>
			<title code="0x23">騎馬戦</title>
			<title code="0x24">勝利のファンファーレ</title>
			<title code="0x25">敗北</title>
			<title code="0x26">ロミオとジュリエット</title>
			<title code="0x27">不思議な国のアリス</title>
			<title code="0x28">西遊記</title>
			<title code="0x29">美少女戦隊セーラーズ</title>
			<title code="0x2a">茶室</title>
			<title code="0x2b">喫茶店</title>
			<title code="0x2c">お化け屋敷</title>
			<title code="0x2d">演技中</title>
			<title code="0x2e">オチ・ずっこけ</title>
			<title code="0x2f">不良行為発覚</title>
			<title code="0x30">全過程終了</title>
			<title code="0x31">別れ</title>
			<title code="0x32">試験中</title>
			<title code="0x33">ウィークエンド</title>
			<title code="0x34">全員退学</title>
			<title code="0x35">スタッフロール</title>
			<title code="0x36">ファンファーレ(ショート)</title>
			<title code="0x37">欠番?</title>
			<title code="0x38">不良行為発覚</title>
			<title code="0x39">SO244.MDB</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-9801] Aggregate (アグレガード) (YM2203)</name>
		<driver type="opn">pc98dos</driver>
		<driveralias type="PC-9801">Japan Home Video</driveralias>
		<options>
			<option name="clockmul" value="8"/>
		</options>
		<romlist archive="agregate_98">
			<rom type="file" offset="-1">SSD_98.COM</rom>
			<rom type="file" offset="-1">SSDRV.EXE</rom>
			<rom type="file" offset="-1">SE.BIN</rom>
			<rom type="file" offset="0x10">SYSTEM.109</rom>
			<rom type="file" offset="0x11">SYSTEM.110</rom>
			<rom type="file" offset="0x12">SYSTEM.111</rom>
			<rom type="file" offset="0x13">SYSTEM.112</rom>
			<rom type="file" offset="0x14">SYSTEM.113</rom>
			<rom type="file" offset="0x15">SYSTEM.114</rom>
			<rom type="file" offset="0x16">SYSTEM.115</rom>
			<rom type="file" offset="0x17">SYSTEM.116</rom>
			<rom type="file" offset="0x18">SYSTEM.117</rom>
			<rom type="file" offset="0x19">SYSTEM.118</rom>
			<rom type="file" offset="0x1a">SYSTEM.119</rom>
			<rom type="file" offset="0x1b">SYSTEM.120</rom>
			<rom type="file" offset="0x1c">SYSTEM.121</rom>
			<rom type="file" offset="0x1d">SYSTEM.122</rom>
			<rom type="shell" offset="0">ssdrv</rom>
			<rom type="shell" offset="0">ssd_98</rom>
		</romlist>
		<titlelist>
			<title code="0x10">SYSTEM.109</title>
			<title code="0x11">SYSTEM.110</title>
			<title code="0x12">SYSTEM.111</title>
			<title code="0x13">SYSTEM.112</title>
			<title code="0x14">SYSTEM.113</title>
			<title code="0x15">SYSTEM.114</title>
			<title code="0x16">SYSTEM.115</title>
			<title code="0x17">SYSTEM.116</title>
			<title code="0x18">SYSTEM.117</title>
			<title code="0x19">SYSTEM.118</title>
			<title code="0x1a">SYSTEM.119</title>
			<title code="0x1b">SYSTEM.120</title>
			<title code="0x1c">SYSTEM.121</title>
			<title code="0x1d">SYSTEM.122</title>
		</titlelist>
	</game>
	<game>
		<name>[X68000] Sotsugyou: Graduation (卒業 －グラデュエーション－) (YM2151+MSM6258)</name>
		<driver type="generic">x68k</driver>
		<driveralias type="X68000">Japan Home Video</driveralias>
		<options>
			<option name="mfp" value="0x01"/>
			<option name="opm_mix" value="0x100"/>
		</options>
		<romlist archive="sotugyo68snd">
			<rom type="code" offset="0x000000">sotu68snd.bin</rom>
			<rom type="code" offset="0x010000">F_SNDSET.ZMD</rom>
			<rom type="code" offset="0x011000">F_AKI.ZMD</rom>
			<rom type="code" offset="0x012000">F_ARI&amp;KI.ZMD</rom>
			<rom type="code" offset="0x013000">F_BELL.ZMD</rom>
			<rom type="code" offset="0x014000">F_DON.ZMD</rom>
			<rom type="code" offset="0x015000">F_FANFAR.ZMD</rom>
			<rom type="code" offset="0x016000">F_FUYU.ZMD</rom>
			<rom type="code" offset="0x017000">F_GEKI.ZMD</rom>
			<rom type="code" offset="0x018000">F_HARU2.ZMD</rom>
			<rom type="code" offset="0x019000">F_HARU3.ZMD</rom>
			<rom type="code" offset="0x01a000">F_HEIJYO.ZMD</rom>
			<rom type="code" offset="0x01b000">F_HYOSHO.ZMD</rom>
			<rom type="code" offset="0x01c000">F_IROKE.ZMD</rom>
			<rom type="code" offset="0x01d000">F_KANASI.ZMD</rom>
			<rom type="code" offset="0x01e000">F_KOUKA2.ZMD</rom>
			<rom type="code" offset="0x01f000">F_MITO.ZMD</rom>
			<rom type="code" offset="0x020000">F_MOMO.ZMD</rom>
			<rom type="code" offset="0x021000">F_NATU1.ZMD</rom>
			<rom type="code" offset="0x022000">F_NATU2.ZMD</rom>
			<rom type="code" offset="0x023000">F_OCHI_5.ZMD</rom>
			<rom type="code" offset="0x024000">F_OCHI_6.ZMD</rom>
			<rom type="code" offset="0x025000">F_OPENI1.ZMD</rom>
			<rom type="code" offset="0x026000">F_OZ.ZMD</rom>
			<rom type="code" offset="0x027000">F_PON.ZMD</rom>
			<rom type="code" offset="0x028000">F_SE_2.ZMD</rom>
			<rom type="code" offset="0x029000">F_SE_3.ZMD</rom>
			<rom type="code" offset="0x02a000">F_SE_4.ZMD</rom>
			<rom type="code" offset="0x02b000">F_SIRAYU.ZMD</rom>
			<rom type="code" offset="0x02c000">F_START.ZMD</rom>
			<rom type="code" offset="0x02d000">F_UNDOU.ZMD</rom>
			<rom type="code" offset="0x02e000">F_UNDOU2.ZMD</rom>
			<rom type="x"    offset="0x050000">ZMSC.X</rom>
		</romlist>
		<titlelist>
			<title code="0x03">ベル</title>
			<title code="0x1c">スタート</title>
			<title code="0x0a">平常</title>
			<title code="0x08">春1</title>
			<title code="0x09">春2</title>
			<title code="0x11">夏1</title>
			<title code="0x12">夏2</title>
			<title code="0x01">秋</title>
			<title code="0x06">冬</title>
			<title code="0x0d">悲しみ</title>
			<title code="0x1d">運動会1</title>
			<title code="0x1e">運動会2</title>
			<title code="0x07">劇</title>
			<title code="0x10">桃太郎</title>
			<title code="0x16">オズの魔法使い</title>
			<title code="0x02">アリとキリギリス</title>
			<title code="0x1b">白雪姫</title>
			<title code="0x0f">水戸黄門</title>
			<title code="0x0b">表彰</title>
			<title code="0x0e">校歌</title>
			<!--
			<title code="0x15">オープニング(未使用)</title>
			<title code="0x0c">色気(未使用)</title>
			  -->
			<title code="0x04">よーいドン!</title>
			<title code="0x05">ファンファーレ</title>
			<title code="0x13">オチ1</title>
			<title code="0x14">オチ2</title>
			<title code="0x17">ポン</title>
			<title code="0x18">F_SE_2.ZMD</title>
			<title code="0x19">F_SE_3.ZMD</title>
			<title code="0x1a">F_SE_4.ZMD</title>
		</titlelist>
	</game>
	<game>
		<name>[X68000] Sotsugyou: Graduation (卒業 －グラデュエーション－) (GS)</name>
		<driver type="generic">x68k</driver>
		<driveralias type="X68000">Japan Home Video</driveralias>
		<options>
			<option name="mfp" value="0x01"/>
			<option name="midiout" value="1"/>
			<option name="midiout_type" value="4"/>
		</options>
		<romlist archive="sotugyo68snd">
			<rom type="code" offset="0x000000">sotu68snd.bin</rom>
			<rom type="code" offset="0x010000">M_SNDSET.ZMD</rom>
			<rom type="code" offset="0x011000">M_AKI.ZMD</rom>
			<rom type="code" offset="0x012000">M_ARI&amp;KI.ZMD</rom>
			<rom type="code" offset="0x013000">M_BELL.ZMD</rom>
			<rom type="code" offset="0x014000">M_DON.ZMD</rom>
			<rom type="code" offset="0x015000">M_FANFAR.ZMD</rom>
			<rom type="code" offset="0x016000">M_FUYU.ZMD</rom>
			<rom type="code" offset="0x017000">M_GEKI.ZMD</rom>
			<rom type="code" offset="0x018000">M_HARU2.ZMD</rom>
			<rom type="code" offset="0x019000">M_HARU3.ZMD</rom>
			<rom type="code" offset="0x01a000">M_HEIJYO.ZMD</rom>
			<rom type="code" offset="0x01b000">M_HYOSHO.ZMD</rom>
			<rom type="code" offset="0x01c000">M_IROKE.ZMD</rom>
			<rom type="code" offset="0x01d000">M_KANASI.ZMD</rom>
			<rom type="code" offset="0x01e000">M_KOUKA2.ZMD</rom>
			<rom type="code" offset="0x01f000">M_MITO.ZMD</rom>
			<rom type="code" offset="0x020000">M_MOMO.ZMD</rom>
			<rom type="code" offset="0x021000">M_NATU1.ZMD</rom>
			<rom type="code" offset="0x023000">M_NATU2.ZMD</rom>
			<rom type="code" offset="0x024000">M_OCHI_5.ZMD</rom>
			<rom type="code" offset="0x025000">M_OCHI_6.ZMD</rom>
			<rom type="code" offset="0x026000">M_OPEN1.ZMD</rom>
			<rom type="code" offset="0x027000">M_OZ.ZMD</rom>
			<rom type="code" offset="0x028000">M_PON.ZMD</rom>
			<rom type="code" offset="0x029000">M_SE_2.ZMD</rom>
			<rom type="code" offset="0x02a000">M_SE_3.ZMD</rom>
			<rom type="code" offset="0x02b000">M_SE_4.ZMD</rom>
			<rom type="code" offset="0x02c000">M_SIRAYU.ZMD</rom>
			<rom type="code" offset="0x02d000">M_START.ZMD</rom>
			<rom type="code" offset="0x02e000">M_UNDOU.ZMD</rom>
			<rom type="code" offset="0x030000">M_UNDOU2.ZMD</rom>
			<rom type="x"    offset="0x050000">ZMSC.X</rom>
		</romlist>
		<titlelist>
			<title code="0x03">ベル</title>
			<title code="0x1d">スタート</title>
			<title code="0x0a">平常</title>
			<title code="0x08">春1</title>
			<title code="0x09">春2</title>
			<title code="0x11">夏1</title>
			<title code="0x13">夏2</title>
			<title code="0x01">秋</title>
			<title code="0x06">冬</title>
			<title code="0x0d">悲しみ</title>
			<title code="0x1e">運動会1</title>
			<title code="0x20">運動会2</title>
			<title code="0x07">劇</title>
			<title code="0x10">桃太郎</title>
			<title code="0x17">オズの魔法使い</title>
			<title code="0x02">アリとキリギリス</title>
			<title code="0x1c">白雪姫</title>
			<title code="0x0f">水戸黄門</title>
			<title code="0x0b">表彰</title>
			<title code="0x0e">校歌</title>
			<title code="0x16">オープニング(未使用)</title>
			<title code="0x0c">色気(未使用)</title>
			<title code="0x04">M_DON.ZMD</title>
			<title code="0x05">M_FANFAR.ZMD</title>
			<title code="0x18">M_PON.ZMD</title>
			<title code="0x14">M_OCHI_5.ZMD</title>
			<title code="0x15">M_OCHI_6.ZMD</title>
			<title code="0x19">M_SE_2.ZMD</title>
			<title code="0x1a">M_SE_3.ZMD</title>
			<title code="0x1b">M_SE_4.ZMD</title>
		</titlelist>
	</game>
	<game>
		<name>[X68000] Sotsugyou: Graduation (卒業 －グラデュエーション－) (Vermouth, Gravis Ultrasound simulation)</name>
		<driver type="generic">x68k</driver>
		<driveralias type="X68000">Japan Home Video</driveralias>
		<options>
			<option name="mfp" value="0x01"/>
			<option name="midiout" value="1"/>
			<option name="midiout_type" value="6"/>
		</options>
		<romlist archive="sotugyo68snd">
			<rom type="code" offset="0x000000">sotu68snd.bin</rom>
			<rom type="code" offset="0x010000">M_SNDSET.ZMD</rom>
			<rom type="code" offset="0x011000">M_AKI.ZMD</rom>
			<rom type="code" offset="0x012000">M_ARI&amp;KI.ZMD</rom>
			<rom type="code" offset="0x013000">M_BELL.ZMD</rom>
			<rom type="code" offset="0x014000">M_DON.ZMD</rom>
			<rom type="code" offset="0x015000">M_FANFAR.ZMD</rom>
			<rom type="code" offset="0x016000">M_FUYU.ZMD</rom>
			<rom type="code" offset="0x017000">M_GEKI.ZMD</rom>
			<rom type="code" offset="0x018000">M_HARU2.ZMD</rom>
			<rom type="code" offset="0x019000">M_HARU3.ZMD</rom>
			<rom type="code" offset="0x01a000">M_HEIJYO.ZMD</rom>
			<rom type="code" offset="0x01b000">M_HYOSHO.ZMD</rom>
			<rom type="code" offset="0x01c000">M_IROKE.ZMD</rom>
			<rom type="code" offset="0x01d000">M_KANASI.ZMD</rom>
			<rom type="code" offset="0x01e000">M_KOUKA2.ZMD</rom>
			<rom type="code" offset="0x01f000">M_MITO.ZMD</rom>
			<rom type="code" offset="0x020000">M_MOMO.ZMD</rom>
			<rom type="code" offset="0x021000">M_NATU1.ZMD</rom>
			<rom type="code" offset="0x023000">M_NATU2.ZMD</rom>
			<rom type="code" offset="0x024000">M_OCHI_5.ZMD</rom>
			<rom type="code" offset="0x025000">M_OCHI_6.ZMD</rom>
			<rom type="code" offset="0x026000">M_OPEN1.ZMD</rom>
			<rom type="code" offset="0x027000">M_OZ.ZMD</rom>
			<rom type="code" offset="0x028000">M_PON.ZMD</rom>
			<rom type="code" offset="0x029000">M_SE_2.ZMD</rom>
			<rom type="code" offset="0x02a000">M_SE_3.ZMD</rom>
			<rom type="code" offset="0x02b000">M_SE_4.ZMD</rom>
			<rom type="code" offset="0x02c000">M_SIRAYU.ZMD</rom>
			<rom type="code" offset="0x02d000">M_START.ZMD</rom>
			<rom type="code" offset="0x02e000">M_UNDOU.ZMD</rom>
			<rom type="code" offset="0x030000">M_UNDOU2.ZMD</rom>
			<rom type="x"    offset="0x050000">ZMSC.X</rom>
		</romlist>
		<titlelist>
			<title code="0x03">ベル</title>
			<title code="0x1d">スタート</title>
			<title code="0x0a">平常</title>
			<title code="0x08">春1</title>
			<title code="0x09">春2</title>
			<title code="0x11">夏1</title>
			<title code="0x13">夏2</title>
			<title code="0x01">秋</title>
			<title code="0x06">冬</title>
			<title code="0x0d">悲しみ</title>
			<title code="0x1e">運動会1</title>
			<title code="0x20">運動会2</title>
			<title code="0x07">劇</title>
			<title code="0x10">桃太郎</title>
			<title code="0x17">オズの魔法使い</title>
			<title code="0x02">アリとキリギリス</title>
			<title code="0x1c">白雪姫</title>
			<title code="0x0f">水戸黄門</title>
			<title code="0x0b">表彰</title>
			<title code="0x0e">校歌</title>
			<title code="0x16">オープニング(未使用)</title>
			<title code="0x0c">色気(未使用)</title>
			<title code="0x04">M_DON.ZMD</title>
			<title code="0x05">M_FANFAR.ZMD</title>
			<title code="0x18">M_PON.ZMD</title>
			<title code="0x14">M_OCHI_5.ZMD</title>
			<title code="0x15">M_OCHI_6.ZMD</title>
			<title code="0x19">M_SE_2.ZMD</title>
			<title code="0x1a">M_SE_3.ZMD</title>
			<title code="0x1b">M_SE_4.ZMD</title>
		</titlelist>
	</game>
</gamelist>