<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="hoot.xsl"?>
<!DOCTYPE gamelist [
	<!ELEMENT gamelist (game|bind|childlists)*>
	<!ATTLIST gamelist date CDATA #IMPLIED>
	<!ELEMENT childlists (list)*>
	<!ELEMENT list (#PCDATA)>
	<!ELEMENT bind (exts,driver,options?)>
	<!ELEMENT exts (ext)*>
	<!ELEMENT ext (#PCDATA)>
	<!ELEMENT game (name,driver,driveralias?,options?,romlist?,titlelist?)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT driver (#PCDATA)>
	<!ATTLIST driver type CDATA #IMPLIED>
	<!ELEMENT driveralias (#PCDATA)>
	<!ATTLIST driveralias type CDATA #IMPLIED>
	<!ELEMENT options (option)*>
	<!ELEMENT option EMPTY>
	<!ATTLIST option name CDATA #REQUIRED
					 value CDATA #REQUIRED>
	<!ELEMENT romlist (rom)*>
	<!ATTLIST romlist archive CDATA #IMPLIED>
	<!ELEMENT rom (#PCDATA)>
	<!ATTLIST rom type CDATA #REQUIRED
				  offset CDATA #IMPLIED
				  crc32 CDATA #IMPLIED>
	<!ELEMENT titlelist (title|range)*>
	<!ELEMENT title (#PCDATA)>
	<!ATTLIST title code CDATA #REQUIRED
					type CDATA #IMPLIED>
	<!ELEMENT range (#PCDATA)>
	<!ATTLIST range min CDATA #REQUIRED
					max CDATA #REQUIRED
					extcode CDATA #IMPLIED
					start CDATA #IMPLIED>

]>
<gamelist date="2005/09/25">
	<!-- //Sierra On-Line -->
	<game>
		<name>[PC/AT] Police Quest 2: The Vengeance (SN76496)</name>
		<driver type="tandy">pcatdos</driver>
		<driveralias type="PC/AT">Sierra On-Line</driveralias>
		<options>
			<option name="clockmul" value="0x05"/>
		</options>
		<romlist archive="pq2_at">
			<rom type="file" offset="-1">silp_at.com</rom>
			<rom type="file" offset="0x08">JR.DRV</rom>
			<rom type="file" offset="0x10">Sound.001</rom>
			<rom type="file" offset="0x11">Sound.002</rom>
			<rom type="file" offset="0x12">Sound.003</rom>
			<rom type="file" offset="0x13">Sound.004</rom>
			<rom type="file" offset="0x14">Sound.005</rom>
			<rom type="file" offset="0x15">Sound.006</rom>
			<rom type="file" offset="0x16">Sound.007</rom>
			<rom type="file" offset="0x17">Sound.008</rom>
			<rom type="file" offset="0x18">Sound.009</rom>
			<rom type="file" offset="0x19">Sound.010</rom>
			<rom type="file" offset="0x1A">Sound.011</rom>
			<rom type="file" offset="0x1B">Sound.012</rom>
			<rom type="file" offset="0x1C">Sound.013</rom>
			<rom type="file" offset="0x1D">Sound.014</rom>
			<rom type="file" offset="0x1E">Sound.015</rom>
			<rom type="file" offset="0x1F">Sound.016</rom>
			<rom type="file" offset="0x20">Sound.017</rom>
			<rom type="file" offset="0x21">Sound.018</rom>
			<rom type="file" offset="0x22">Sound.019</rom>
			<rom type="file" offset="0x23">Sound.020</rom>
			<rom type="file" offset="0x24">Sound.021</rom>
			<rom type="file" offset="0x25">Sound.022</rom>
			<rom type="file" offset="0x26">Sound.023</rom>
			<rom type="file" offset="0x27">Sound.024</rom>
			<rom type="file" offset="0x28">Sound.025</rom>
			<rom type="file" offset="0x29">Sound.026</rom>
			<rom type="file" offset="0x2A">Sound.027</rom>
			<rom type="file" offset="0x2B">Sound.028</rom>
			<rom type="file" offset="0x2C">Sound.029</rom>
			<rom type="file" offset="0x2D">Sound.030</rom>
			<rom type="file" offset="0x2E">Sound.032</rom>
			<rom type="file" offset="0x2F">Sound.033</rom>
			<rom type="file" offset="0x30">Sound.035</rom>
			<rom type="file" offset="0x31">Sound.036</rom>
			<rom type="file" offset="0x32">Sound.037</rom>
			<rom type="file" offset="0x33">Sound.038</rom>
			<rom type="file" offset="0x34">Sound.039</rom>
			<rom type="file" offset="0x35">Sound.040</rom>
			<rom type="file" offset="0x36">Sound.041</rom>
			<rom type="file" offset="0x37">Sound.042</rom>
			<rom type="file" offset="0x38">Sound.043</rom>
			<rom type="file" offset="0x39">Sound.044</rom>
			<rom type="file" offset="0x3A">Sound.045</rom>
			<rom type="file" offset="0x3B">Sound.046</rom>
			<rom type="file" offset="0x3C">Sound.047</rom>
			<rom type="file" offset="0x3D">Sound.048</rom>
			<rom type="file" offset="0x3E">Sound.049</rom>
			<rom type="shell" offset="0">silp_at</rom>
		</romlist>
		<titlelist>
			<title code="0x10">Sound.001</title>
			<title code="0x11">Sound.002</title>
			<title code="0x12">Sound.003</title>
			<title code="0x13">Sound.004</title>
			<title code="0x14">Sound.005</title>
			<title code="0x15">Sound.006</title>
			<title code="0x16">Sound.007</title>
			<title code="0x17">Sound.008</title>
			<title code="0x18">Sound.009</title>
			<title code="0x19">Sound.010</title>
			<title code="0x1A">Sound.011</title>
			<title code="0x1B">Sound.012</title>
			<title code="0x1C">Sound.013</title>
			<title code="0x1D">Sound.014</title>
			<title code="0x1E">Sound.015</title>
			<title code="0x1F">Sound.016</title>
			<title code="0x20">Sound.017</title>
			<title code="0x21">Sound.018</title>
			<title code="0x22">Sound.019</title>
			<title code="0x23">Sound.020</title>
			<title code="0x24">Sound.021</title>
			<title code="0x25">Sound.022</title>
			<title code="0x26">Sound.023</title>
			<title code="0x27">Sound.024</title>
			<title code="0x2A">Sound.027</title>
			<title code="0x2B">Sound.028</title>
			<title code="0x2C">Sound.029</title>
			<title code="0x2E">Sound.032</title>
			<title code="0x2F">Sound.033</title>
			<title code="0x30">Sound.035</title>
			<title code="0x31">Sound.036</title>
			<title code="0x35">Sound.040</title>
			<title code="0x3C">Sound.047</title>
			<title code="0x3D">Sound.048</title>
			<title code="0x3E">Sound.049</title>
		</titlelist>
	</game>
	<game>
		<name>[PC/AT] Police Quest 2: The Vengeance (YM3812)</name>
		<driver type="adlib">pcatdos</driver>
		<driveralias type="PC/AT">Sierra On-Line</driveralias>
		<options>
			<option name="clockmul" value="0x05"/>
			<option name="opl2_mix" value="0x100"/>
		</options>
		<romlist archive="pq2_at">
			<rom type="file" offset="-1">silp_at.com</rom>
			<rom type="file" offset="0x08">ADL.DRV</rom>
			<rom type="file" offset="0x09">Patch.003</rom>
			<rom type="file" offset="0x10">Sound.001</rom>
			<rom type="file" offset="0x11">Sound.002</rom>
			<rom type="file" offset="0x12">Sound.003</rom>
			<rom type="file" offset="0x13">Sound.004</rom>
			<rom type="file" offset="0x14">Sound.005</rom>
			<rom type="file" offset="0x15">Sound.006</rom>
			<rom type="file" offset="0x16">Sound.007</rom>
			<rom type="file" offset="0x17">Sound.008</rom>
			<rom type="file" offset="0x18">Sound.009</rom>
			<rom type="file" offset="0x19">Sound.010</rom>
			<rom type="file" offset="0x1A">Sound.011</rom>
			<rom type="file" offset="0x1B">Sound.012</rom>
			<rom type="file" offset="0x1C">Sound.013</rom>
			<rom type="file" offset="0x1D">Sound.014</rom>
			<rom type="file" offset="0x1E">Sound.015</rom>
			<rom type="file" offset="0x1F">Sound.016</rom>
			<rom type="file" offset="0x20">Sound.017</rom>
			<rom type="file" offset="0x21">Sound.018</rom>
			<rom type="file" offset="0x22">Sound.019</rom>
			<rom type="file" offset="0x23">Sound.020</rom>
			<rom type="file" offset="0x24">Sound.021</rom>
			<rom type="file" offset="0x25">Sound.022</rom>
			<rom type="file" offset="0x26">Sound.023</rom>
			<rom type="file" offset="0x27">Sound.024</rom>
			<rom type="file" offset="0x28">Sound.025</rom>
			<rom type="file" offset="0x29">Sound.026</rom>
			<rom type="file" offset="0x2A">Sound.027</rom>
			<rom type="file" offset="0x2B">Sound.028</rom>
			<rom type="file" offset="0x2C">Sound.029</rom>
			<rom type="file" offset="0x2D">Sound.030</rom>
			<rom type="file" offset="0x2E">Sound.032</rom>
			<rom type="file" offset="0x2F">Sound.033</rom>
			<rom type="file" offset="0x30">Sound.035</rom>
			<rom type="file" offset="0x31">Sound.036</rom>
			<rom type="file" offset="0x32">Sound.037</rom>
			<rom type="file" offset="0x33">Sound.038</rom>
			<rom type="file" offset="0x34">Sound.039</rom>
			<rom type="file" offset="0x35">Sound.040</rom>
			<rom type="file" offset="0x36">Sound.041</rom>
			<rom type="file" offset="0x37">Sound.042</rom>
			<rom type="file" offset="0x38">Sound.043</rom>
			<rom type="file" offset="0x39">Sound.044</rom>
			<rom type="file" offset="0x3A">Sound.045</rom>
			<rom type="file" offset="0x3B">Sound.046</rom>
			<rom type="file" offset="0x3C">Sound.047</rom>
			<rom type="file" offset="0x3D">Sound.048</rom>
			<rom type="file" offset="0x3E">Sound.049</rom>
			<rom type="shell" offset="0">silp_at</rom>
		</romlist>
		<titlelist>
			<title code="0x10">Sound.001</title>
			<title code="0x11">Sound.002</title>
			<title code="0x12">Sound.003</title>
			<title code="0x13">Sound.004</title>
			<title code="0x14">Sound.005</title>
			<title code="0x15">Sound.006</title>
			<title code="0x16">Sound.007</title>
			<title code="0x17">Sound.008</title>
			<title code="0x18">Sound.009</title>
			<title code="0x19">Sound.010</title>
			<title code="0x1A">Sound.011</title>
			<title code="0x1B">Sound.012</title>
			<title code="0x1C">Sound.013</title>
			<title code="0x1D">Sound.014</title>
			<title code="0x1E">Sound.015</title>
			<title code="0x1F">Sound.016</title>
			<title code="0x20">Sound.017</title>
			<title code="0x21">Sound.018</title>
			<title code="0x22">Sound.019</title>
			<title code="0x23">Sound.020</title>
			<title code="0x24">Sound.021</title>
			<title code="0x25">Sound.022</title>
			<title code="0x26">Sound.023</title>
			<title code="0x27">Sound.024</title>
			<title code="0x2A">Sound.027</title>
			<title code="0x2B">Sound.028</title>
			<title code="0x2C">Sound.029</title>
			<title code="0x2E">Sound.032</title>
			<title code="0x2F">Sound.033</title>
			<title code="0x30">Sound.035</title>
			<title code="0x31">Sound.036</title>
			<title code="0x35">Sound.040</title>
			<title code="0x3C">Sound.047</title>
			<title code="0x3D">Sound.048</title>
			<title code="0x3E">Sound.049</title>
		</titlelist>
	</game>
	<game>
		<name>[PC/AT] Police Quest 2: The Vengeance (MT-32)</name>
		<driver type="beep">pcatdos</driver>
		<driveralias type="PC/AT">Sierra On-Line</driveralias>
		<options>
			<option name="clockmul" value="5"/>
			<option name="midiout" value="1"/>
			<option name="midiout_type" value="2"/>
		</options>
		<romlist archive="pq2_at">
			<rom type="file" offset="-1">silp_at.com</rom>
			<rom type="file" offset="0x08">MT32.DRV</rom>
			<rom type="file" offset="0x09">Patch.001</rom>
			<rom type="file" offset="0x10">Sound.001</rom>
			<rom type="file" offset="0x11">Sound.002</rom>
			<rom type="file" offset="0x12">Sound.003</rom>
			<rom type="file" offset="0x13">Sound.004</rom>
			<rom type="file" offset="0x14">Sound.005</rom>
			<rom type="file" offset="0x15">Sound.006</rom>
			<rom type="file" offset="0x16">Sound.007</rom>
			<rom type="file" offset="0x17">Sound.008</rom>
			<rom type="file" offset="0x18">Sound.009</rom>
			<rom type="file" offset="0x19">Sound.010</rom>
			<rom type="file" offset="0x1A">Sound.011</rom>
			<rom type="file" offset="0x1B">Sound.012</rom>
			<rom type="file" offset="0x1C">Sound.013</rom>
			<rom type="file" offset="0x1D">Sound.014</rom>
			<rom type="file" offset="0x1E">Sound.015</rom>
			<rom type="file" offset="0x1F">Sound.016</rom>
			<rom type="file" offset="0x20">Sound.017</rom>
			<rom type="file" offset="0x21">Sound.018</rom>
			<rom type="file" offset="0x22">Sound.019</rom>
			<rom type="file" offset="0x23">Sound.020</rom>
			<rom type="file" offset="0x24">Sound.021</rom>
			<rom type="file" offset="0x25">Sound.022</rom>
			<rom type="file" offset="0x26">Sound.023</rom>
			<rom type="file" offset="0x27">Sound.024</rom>
			<rom type="file" offset="0x28">Sound.025</rom>
			<rom type="file" offset="0x29">Sound.026</rom>
			<rom type="file" offset="0x2A">Sound.027</rom>
			<rom type="file" offset="0x2B">Sound.028</rom>
			<rom type="file" offset="0x2C">Sound.029</rom>
			<rom type="file" offset="0x2D">Sound.030</rom>
			<rom type="file" offset="0x2E">Sound.032</rom>
			<rom type="file" offset="0x2F">Sound.033</rom>
			<rom type="file" offset="0x30">Sound.035</rom>
			<rom type="file" offset="0x31">Sound.036</rom>
			<rom type="file" offset="0x32">Sound.037</rom>
			<rom type="file" offset="0x33">Sound.038</rom>
			<rom type="file" offset="0x34">Sound.039</rom>
			<rom type="file" offset="0x35">Sound.040</rom>
			<rom type="file" offset="0x36">Sound.041</rom>
			<rom type="file" offset="0x37">Sound.042</rom>
			<rom type="file" offset="0x38">Sound.043</rom>
			<rom type="file" offset="0x39">Sound.044</rom>
			<rom type="file" offset="0x3A">Sound.045</rom>
			<rom type="file" offset="0x3B">Sound.046</rom>
			<rom type="file" offset="0x3C">Sound.047</rom>
			<rom type="file" offset="0x3D">Sound.048</rom>
			<rom type="file" offset="0x3E">Sound.049</rom>
			<rom type="shell" offset="0">silp_at</rom>
		</romlist>
		<titlelist>
			<title code="0x10">Sound.001</title>
			<title code="0x11">Sound.002</title>
			<title code="0x12">Sound.003</title>
			<title code="0x13">Sound.004</title>
			<title code="0x14">Sound.005</title>
			<title code="0x15">Sound.006</title>
			<title code="0x16">Sound.007</title>
			<title code="0x17">Sound.008</title>
			<title code="0x18">Sound.009</title>
			<title code="0x19">Sound.010</title>
			<title code="0x1A">Sound.011</title>
			<title code="0x1B">Sound.012</title>
			<title code="0x1C">Sound.013</title>
			<title code="0x1D">Sound.014</title>
			<title code="0x1E">Sound.015</title>
			<title code="0x1F">Sound.016</title>
			<title code="0x20">Sound.017</title>
			<title code="0x21">Sound.018</title>
			<title code="0x22">Sound.019</title>
			<title code="0x23">Sound.020</title>
			<title code="0x24">Sound.021</title>
			<title code="0x25">Sound.022</title>
			<title code="0x26">Sound.023</title>
			<title code="0x27">Sound.024</title>
			<title code="0x2A">Sound.027</title>
			<title code="0x2B">Sound.028</title>
			<title code="0x2C">Sound.029</title>
			<title code="0x2E">Sound.032</title>
			<title code="0x2F">Sound.033</title>
			<title code="0x30">Sound.035</title>
			<title code="0x31">Sound.036</title>
			<title code="0x35">Sound.040</title>
			<title code="0x3C">Sound.047</title>
			<title code="0x3D">Sound.048</title>
			<title code="0x3E">Sound.049</title>
		</titlelist>
	</game>
	<game>
		<name>[PC/AT] Police Quest 2: The Vengeance (Munt, MT-32 emulation)</name>
		<driver type="beep">pcatdos</driver>
		<driveralias type="PC/AT">Sierra On-Line</driveralias>
		<options>
			<option name="clockmul" value="5"/>
			<option name="midiout" value="1"/>
			<option name="midiout_type" value="1"/>
		</options>
		<romlist archive="pq2_at">
			<rom type="file" offset="-1">silp_at.com</rom>
			<rom type="file" offset="0x08">MT32.DRV</rom>
			<rom type="file" offset="0x09">Patch.001</rom>
			<rom type="file" offset="0x10">Sound.001</rom>
			<rom type="file" offset="0x11">Sound.002</rom>
			<rom type="file" offset="0x12">Sound.003</rom>
			<rom type="file" offset="0x13">Sound.004</rom>
			<rom type="file" offset="0x14">Sound.005</rom>
			<rom type="file" offset="0x15">Sound.006</rom>
			<rom type="file" offset="0x16">Sound.007</rom>
			<rom type="file" offset="0x17">Sound.008</rom>
			<rom type="file" offset="0x18">Sound.009</rom>
			<rom type="file" offset="0x19">Sound.010</rom>
			<rom type="file" offset="0x1A">Sound.011</rom>
			<rom type="file" offset="0x1B">Sound.012</rom>
			<rom type="file" offset="0x1C">Sound.013</rom>
			<rom type="file" offset="0x1D">Sound.014</rom>
			<rom type="file" offset="0x1E">Sound.015</rom>
			<rom type="file" offset="0x1F">Sound.016</rom>
			<rom type="file" offset="0x20">Sound.017</rom>
			<rom type="file" offset="0x21">Sound.018</rom>
			<rom type="file" offset="0x22">Sound.019</rom>
			<rom type="file" offset="0x23">Sound.020</rom>
			<rom type="file" offset="0x24">Sound.021</rom>
			<rom type="file" offset="0x25">Sound.022</rom>
			<rom type="file" offset="0x26">Sound.023</rom>
			<rom type="file" offset="0x27">Sound.024</rom>
			<rom type="file" offset="0x28">Sound.025</rom>
			<rom type="file" offset="0x29">Sound.026</rom>
			<rom type="file" offset="0x2A">Sound.027</rom>
			<rom type="file" offset="0x2B">Sound.028</rom>
			<rom type="file" offset="0x2C">Sound.029</rom>
			<rom type="file" offset="0x2D">Sound.030</rom>
			<rom type="file" offset="0x2E">Sound.032</rom>
			<rom type="file" offset="0x2F">Sound.033</rom>
			<rom type="file" offset="0x30">Sound.035</rom>
			<rom type="file" offset="0x31">Sound.036</rom>
			<rom type="file" offset="0x32">Sound.037</rom>
			<rom type="file" offset="0x33">Sound.038</rom>
			<rom type="file" offset="0x34">Sound.039</rom>
			<rom type="file" offset="0x35">Sound.040</rom>
			<rom type="file" offset="0x36">Sound.041</rom>
			<rom type="file" offset="0x37">Sound.042</rom>
			<rom type="file" offset="0x38">Sound.043</rom>
			<rom type="file" offset="0x39">Sound.044</rom>
			<rom type="file" offset="0x3A">Sound.045</rom>
			<rom type="file" offset="0x3B">Sound.046</rom>
			<rom type="file" offset="0x3C">Sound.047</rom>
			<rom type="file" offset="0x3D">Sound.048</rom>
			<rom type="file" offset="0x3E">Sound.049</rom>
			<rom type="shell" offset="0">silp_at</rom>
		</romlist>
		<titlelist>
			<title code="0x10">Sound.001</title>
			<title code="0x11">Sound.002</title>
			<title code="0x12">Sound.003</title>
			<title code="0x13">Sound.004</title>
			<title code="0x14">Sound.005</title>
			<title code="0x15">Sound.006</title>
			<title code="0x16">Sound.007</title>
			<title code="0x17">Sound.008</title>
			<title code="0x18">Sound.009</title>
			<title code="0x19">Sound.010</title>
			<title code="0x1A">Sound.011</title>
			<title code="0x1B">Sound.012</title>
			<title code="0x1C">Sound.013</title>
			<title code="0x1D">Sound.014</title>
			<title code="0x1E">Sound.015</title>
			<title code="0x1F">Sound.016</title>
			<title code="0x20">Sound.017</title>
			<title code="0x21">Sound.018</title>
			<title code="0x22">Sound.019</title>
			<title code="0x23">Sound.020</title>
			<title code="0x24">Sound.021</title>
			<title code="0x25">Sound.022</title>
			<title code="0x26">Sound.023</title>
			<title code="0x27">Sound.024</title>
			<title code="0x2A">Sound.027</title>
			<title code="0x2B">Sound.028</title>
			<title code="0x2C">Sound.029</title>
			<title code="0x2E">Sound.032</title>
			<title code="0x2F">Sound.033</title>
			<title code="0x30">Sound.035</title>
			<title code="0x31">Sound.036</title>
			<title code="0x35">Sound.040</title>
			<title code="0x3C">Sound.047</title>
			<title code="0x3D">Sound.048</title>
			<title code="0x3E">Sound.049</title>
		</titlelist>
	</game>
	<game>
		<name>[PC/AT] Space Quest 3: The Pirates of Pestulon (SAA1099)</name>
		<driver type="gameblaster">pcatdos</driver>
		<driveralias type="PC/AT">Sierra On-Line</driveralias>
		<options>
			<option name="clockmul" value="5"/>
			<option name="opl2_mix" value="0x100"/>
		</options>
		<romlist archive="sq3_at">
			<rom type="file" offset="-1">silp_at.com</rom>
			<rom type="file" offset="0x08">CMS.DRV</rom>
			<rom type="file" offset="0x09">PATCH.101</rom>
			<rom type="file" offset="0x10">Sound.001</rom>
			<rom type="file" offset="0x11">Sound.010</rom>
			<rom type="file" offset="0x12">Sound.011</rom>
			<rom type="file" offset="0x13">Sound.013</rom>
			<rom type="file" offset="0x14">Sound.014</rom>
			<rom type="file" offset="0x15">Sound.016</rom>
			<rom type="file" offset="0x16">Sound.023</rom>
			<rom type="file" offset="0x17">Sound.024</rom>
			<rom type="file" offset="0x18">Sound.025</rom>
			<rom type="file" offset="0x19">Sound.026</rom>
			<rom type="file" offset="0x1A">Sound.064</rom>
			<rom type="file" offset="0x1B">Sound.069</rom>
			<rom type="file" offset="0x1C">Sound.071</rom>
			<rom type="file" offset="0x1D">Sound.072</rom>
			<rom type="file" offset="0x1E">Sound.073</rom>
			<rom type="file" offset="0x1F">Sound.081</rom>
			<rom type="file" offset="0x20">Sound.086</rom>
			<rom type="file" offset="0x21">Sound.087</rom>
			<rom type="file" offset="0x22">Sound.093</rom>
			<rom type="file" offset="0x23">Sound.094</rom>
			<rom type="file" offset="0x24">Sound.099</rom>
			<rom type="shell" offset="0">silp_at</rom>
		</romlist>
		<titlelist>
			<title code="0x10">Sound.001</title>
			<title code="0x11">Sound.010</title>
			<title code="0x12">Sound.011</title>
			<title code="0x13">Sound.013</title>
			<title code="0x14">Sound.014</title>
			<title code="0x15">Sound.016</title>
			<title code="0x16">Sound.023</title>
			<title code="0x17">Sound.024</title>
			<title code="0x18">Sound.025</title>
			<title code="0x19">Sound.026</title>
			<title code="0x1A">Sound.064</title>
			<title code="0x1B">Sound.069</title>
			<title code="0x1C">Sound.071</title>
			<title code="0x1D">Sound.072</title>
			<title code="0x1E">Sound.073</title>
			<title code="0x1F">Sound.081</title>
			<title code="0x20">Sound.086</title>
			<title code="0x21">Sound.087</title>
			<title code="0x22">Sound.093</title>
			<title code="0x23">Sound.094</title>
			<title code="0x24">Sound.099</title>
		</titlelist>
	</game>
	<game>
		<name>[PC/AT] Space Quest 3: The Pirates of Pestulon (YM3812)</name>
		<driver type="adlib">pcatdos</driver>
		<driveralias type="PC/AT">Sierra On-Line</driveralias>
		<options>
			<option name="clockmul" value="5"/>
			<option name="opl2_mix" value="0x100"/>
		</options>
		<romlist archive="sq3_at">
			<rom type="file" offset="-1">silp_at.com</rom>
			<rom type="file" offset="0x08">ADL.DRV</rom>
			<rom type="file" offset="0x09">Patch.003</rom>
			<rom type="file" offset="0x10">Sound.001</rom>
			<rom type="file" offset="0x11">Sound.010</rom>
			<rom type="file" offset="0x12">Sound.011</rom>
			<rom type="file" offset="0x13">Sound.013</rom>
			<rom type="file" offset="0x14">Sound.014</rom>
			<rom type="file" offset="0x15">Sound.016</rom>
			<rom type="file" offset="0x16">Sound.023</rom>
			<rom type="file" offset="0x17">Sound.024</rom>
			<rom type="file" offset="0x18">Sound.025</rom>
			<rom type="file" offset="0x19">Sound.026</rom>
			<rom type="file" offset="0x1A">Sound.064</rom>
			<rom type="file" offset="0x1B">Sound.069</rom>
			<rom type="file" offset="0x1C">Sound.071</rom>
			<rom type="file" offset="0x1D">Sound.072</rom>
			<rom type="file" offset="0x1E">Sound.073</rom>
			<rom type="file" offset="0x1F">Sound.081</rom>
			<rom type="file" offset="0x20">Sound.086</rom>
			<rom type="file" offset="0x21">Sound.087</rom>
			<rom type="file" offset="0x22">Sound.093</rom>
			<rom type="file" offset="0x23">Sound.094</rom>
			<rom type="file" offset="0x24">Sound.099</rom>
			<rom type="shell" offset="0">silp_at</rom>
		</romlist>
		<titlelist>
			<title code="0x10">Sound.001</title>
			<title code="0x11">Sound.010</title>
			<title code="0x12">Sound.011</title>
			<title code="0x13">Sound.013</title>
			<title code="0x14">Sound.014</title>
			<title code="0x15">Sound.016</title>
			<title code="0x16">Sound.023</title>
			<title code="0x17">Sound.024</title>
			<title code="0x18">Sound.025</title>
			<title code="0x19">Sound.026</title>
			<title code="0x1A">Sound.064</title>
			<title code="0x1B">Sound.069</title>
			<title code="0x1C">Sound.071</title>
			<title code="0x1D">Sound.072</title>
			<title code="0x1E">Sound.073</title>
			<title code="0x1F">Sound.081</title>
			<title code="0x20">Sound.086</title>
			<title code="0x21">Sound.087</title>
			<title code="0x22">Sound.093</title>
			<title code="0x23">Sound.094</title>
			<title code="0x24">Sound.099</title>
		</titlelist>
	</game>
	<game>
		<name>[PC/AT] Space Quest 3: The Pirates of Pestulon (MT-32)</name>
		<driver type="beep">pcatdos</driver>
		<driveralias type="PC/AT">Sierra On-Line</driveralias>
		<options>
			<option name="clockmul" value="5"/>
			<option name="midiout" value="1"/>
			<option name="midiout_type" value="2"/>
		</options>
		<romlist archive="sq3_at">
			<rom type="file" offset="-1">silp_at.com</rom>
			<rom type="file" offset="0x08">MT32.DRV</rom>
			<rom type="file" offset="0x09">Patch.001</rom>
			<rom type="file" offset="0x10">Sound.001</rom>
			<rom type="file" offset="0x11">Sound.010</rom>
			<rom type="file" offset="0x12">Sound.011</rom>
			<rom type="file" offset="0x13">Sound.013</rom>
			<rom type="file" offset="0x14">Sound.014</rom>
			<rom type="file" offset="0x15">Sound.016</rom>
			<rom type="file" offset="0x16">Sound.023</rom>
			<rom type="file" offset="0x17">Sound.024</rom>
			<rom type="file" offset="0x18">Sound.025</rom>
			<rom type="file" offset="0x19">Sound.026</rom>
			<rom type="file" offset="0x1A">Sound.064</rom>
			<rom type="file" offset="0x1B">Sound.069</rom>
			<rom type="file" offset="0x1C">Sound.071</rom>
			<rom type="file" offset="0x1D">Sound.072</rom>
			<rom type="file" offset="0x1E">Sound.073</rom>
			<rom type="file" offset="0x1F">Sound.081</rom>
			<rom type="file" offset="0x20">Sound.086</rom>
			<rom type="file" offset="0x21">Sound.087</rom>
			<rom type="file" offset="0x22">Sound.093</rom>
			<rom type="file" offset="0x23">Sound.094</rom>
			<rom type="file" offset="0x24">Sound.099</rom>
			<rom type="shell" offset="0">silp_at</rom>
		</romlist>
		<titlelist>
			<title code="0x10">Sound.001</title>
			<title code="0x11">Sound.010</title>
			<title code="0x12">Sound.011</title>
			<title code="0x13">Sound.013</title>
			<title code="0x14">Sound.014</title>
			<title code="0x15">Sound.016</title>
			<title code="0x16">Sound.023</title>
			<title code="0x17">Sound.024</title>
			<title code="0x18">Sound.025</title>
			<title code="0x19">Sound.026</title>
			<title code="0x1A">Sound.064</title>
			<title code="0x1B">Sound.069</title>
			<title code="0x1C">Sound.071</title>
			<title code="0x1D">Sound.072</title>
			<title code="0x1E">Sound.073</title>
			<title code="0x1F">Sound.081</title>
			<title code="0x20">Sound.086</title>
			<title code="0x21">Sound.087</title>
			<title code="0x22">Sound.093</title>
			<title code="0x23">Sound.094</title>
			<title code="0x24">Sound.099</title>
		</titlelist>
	</game>
	<game>
		<name>[PC/AT] Space Quest 3: The Pirates of Pestulon (Munt, MT-32 emulation)</name>
		<driver type="beep">pcatdos</driver>
		<driveralias type="PC/AT">Sierra On-Line</driveralias>
		<options>
			<option name="clockmul" value="5"/>
			<option name="midiout" value="1"/>
			<option name="midiout_type" value="1"/>
		</options>
		<romlist archive="sq3_at">
			<rom type="file" offset="-1">silp_at.com</rom>
			<rom type="file" offset="0x08">MT32.DRV</rom>
			<rom type="file" offset="0x09">Patch.001</rom>
			<rom type="file" offset="0x10">Sound.001</rom>
			<rom type="file" offset="0x11">Sound.010</rom>
			<rom type="file" offset="0x12">Sound.011</rom>
			<rom type="file" offset="0x13">Sound.013</rom>
			<rom type="file" offset="0x14">Sound.014</rom>
			<rom type="file" offset="0x15">Sound.016</rom>
			<rom type="file" offset="0x16">Sound.023</rom>
			<rom type="file" offset="0x17">Sound.024</rom>
			<rom type="file" offset="0x18">Sound.025</rom>
			<rom type="file" offset="0x19">Sound.026</rom>
			<rom type="file" offset="0x1A">Sound.064</rom>
			<rom type="file" offset="0x1B">Sound.069</rom>
			<rom type="file" offset="0x1C">Sound.071</rom>
			<rom type="file" offset="0x1D">Sound.072</rom>
			<rom type="file" offset="0x1E">Sound.073</rom>
			<rom type="file" offset="0x1F">Sound.081</rom>
			<rom type="file" offset="0x20">Sound.086</rom>
			<rom type="file" offset="0x21">Sound.087</rom>
			<rom type="file" offset="0x22">Sound.093</rom>
			<rom type="file" offset="0x23">Sound.094</rom>
			<rom type="file" offset="0x24">Sound.099</rom>
			<rom type="shell" offset="0">silp_at</rom>
		</romlist>
		<titlelist>
			<title code="0x10">Sound.001</title>
			<title code="0x11">Sound.010</title>
			<title code="0x12">Sound.011</title>
			<title code="0x13">Sound.013</title>
			<title code="0x14">Sound.014</title>
			<title code="0x15">Sound.016</title>
			<title code="0x16">Sound.023</title>
			<title code="0x17">Sound.024</title>
			<title code="0x18">Sound.025</title>
			<title code="0x19">Sound.026</title>
			<title code="0x1A">Sound.064</title>
			<title code="0x1B">Sound.069</title>
			<title code="0x1C">Sound.071</title>
			<title code="0x1D">Sound.072</title>
			<title code="0x1E">Sound.073</title>
			<title code="0x1F">Sound.081</title>
			<title code="0x20">Sound.086</title>
			<title code="0x21">Sound.087</title>
			<title code="0x22">Sound.093</title>
			<title code="0x23">Sound.094</title>
			<title code="0x24">Sound.099</title>
		</titlelist>
	</game>
	<game>
		<name>[PC/AT] Hoyle's Book of Games (SAA1099)</name>
		<driver type="gameblaster">pcatdos</driver>
		<driveralias type="PC/AT">Sierra On-Line</driveralias>
		<options>
			<option name="clockmul" value="5"/>
			<option name="opl2_mix" value="0x100"/>
		</options>
		<romlist archive="hoyle_at">
			<rom type="file" offset="-1">silp_at.com</rom>
			<rom type="file" offset="0x08">CMS.DRV</rom>
			<rom type="file" offset="0x09">PATCH.101</rom>
			<rom type="file" offset="0x10">Sound.001</rom>
			<rom type="file" offset="0x11">Sound.002</rom>
			<rom type="file" offset="0x12">Sound.003</rom>
			<rom type="file" offset="0x13">Sound.004</rom>
			<rom type="file" offset="0x14">Sound.005</rom>
			<rom type="file" offset="0x15">Sound.006</rom>
			<rom type="file" offset="0x16">Sound.007</rom>
			<rom type="file" offset="0x17">Sound.008</rom>
			<rom type="file" offset="0x18">Sound.009</rom>
			<rom type="file" offset="0x19">Sound.010</rom>
			<rom type="file" offset="0x1A">Sound.011</rom>
			<rom type="file" offset="0x1B">Sound.012</rom>
			<rom type="file" offset="0x1C">Sound.013</rom>
			<rom type="file" offset="0x1D">Sound.014</rom>
			<rom type="file" offset="0x1E">Sound.015</rom>
			<rom type="file" offset="0x1F">Sound.017</rom>
			<rom type="file" offset="0x20">Sound.018</rom>
			<rom type="file" offset="0x21">Sound.019</rom>
			<rom type="file" offset="0x22">Sound.020</rom>
			<rom type="file" offset="0x23">Sound.021</rom>
			<rom type="file" offset="0x24">Sound.022</rom>
			<rom type="file" offset="0x25">Sound.023</rom>
			<rom type="file" offset="0x26">Sound.024</rom>
			<rom type="file" offset="0x27">Sound.025</rom>