<?xml version="1.0" encoding="Shift_JIS"?>
<?xml-stylesheet type="text/xsl" href="hoot.xsl"?>
<!DOCTYPE gamelist [
	<!ELEMENT gamelist (game|bind|childlists)*>
	<!ATTLIST gamelist date CDATA #IMPLIED>
	<!ELEMENT childlists (list)*>
	<!ELEMENT list (#PCDATA)>
	<!ELEMENT bind (exts,driver,options?)>
	<!ELEMENT exts (ext)*>
	<!ELEMENT ext (#PCDATA)>
	<!ELEMENT game (name,driver,driveralias?,options?,romlist?,titlelist?)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT driver (#PCDATA)>
	<!ATTLIST driver type CDATA #IMPLIED>
	<!ELEMENT driveralias (#PCDATA)>
	<!ATTLIST driveralias type CDATA #IMPLIED>
	<!ELEMENT options (option)*>
	<!ELEMENT option EMPTY>
	<!ATTLIST option name CDATA #REQUIRED
					 value CDATA #REQUIRED>
	<!ELEMENT romlist (rom)*>
	<!ATTLIST romlist archive CDATA #IMPLIED>
	<!ELEMENT rom (#PCDATA)>
	<!ATTLIST rom type CDATA #REQUIRED
				  offset CDATA #IMPLIED
				  crc32 CDATA #IMPLIED>
	<!ELEMENT titlelist (title|range)*>
	<!ELEMENT title (#PCDATA)>
	<!ATTLIST title code CDATA #REQUIRED
					type CDATA #IMPLIED>
	<!ELEMENT range (#PCDATA)>
	<!ATTLIST range min CDATA #REQUIRED
					max CDATA #REQUIRED
					extcode CDATA #IMPLIED>
]>
<gamelist date="2007/07/21">
	<!-- //TIERHEIT -->
	<game>
		<name>[PC-9801] Aiza (エイジア) (YM2203)</name>
		<driver type="opn">pc98dos</driver>
		<driveralias type="PC-9801">Tier Heit</driveralias>
		<options>
			<option name="clockmul" value="8"/>
		</options>
		<romlist archive="aiza_98">
			<rom type="file" offset="-1">aiza_98.com</rom>
			<rom type="file" offset="-1">AIZA.EXE</rom>
			<rom type="conin" offset="5">AIZA.EXE</rom>
			<rom type="file" offset="6" >SOUND.DAT</rom>
			<rom type="file" offset="11">BARIANTE.ROJ</rom>
			<rom type="file" offset="12">BARNIA.ROJ</rom>
			<rom type="file" offset="13">BOSS1.ROJ</rom>
			<rom type="file" offset="14">BOSS2.ROJ</rom>
			<rom type="file" offset="15">BOSSROOM.ROJ</rom>
			<rom type="file" offset="16">CASTLE.ROJ</rom>
			<rom type="file" offset="17">CAVERN1.ROJ</rom>
			<rom type="file" offset="18">CAVERN2.ROJ</rom>
			<rom type="file" offset="19">EDING.ROJ</rom>
			<rom type="file" offset="20">ENEMY.ROJ</rom>
			<rom type="file" offset="21">EPILOGUE.ROJ</rom>
			<rom type="file" offset="22">FIELD1.ROJ</rom>
			<rom type="file" offset="23">FLUTE.ROJ</rom>
			<rom type="file" offset="24">GAMEOVER.ROJ</rom>
			<rom type="file" offset="25">GARUTEGA.ROJ</rom>
			<rom type="file" offset="26">HOUSE1.ROJ</rom>
			<rom type="file" offset="27">HOUSE2.ROJ</rom>
			<rom type="file" offset="28">JASIN.ROJ</rom>
			<rom type="file" offset="29">KIIL.ROJ</rom>
			<rom type="file" offset="30">KING.ROJ</rom>
			<rom type="file" offset="31">KYUDEN1.ROJ</rom>
			<rom type="file" offset="32">MORI.ROJ</rom>
			<rom type="file" offset="33">OPING.ROJ</rom>
			<rom type="file" offset="34">OPING1.ROJ</rom>
			<rom type="file" offset="35">OPING2.ROJ</rom>
			<rom type="file" offset="36">RAFIA.ROJ</rom>
			<rom type="file" offset="37">RAMIIRU.ROJ</rom>
			<rom type="file" offset="38">ROJ.ROJ</rom>
			<rom type="file" offset="39">RUTH.ROJ</rom>
			<rom type="file" offset="40">SARA.ROJ</rom>
			<rom type="file" offset="41">SHOP.ROJ</rom>
			<rom type="file" offset="42">SYRINE.ROJ</rom>
			<rom type="file" offset="43">TAKE.ROJ</rom>
			<rom type="file" offset="44">TOWN1.ROJ</rom>
			<rom type="file" offset="45">TOWN2.ROJ</rom>
			<rom type="file" offset="46">TOWN3.ROJ</rom>
			<rom type="file" offset="47">TOWN4.ROJ</rom>
			<rom type="file" offset="48">ZAGRASS.ROJ</rom>
			<rom type="file" offset="49">ZODEIAGG.ROJ</rom>
			<rom type="file" offset="50">ﾌｨｰｽﾞ.ROJ</rom>
			<rom type="shell" offset="0">aiza_98</rom>
		</romlist>
		<titlelist>
			<title code="33">オープニング</title>
		<!--	<title code="34">オープニング</title> -->
		<!--	<title code="35">ゲームオーバー</title> -->
			<title code="44">村のテーマ</title>
		<!--	<title code="45">村のテーマ</title> -->
		<!--	<title code="46">村のテーマ</title> -->
		<!--	<title code="47">村のテーマ</title> -->
			<title code="26">民家</title>
			<title code="27">寂しい民家</title>
			<title code="41">ショップ</title>
			<title code="22">フィールド</title>
			<title code="17">洞窟</title>
			<title code="32">森</title>
			<title code="37">ラミールの塔</title>
			<title code="20">敵のテーマ</title>
			<title code="15">ボスの部屋</title>
			<title code="13">ボスとの戦闘</title>
			<title code="16">ワイスレム城</title>
			<title code="30">王室</title>
			<title code="39">ルースのテーマ</title>
			<title code="11">バリアンテ</title>
			<title code="18">海底洞窟</title>
			<title code="42">海底神殿</title>
			<title code="40">女神の部屋</title>
		<!--	<title code="23">笛</title> -->
			<title code="29">キールの山</title>
			<title code="12">魔の森</title>
			<title code="31">宮殿</title>
			<title code="49">ゾディ・アッグ</title>
			<title code="48">ザグラス</title>
			<title code="28">邪神のテーマ</title>
			<title code="14">邪神との戦い</title>
			<title code="21">エピローグ</title>
			<title code="19">エンディング</title>
			<title code="24">ゲームオーバー</title>
			<title code="25">GARUTEGA.ROJ</title>
			<title code="36">RAFIA.ROJ</title>
		<!--	<title code="38">(無音)</title> -->
		<!--	<title code="43">(無音)</title> -->
			<title code="50">ﾌｨｰｽﾞ.ROJ</title>
		</titlelist>
	</game>
	<game>
		<name>[X68000] Chase H.Q. (チェイスH.Q.) (YM2151+MSM6258)</name>
		<driver type="generic">x68k</driver>
		<driveralias type="X68000">Tier Heit</driveralias>
		<options>
			<option name="opm_mix" value="0x70"/>
			<option name="pcm_mix" value="0x82"/>
		</options>
		<romlist archive="chq68snd">
			<rom type="code" offset="0x00000">axd68snd.bin</rom>
			<rom type="x" offset="0x10000">AXDRIVE.X</rom>
			<rom type="code" offset="0x13000">CHASE.PDX</rom>
			<rom type="code" offset="0x34000">ARREST.MDX</rom>
			<rom type="code" offset="0x38000">CHICAGO.MDX</rom>
			<rom type="code" offset="0x3C000">COUNT.MDX</rom>
			<rom type="code" offset="0x40000">COUNT2.MDX</rom>
			<rom type="code" offset="0x44000">DEMOTITL.MDX</rom>
			<rom type="code" offset="0x48000">ENDING.MDX</rom>
			<rom type="code" offset="0x4C000">GAME_OVE.MDX</rom>
			<rom type="code" offset="0x50000">IDAHO.MDX</rom>
			<rom type="code" offset="0x54000">IPL.MDX</rom>
			<rom type="code" offset="0x58000">LOS.MDX</rom>
			<rom type="code" offset="0x5C000">MAIN.MDX</rom>
			<rom type="code" offset="0x60000">NAME.MDX</rom>
			<rom type="code" offset="0x64000">NEW_YORK.MDX</rom>
			<rom type="code" offset="0x68000">PERFECT.MDX</rom>
			<rom type="code" offset="0x6C000">PIPOPA.MDX</rom>
			<rom type="code" offset="0x70000">ROUNDSTA.MDX</rom>
			<rom type="code" offset="0x74000">WASHINGT.MDX</rom>
		</romlist>
		<titlelist>
			<title code="0x09">IPL</title>
			<title code="0x05">Demo Title</title>
			<title code="0x10">Round Start</title>
			<title code="0x0a">Los Angeles</title>
			<title code="0x08">Idaho</title>
			<title code="0x11">Washington</title>
			<title code="0x02">Chicago</title>
			<title code="0x0d">New York</title>
			<title code="0x0b">This is Chase H.Q.!</title>
			<title code="0x03">Count Down</title>
			<title code="0x04">Count Down Type-2</title>
			<title code="0x01">Arrest</title>
			<title code="0x0e">Perfect Chaser</title>
			<title code="0x0c">My Name &amp; Your Name</title>
			<title code="0x06">Ending Theme</title>
			<title code="0x07">Game Over</title>
			<title code="0x0f">Pi-Po-Pa</title>
		</titlelist>
	</game>
</gamelist>